'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
function memoryStorage(){const data=new Map();return{getItem:k=>data.has(k)?data.get(k):null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)}}
global.localStorage=memoryStorage();
delete global.RollandsDemoScenario;delete global.RollandsDemoWorkflows;
require('../apps/portal/demo-scenario.js');
require('../apps/portal/demo-workflows.js');
const Demo=global.RollandsDemoScenario,Flows=global.RollandsDemoWorkflows;

test('gemensamt demoscenario laddas och kan återställas',()=>{assert.ok(Demo);const state=Demo.state();assert.equal(state.version,Demo.VERSION);Demo.patch(next=>{next.bankPayments[0].status='proposal-created'});assert.equal(Demo.state().bankPayments[0].status,'proposal-created');assert.equal(Demo.reset().bankPayments[0].status,'unmatched')});

test('bankmatchning 310002 använder samma restbelopp och faktura i alla lager',()=>{const state=Demo.reset(),payment=state.bankPayments.find(row=>row.reference==='310002'),invoice=state.customerInvoices.find(row=>row.invoiceNumber==='310002'),proposal=state.automationProposals.find(row=>row.type==='bank-payment-match'&&row.suggestion.invoiceNumber==='310002');assert.ok(payment&&invoice&&proposal);assert.equal(payment.amountOre,392500);assert.equal(invoice.remainingOre,payment.amountOre);assert.equal(proposal.review.amountOre,payment.amountOre);assert.equal(proposal.suggestion.invoiceId,invoice.id);assert.deepEqual(proposal.review.accountingLines.map(row=>[row.account,row.debitOre,row.creditOre]),[['1930',392500,0],['1510',0,392500]])});

test('automationsförslag för leverantörsfaktura pekar på verklig demofaktura och leverantör',()=>{const state=Demo.reset(),proposal=state.automationProposals.find(row=>row.type==='supplier-invoice-coding'),invoice=state.supplierInvoices.find(row=>row.id===proposal.sourceId),supplier=state.suppliers.find(row=>row.id===invoice.supplierId);assert.equal(invoice.supplierInvoiceNumber,'KE-2088');assert.equal(supplier.name,'Kustens Emballage AB');assert.equal(proposal.context.supplierName,supplier.name);assert.equal(proposal.review.amountOre,invoice.totalOre)});

test('dokumentkopplingar till leverantörsfaktura pekar på befintliga fakturor',()=>{const state=Demo.reset(),ids=new Set(state.supplierInvoices.map(row=>row.id)),links=state.documents.flatMap(document=>(document.links||[]).filter(link=>link.entityType==='supplier-invoice'));assert.ok(links.length>=2);for(const link of links)assert.ok(ids.has(link.entityId),`Saknad leverantörsfaktura för dokumentlänk ${link.entityId}`)});

test('bokförd leverantörsbetalning GF-8821 har motsvarande betalning och balanserad verifikation',()=>{const state=Demo.reset(),payment=state.supplierPayments.find(row=>row.supplierInvoiceNumber==='GF-8821'),entry=state.accountingEntries.find(row=>row.sourceId===payment.id);assert.ok(entry);const debit=entry.lines.reduce((sum,row)=>sum+row.debitOre,0),credit=entry.lines.reduce((sum,row)=>sum+row.creditOre,0);assert.equal(debit,payment.amountOre);assert.equal(debit,credit);assert.deepEqual(entry.lines.map(row=>row.account),['2440','1930'])});

test('BKS-771 bokför skuld, förbereds, frisläpps, bankbekräftas och nollar 2440',()=>{Demo.reset();assert.ok(Flows);let state=Flows.postSupplierInvoice('sinv-demo-3');let invoice=state.supplierInvoices.find(row=>row.id==='sinv-demo-3');const invoiceEntry=state.accountingEntries.find(row=>row.sourceType==='supplier-invoice'&&row.sourceId==='sinv-demo-3');assert.ok(invoiceEntry);assert.equal(invoice.openAmountOre,437500);state=Flows.prepareSupplierPayment('sinv-demo-3');invoice=state.supplierInvoices.find(row=>row.id==='sinv-demo-3');let payment=state.supplierPayments.find(row=>row.supplierInvoiceId==='sinv-demo-3');assert.equal(invoice.status,'payment-prepared');assert.equal(payment.status,'prepared');assert.equal(payment.amountOre,437500);state=Flows.releaseSupplierPayment(payment.id);payment=state.supplierPayments.find(row=>row.id===payment.id);assert.equal(payment.status,'released');state=Flows.confirmSupplierPayment(payment.id,'BANK-DEMO-BKS-771');invoice=state.supplierInvoices.find(row=>row.id==='sinv-demo-3');payment=state.supplierPayments.find(row=>row.id===payment.id);const paymentEntry=state.accountingEntries.find(row=>row.sourceType==='supplier-payment'&&row.sourceId===payment.id);assert.equal(invoice.status,'paid');assert.equal(invoice.openAmountOre,0);assert.equal(payment.status,'paid');assert.equal(payment.confirmationReference,'BANK-DEMO-BKS-771');assert.ok(paymentEntry);const net2440=[invoiceEntry,paymentEntry].flatMap(entry=>entry.lines).filter(row=>row.account==='2440').reduce((sum,row)=>sum+row.debitOre-row.creditOre,0);assert.equal(net2440,0)});

test('betalningsflödet stoppar förberedelse före skuldbokföring och bankbekräftelse utan frisläppning',()=>{Demo.reset();assert.throws(()=>Flows.releaseSupplierPayment('saknas'),error=>error.code==='DEMO_PAYMENT_NOT_FOUND');assert.throws(()=>Flows.prepareSupplierPayment('sinv-demo-3'),error=>error.code==='DEMO_LIABILITY_NOT_POSTED');Flows.postSupplierInvoice('sinv-demo-3');Flows.prepareSupplierPayment('sinv-demo-3');const payment=Demo.state().supplierPayments.find(row=>row.supplierInvoiceId==='sinv-demo-3');assert.throws(()=>Flows.confirmSupplierPayment(payment.id),error=>error.code==='DEMO_PAYMENT_NOT_RELEASED')});

test('alla demoverifikationer är balanserade',()=>{const state=Demo.reset();for(const entry of state.accountingEntries){const debit=entry.lines.reduce((sum,row)=>sum+Number(row.debitOre||0),0),credit=entry.lines.reduce((sum,row)=>sum+Number(row.creditOre||0),0);assert.equal(debit,credit,`${entry.number} balanserar inte`)}});
