'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const Domain=require('../packages/payables/supplier-invoices.js');
const Db=require('../apps/api/database.js');
const Auth=require('../apps/api/auth.js');
const Payables=require('../apps/api/payables.js');

function seed(){const db=Db.openDatabase(':memory:');Payables.initializePayables(db);const company=Db.createCompany(db,{legalName:'Testbolag AB',displayName:'Testbolag',orgNumber:'559900-0001'});const passwordHash=Auth.hashPassword('Sakert testlosenord 2026!');const registrar=Db.createUser(db,{username:'registrar',displayName:'Registrerare',passwordHash});const approver=Db.createUser(db,{username:'approver',displayName:'Attestant',passwordHash});const supplier=Payables.createSupplier(db,{companyId:company.id,supplierNumber:'L-100',name:'Grön Grossist AB',bankgiro:'555-1234',defaultCostAccount:'4010'});const invoice=Payables.createSupplierInvoice(db,{companyId:company.id,supplierId:supplier.id,supplierInvoiceNumber:'GG-4401',invoiceDate:'2026-09-10',dueDate:'2026-10-10',totalOre:125000,vatOre:25000,registeredBy:registrar.id});return{db,company,registrar,approver,supplier,invoice}}

test('konteringsmodulen skapar balanserad leverantörskontering i ören',()=>{const coding=Domain.buildCoding({totalOre:125000,vatOre:25000,costAccount:'4010'});assert.equal(coding.debitOre,125000);assert.equal(coding.creditOre,125000);assert.deepEqual(coding.lines.map(x=>x.account),['4010','2641','2440']);});
test('felaktig kontering stoppas',()=>{assert.throws(()=>Domain.validateCoding({totalOre:125000,lines:[{account:'4010',debitOre:100000,creditOre:0},{account:'2440',debitOre:0,creditOre:125000}]}),e=>e.code==='UNBALANCED_CODING');});
test('registrerad användare får inte attestera sin egen faktura',()=>{const {db,company,registrar,invoice}=seed();try{const coding=Domain.buildCoding({totalOre:125000,vatOre:25000});Payables.saveCoding(db,{companyId:company.id,invoiceId:invoice.id,lines:coding.lines});assert.throws(()=>Payables.approve(db,{companyId:company.id,invoiceId:invoice.id,actorId:registrar.id}),e=>e.code==='SEPARATION_OF_DUTIES_FAILED');}finally{db.close()}});
test('attest låser konteringen och möjliggör betalningsförberedelse',()=>{const {db,company,registrar,approver,invoice}=seed();try{const coding=Domain.buildCoding({totalOre:125000,vatOre:25000});Payables.saveCoding(db,{companyId:company.id,invoiceId:invoice.id,lines:coding.lines});const approved=Payables.approve(db,{companyId:company.id,invoiceId:invoice.id,actorId:approver.id});assert.equal(approved.status,'approved');assert.equal(approved.approvedBy,approver.id);assert.match(approved.codingSha256,/^[a-f0-9]{64}$/);assert.throws(()=>Payables.saveCoding(db,{companyId:company.id,invoiceId:invoice.id,lines:coding.lines}),e=>e.code==='CODING_LOCKED');const payment=Payables.preparePayment(db,{companyId:company.id,invoiceId:invoice.id,paymentDate:'2026-09-16',amountOre:125000,account:'1930',preparedBy:registrar.id});assert.equal(payment.status,'prepared');assert.equal(payment.amountOre,125000);}finally{db.close()}});
test('PDF-underlag sparas med kontrollsumma och kan hämtas endast via företag',()=>{const {db,company,invoice}=seed();try{const bytes=Buffer.from('%PDF-1.4\n% test\n','ascii');const result=Payables.storeDocument(db,{companyId:company.id,invoiceId:invoice.id,name:'faktura.pdf',bytes});const stored=Payables.document(db,company.id,invoice.id);const storedBytes=Buffer.from(stored.bytes);assert.equal(result.sha256,crypto.createHash('sha256').update(bytes).digest('hex'));assert.deepEqual(storedBytes,bytes);assert.throws(()=>Payables.document(db,'fel-foretag',invoice.id),e=>e.code==='DOCUMENT_NOT_FOUND');}finally{db.close()}});
test('dagens utbetalningar summeras per status',()=>{const payments=[{paymentDate:'2026-09-16',amountOre:10000,status:'prepared'},{paymentDate:'2026-09-16',amountOre:20000,status:'released'},{paymentDate:'2026-09-16',amountOre:30000,status:'paid'},{paymentDate:'2026-09-17',amountOre:90000,status:'prepared'}];const summary=Domain.paymentSummary(payments,'2026-09-16');assert.equal(summary.count,3);assert.equal(summary.totalOre,60000);assert.equal(summary.byStatus.prepared,10000);assert.equal(summary.byStatus.released,20000);assert.equal(summary.byStatus.paid,30000);});
