'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const Domain=require('../packages/payables/supplier-invoices.js');
const Db=require('../apps/api/database.js');
const Auth=require('../apps/api/auth.js');
const Payables=require('../apps/api/payables.js');
const SupplierDocumentStore=require('../apps/api/supplier-invoice-document-store.js');
const SupplierAccounting=require('../apps/api/supplier-accounting.js');

function seed(){const db=Db.openDatabase(':memory:');Payables.initializePayables(db);SupplierAccounting.initializeSupplierAccounting(db);const company=Db.createCompany(db,{legalName:'Testbolag AB',displayName:'Testbolag',orgNumber:'559900-0001'});const passwordHash=Auth.hashPassword('Sakert testlosenord 2026!');const registrar=Db.createUser(db,{username:'registrar',displayName:'Registrerare',passwordHash});const approver=Db.createUser(db,{username:'approver',displayName:'Attestant',passwordHash});const accountant=Db.createUser(db,{username:'accountant',displayName:'Ekonom',passwordHash});const supplier=Payables.createSupplier(db,{companyId:company.id,supplierNumber:'L-100',name:'Grön Grossist AB',bankgiro:'555-1234',defaultCostAccount:'4010'});const invoice=Payables.createSupplierInvoice(db,{companyId:company.id,supplierId:supplier.id,supplierInvoiceNumber:'GG-4401',invoiceDate:'2026-09-10',dueDate:'2026-10-10',totalOre:125000,vatOre:25000,registeredBy:registrar.id});return{db,company,registrar,approver,accountant,supplier,invoice}}
function pdf(label='test'){return Buffer.from(`%PDF-1.4\n% ${label}\n`,'ascii')}
function attachPdf(db,companyId,invoiceId){return Payables.storeDocument(db,{companyId,invoiceId,name:'faktura.pdf',bytes:pdf()})}
function approveCurrent(db,companyId,invoiceId,actorId){const current=Payables.invoiceById(db,companyId,invoiceId);return Payables.approve(db,{companyId,invoiceId,actorId,expectedCodingSha256:current?.codingSha256,expectedDocumentSha256:current?.documentSha256})}

test('konteringsmodulen skapar balanserad leverantörskontering i ören',()=>{const coding=Domain.buildCoding({totalOre:125000,vatOre:25000,costAccount:'4010'});assert.equal(coding.debitOre,125000);assert.equal(coding.creditOre,125000);assert.deepEqual(coding.lines.map(x=>x.account),['4010','2641','2440']);});
test('felaktig kontering stoppas',()=>{assert.throws(()=>Domain.validateCoding({totalOre:125000,lines:[{account:'4010',debitOre:100000,creditOre:0},{account:'2440',debitOre:0,creditOre:125000}]}),e=>e.code==='UNBALANCED_CODING');});
test('attest kräver PDF-underlag',()=>{const {db,company,approver,invoice}=seed();try{const coding=Domain.buildCoding({totalOre:125000,vatOre:25000});Payables.saveCoding(db,{companyId:company.id,invoiceId:invoice.id,lines:coding.lines});assert.throws(()=>approveCurrent(db,company.id,invoice.id,approver.id),e=>e.code==='DOCUMENT_REQUIRED_FOR_APPROVAL');}finally{db.close()}});
test('leverantörsfakturor blockerar aktiva PDF-funktioner och fel filändelse',()=>{const {db,company,invoice}=seed();try{const active=Buffer.from('%PDF-1.4\n1 0 obj << /OpenAction 2 0 R /JavaScript (app.alert(1)) >> endobj\n%%EOF','latin1');assert.throws(()=>Payables.storeDocument(db,{companyId:company.id,invoiceId:invoice.id,name:'faktura.pdf',mime:'application/pdf',bytes:active}),e=>e.code==='ACTIVE_PDF_CONTENT_NOT_ALLOWED'&&e.statusCode===415);assert.throws(()=>Payables.storeDocument(db,{companyId:company.id,invoiceId:invoice.id,name:'faktura.exe',mime:'application/pdf',bytes:pdf()}),e=>e.code==='PDF_EXTENSION_REQUIRED'&&e.statusCode===415);}finally{db.close()}});
test('registrerad användare får inte attestera sin egen faktura',()=>{const {db,company,registrar,invoice}=seed();try{attachPdf(db,company.id,invoice.id);const coding=Domain.buildCoding({totalOre:125000,vatOre:25000});Payables.saveCoding(db,{companyId:company.id,invoiceId:invoice.id,lines:coding.lines});assert.throws(()=>approveCurrent(db,company.id,invoice.id,registrar.id),e=>e.code==='SEPARATION_OF_DUTIES_FAILED');}finally{db.close()}});
test('attest låser konteringen och betalning kräver först bokförd leverantörsskuld',()=>{const {db,company,registrar,approver,accountant,invoice}=seed();try{attachPdf(db,company.id,invoice.id);const coding=Domain.buildCoding({totalOre:125000,vatOre:25000});Payables.saveCoding(db,{companyId:company.id,invoiceId:invoice.id,lines:coding.lines});const approved=approveCurrent(db,company.id,invoice.id,approver.id);assert.equal(approved.status,'approved');assert.equal(approved.approvedBy,approver.id);assert.match(approved.codingSha256,/^[a-f0-9]{64}$/);assert.throws(()=>Payables.saveCoding(db,{companyId:company.id,invoiceId:invoice.id,lines:coding.lines}),e=>e.code==='CODING_LOCKED');assert.throws(()=>Payables.preparePayment(db,{companyId:company.id,invoiceId:invoice.id,paymentDate:'2026-09-16',amountOre:125000,account:'1930',preparedBy:registrar.id}),e=>e.code==='INVOICE_LIABILITY_NOT_POSTED');SupplierAccounting.postSupplierInvoice(db,{companyId:company.id,invoiceId:invoice.id,actorId:accountant.id});const payment=Payables.preparePayment(db,{companyId:company.id,invoiceId:invoice.id,paymentDate:'2026-09-16',amountOre:125000,account:'1930',preparedBy:registrar.id});assert.equal(payment.status,'prepared');assert.equal(payment.amountOre,125000);}finally{db.close()}});

test('attest kräver versionsuppgifter för kontering och PDF',()=>{const {db,company,approver,invoice}=seed();try{attachPdf(db,company.id,invoice.id);const coding=Domain.buildCoding({totalOre:125000,vatOre:25000});Payables.saveCoding(db,{companyId:company.id,invoiceId:invoice.id,lines:coding.lines});assert.throws(()=>Payables.approve(db,{companyId:company.id,invoiceId:invoice.id,actorId:approver.id}),e=>e.code==='APPROVAL_PRECONDITION_REQUIRED'&&e.statusCode===428);}finally{db.close()}});
test('attest stoppas om konteringen ändrats efter granskning',()=>{const {db,company,approver,invoice}=seed();try{attachPdf(db,company.id,invoice.id);Payables.saveCoding(db,{companyId:company.id,invoiceId:invoice.id,lines:Domain.buildCoding({totalOre:125000,vatOre:25000,costAccount:'4010'}).lines});const reviewed=Payables.invoiceById(db,company.id,invoice.id);Payables.saveCoding(db,{companyId:company.id,invoiceId:invoice.id,lines:Domain.buildCoding({totalOre:125000,vatOre:25000,costAccount:'5460'}).lines});assert.throws(()=>Payables.approve(db,{companyId:company.id,invoiceId:invoice.id,actorId:approver.id,expectedCodingSha256:reviewed.codingSha256,expectedDocumentSha256:reviewed.documentSha256}),e=>e.code==='APPROVAL_STALE_CODING'&&e.statusCode===409);assert.equal(Payables.invoiceById(db,company.id,invoice.id).status,'coded');}finally{db.close()}});
test('attest stoppas om PDF-underlaget ändrats efter granskning',()=>{const {db,company,approver,invoice}=seed();try{attachPdf(db,company.id,invoice.id);Payables.saveCoding(db,{companyId:company.id,invoiceId:invoice.id,lines:Domain.buildCoding({totalOre:125000,vatOre:25000}).lines});const reviewed=Payables.invoiceById(db,company.id,invoice.id);Payables.storeDocument(db,{companyId:company.id,invoiceId:invoice.id,name:'ny-version.pdf',bytes:pdf('ny version')});assert.throws(()=>Payables.approve(db,{companyId:company.id,invoiceId:invoice.id,actorId:approver.id,expectedCodingSha256:reviewed.codingSha256,expectedDocumentSha256:reviewed.documentSha256}),e=>e.code==='APPROVAL_STALE_DOCUMENT'&&e.statusCode===409);assert.equal(Payables.invoiceById(db,company.id,invoice.id).status,'coded');}finally{db.close()}});
test('PDF-underlag sparas med kontrollsumma och kan hämtas endast via företag',()=>{const {db,company,invoice}=seed();try{const bytes=pdf();const result=Payables.storeDocument(db,{companyId:company.id,invoiceId:invoice.id,name:'faktura.pdf',bytes});const stored=Payables.document(db,company.id,invoice.id);assert.equal(result.sha256,crypto.createHash('sha256').update(bytes).digest('hex'));assert.deepEqual(Buffer.from(stored.bytes),bytes);assert.throws(()=>Payables.document(db,'fel-foretag',invoice.id),e=>e.code==='DOCUMENT_NOT_FOUND');}finally{db.close()}});
test('ogiltig fil, datum, dubblett och felaktigt standardkonto stoppas vid registrering',()=>{const {db,company,registrar,supplier,invoice}=seed();try{assert.throws(()=>Payables.storeDocument(db,{companyId:company.id,invoiceId:invoice.id,name:'fake.pdf',bytes:Buffer.from('inte pdf')}),e=>e.code==='INVALID_PDF_SIGNATURE'&&e.statusCode===415);assert.throws(()=>Payables.createSupplierInvoice(db,{companyId:company.id,supplierId:supplier.id,supplierInvoiceNumber:'X',invoiceDate:'2026-09-31',dueDate:'2026-10-10',totalOre:10000,vatOre:2000,registeredBy:registrar.id}),e=>e.code==='INVALID_SUPPLIER_INVOICE_DATE');assert.throws(()=>Payables.createSupplierInvoice(db,{companyId:company.id,supplierId:supplier.id,supplierInvoiceNumber:'GG-4401',invoiceDate:'2026-09-10',dueDate:'2026-10-10',totalOre:125000,vatOre:25000,registeredBy:registrar.id}),e=>e.code==='DUPLICATE_SUPPLIER_INVOICE');assert.throws(()=>Payables.createSupplier(db,{companyId:company.id,supplierNumber:'L-200',name:'Fel Konto AB',defaultCostAccount:'40A0'}),e=>e.code==='INVALID_SUPPLIER_ACCOUNT');}finally{db.close()}});
test('fakturanummer jämförs normaliserat för samma leverantör',()=>{const {db,company,registrar,supplier}=seed();try{assert.equal(Payables.normalizeInvoiceNumber(' gg 44-01 '),'GG4401');assert.throws(()=>Payables.createSupplierInvoice(db,{companyId:company.id,supplierId:supplier.id,supplierInvoiceNumber:'gg 44 01',invoiceDate:'2026-09-11',dueDate:'2026-10-11',totalOre:125000,vatOre:25000,registeredBy:registrar.id}),e=>e.code==='DUPLICATE_SUPPLIER_INVOICE'&&Boolean(e.details?.existingInvoiceId));}finally{db.close()}});
test('samma PDF kan inte kopplas till två fakturor i samma företag',()=>{const {db,company,registrar,supplier,invoice}=seed();try{const bytes=pdf('unik faktura');Payables.storeDocument(db,{companyId:company.id,invoiceId:invoice.id,name:'ett.pdf',bytes});const second=Payables.createSupplierInvoice(db,{companyId:company.id,supplierId:supplier.id,supplierInvoiceNumber:'GG-4402',invoiceDate:'2026-09-11',dueDate:'2026-10-11',totalOre:125000,vatOre:25000,registeredBy:registrar.id});assert.throws(()=>Payables.storeDocument(db,{companyId:company.id,invoiceId:second.id,name:'två.pdf',bytes}),e=>e.code==='DUPLICATE_SUPPLIER_DOCUMENT'&&e.statusCode===409&&Boolean(e.details?.existingInvoiceId));Payables.storeDocument(db,{companyId:company.id,invoiceId:second.id,name:'två.pdf',bytes:pdf('annan faktura')});assert.equal(Payables.invoiceById(db,company.id,second.id).hasDocument,true);}finally{db.close()}});
test('dagens utbetalningar summeras per status',()=>{const payments=[{paymentDate:'2026-09-16',amountOre:10000,status:'prepared'},{paymentDate:'2026-09-16',amountOre:20000,status:'released'},{paymentDate:'2026-09-16',amountOre:30000,status:'paid'},{paymentDate:'2026-09-17',amountOre:90000,status:'prepared'}];const summary=Domain.paymentSummary(payments,'2026-09-16');assert.equal(summary.count,3);assert.equal(summary.totalOre,60000);assert.equal(summary.byStatus.prepared,10000);assert.equal(summary.byStatus.released,20000);assert.equal(summary.byStatus.paid,30000);});


test('intern leverantörs-PDF-lagring är företagsskopad och låst efter attest',()=>{const {db,company,approver,invoice}=seed();try{
  const other=Db.createCompany(db,{legalName:'Andra Leverantörsbolaget AB',displayName:'Andra',orgNumber:'559901-2002'});
  const store=SupplierDocumentStore.createSqliteSupplierInvoiceDocumentStore(db),bytes=pdf('storage-seam');
  assert.equal(store.put({companyId:other.id,invoiceId:invoice.id,bytes}),false);
  assert.equal(store.exists({companyId:other.id,invoiceId:invoice.id}),false);
  assert.equal(store.get({companyId:other.id,invoiceId:invoice.id}),null);
  Payables.storeDocument(db,{companyId:company.id,invoiceId:invoice.id,name:'storage.pdf',bytes});
  assert.equal(store.exists({companyId:company.id,invoiceId:invoice.id}),true);
  assert.deepEqual(store.get({companyId:company.id,invoiceId:invoice.id}),bytes);
  Payables.saveCoding(db,{companyId:company.id,invoiceId:invoice.id,lines:Domain.buildCoding({totalOre:125000,vatOre:25000}).lines});
  approveCurrent(db,company.id,invoice.id,approver.id);
  assert.equal(store.put({companyId:company.id,invoiceId:invoice.id,bytes:pdf('replacement')}),false);
  assert.deepEqual(Payables.document(db,company.id,invoice.id).bytes,bytes);
}finally{db.close()}});


test('leverantörsfakturans PDF kan beskrivas med provider-neutral företagsisolerad metadata',()=>{const {db,company,invoice}=seed();try{
  assert.equal(Payables.privateObjectMetadata(db,company.id,invoice.id),null);
  const bytes=pdf('supplier-object-metadata');
  const stored=Payables.storeDocument(db,{companyId:company.id,invoiceId:invoice.id,name:'metadata.pdf',bytes});
  const metadata=Payables.privateObjectMetadata(db,company.id,invoice.id);
  assert.equal(metadata.companyId,company.id);
  assert.equal(metadata.kind,'supplier-invoice');
  assert.equal(metadata.objectId,invoice.id);
  assert.equal(metadata.objectKey,`private/${company.id}/supplier-invoices/${invoice.id}`);
  assert.equal(metadata.mimeType,'application/pdf');
  assert.equal(metadata.sizeBytes,bytes.length);
  assert.equal(metadata.sha256,stored.sha256);

  const other=Db.createCompany(db,{legalName:'Leverantör Metadata B AB',displayName:'Metadata B',orgNumber:'559901-4004'});
  assert.equal(Payables.privateObjectMetadata(db,other.id,invoice.id),null);
}finally{db.close()}});
