'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const Db=require('../apps/api/database.js');
const Auth=require('../apps/api/auth.js');
const Cms=require('../apps/api/website-cms.js');

function seed(){const db=Db.openDatabase(':memory:');const company=Db.createCompany(db,{legalName:'Rolands Frukt o Grönt Aktiebolag',displayName:'Rollands Saluhall',orgNumber:'556406-5059'});const user=Db.createUser(db,{username:'cms.test',displayName:'CMS Test',passwordHash:Auth.hashPassword('CMS testlosenord 2026!')});Cms.initializeWebsiteCms(db);return{db,company,user}}

test('CMS startar med separata utkast och publicerat innehåll',()=>{const {db,company}=seed();try{const state=Cms.state(db,company.id);assert.equal(state.published.version,0);assert.equal(state.draft.company.orgNumber,'556406-5059');assert.match(state.draft.site.hero.title,/Bra råvaror/i);}finally{db.close()}});

test('utkast kan ändra webbdata men inte juridisk identitet',()=>{const {db,company,user}=seed();try{const current=Cms.state(db,company.id);const site=structuredClone(current.draft.site),companyDraft=structuredClone(current.draft.company);site.hero.title='Ny rubrik för webbplatsen';companyDraft.displayName='Rollands Testnamn';companyDraft.contact.email='webb@rollands.se';companyDraft.legalName='Felaktigt namn AB';companyDraft.orgNumber='000000-0000';companyDraft.vatNumber='FEL';const saved=Cms.saveDraft(db,{companyId:company.id,site,company:companyDraft,userId:user.id});assert.equal(saved.draft.site.hero.title,'Ny rubrik för webbplatsen');assert.equal(saved.draft.company.displayName,'Rollands Testnamn');assert.equal(saved.draft.company.contact.email,'webb@rollands.se');assert.equal(saved.draft.company.legalName,'Rolands Frukt o Grönt Aktiebolag');assert.equal(saved.draft.company.orgNumber,'556406-5059');assert.equal(saved.draft.company.vatNumber,'SE556406505901');assert.notEqual(saved.published.site.hero.title,'Ny rubrik för webbplatsen');}finally{db.close()}});

test('publicering skapar versionshistorik och återställning blir endast nytt utkast',()=>{const {db,company,user}=seed();try{let current=Cms.state(db,company.id);let site=structuredClone(current.draft.site),companyDraft=structuredClone(current.draft.company);site.hero.title='Version ett';Cms.saveDraft(db,{companyId:company.id,site,company:companyDraft,userId:user.id});current=Cms.publish(db,{companyId:company.id,userId:user.id});assert.equal(current.published.version,1);assert.equal(current.published.site.hero.title,'Version ett');site=structuredClone(current.draft.site);site.hero.title='Version två';Cms.saveDraft(db,{companyId:company.id,site,company:current.draft.company,userId:user.id});current=Cms.publish(db,{companyId:company.id,userId:user.id});assert.equal(current.published.version,2);assert.equal(Cms.listRevisions(db,company.id).length,2);const restored=Cms.restoreToDraft(db,{companyId:company.id,version:1,userId:user.id});assert.equal(restored.draft.site.hero.title,'Version ett');assert.equal(restored.published.site.hero.title,'Version två');assert.equal(restored.published.version,2);}finally{db.close()}});

test('CMS stoppar osäkra länkar och ogiltiga kontaktuppgifter',()=>{const {db,company,user}=seed();try{const current=Cms.state(db,company.id);const site=structuredClone(current.draft.site),companyDraft=structuredClone(current.draft.company);site.navigation[0].href='javascript:alert(1)';assert.throws(()=>Cms.saveDraft(db,{companyId:company.id,site,company:companyDraft,userId:user.id}),error=>error.code==='INVALID_WEBSITE_LINK');site.navigation[0].href='#hem';companyDraft.contact.email='inte-en-adress';assert.throws(()=>Cms.saveDraft(db,{companyId:company.id,site,company:companyDraft,userId:user.id}),error=>error.code==='INVALID_EMAIL');}finally{db.close()}});

test('CMS-data är isolerad per företag',()=>{const {db,company,user}=seed();try{const other=Db.createCompany(db,{legalName:'Fiktiva Kaféet AB',displayName:'Fiktiva Kaféet',orgNumber:'559999-9001'});let first=Cms.state(db,company.id),second=Cms.state(db,other.id);const site=structuredClone(first.draft.site);site.hero.title='Endast företag ett';Cms.saveDraft(db,{companyId:company.id,site,company:first.draft.company,userId:user.id});second=Cms.state(db,other.id);assert.notEqual(second.draft.site.hero.title,'Endast företag ett');assert.equal(second.draft.company.orgNumber,'559999-9001');}finally{db.close()}});
