const app=document.getElementById('accounting-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
let session=null,tab='journal',from='',to='',entries=[],report=null,message='';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ore(v){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(v||0)/100)}
function today(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
async function api(path){const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',headers:{Accept:'application/json'}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Begäran misslyckades.');return data}
function suffix(){const p=new URLSearchParams();if(from)p.set('from',from);if(to)p.set('to',to);const q=p.toString();return q?`?${q}`:''}
function sidebar(){const d=isDemo?'?demo=1':'';return `<aside class="sidebar accounting-nav"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">${esc(session?.company?.name||'Rollands Frukt o Grönt AB')}<br>${isDemo?'Demoföretag':'Skyddad företagsmiljö'}</div><div class="side-group"><span>Arbetsyta</span><a class="side-link" href="./dashboard.html${d}">Översikt</a></div><div class="side-group"><span>Försäljning</span><a class="side-link" href="./index.html${d}">Kundreskontra</a></div><div class="side-group"><span>Ekonomi</span><a class="side-link" href="./bank.html${d}">Bank & avstämning</a><a class="side-link" href="./payables.html${d}">Leverantörsfakturor</a><a class="side-link" href="./suppliers.html${d}">Leverantörer</a><a class="side-link active" href="./accounting.html${d}">Bokföring & rapporter</a><a class="side-link" href="./automation.html${d}">Automationskö</a></div><div class="sidebar-footer">Alla rapportbelopp visas i exakt bokförda ören.</div></aside>`}
const demoEntries=[
{id:'e1',number:'A31',postingDate:'2026-09-01',description:'Kundfaktura 310031',sourceType:'customer-invoice',lines:[{account:'1510',text:'Kundfordran',debitOre:125000,creditOre:0},{account:'3010',text:'Försäljning',debitOre:0,creditOre:100000},{account:'2611',text:'Utgående moms',debitOre:0,creditOre:25000}]},
{id:'e2',number:'A32',postingDate:'2026-09-10',description:'Leverantörsfaktura GG-4401',sourceType:'supplier-invoice',lines:[{account:'4010',text:'Varuinköp',debitOre:100000,creditOre:0},{account:'2641',text:'Ingående moms',debitOre:25000,creditOre:0},{account:'2440',text:'Leverantörsskuld',debitOre:0,creditOre:125000}]},
{id:'e3',number:'A33',postingDate:'2026-09-16',description:'Betalning leverantörsfaktura GG-4401',sourceType:'supplier-payment',lines:[{account:'2440',text:'Betald GG-4401',debitOre:125000,creditOre:0},{account:'1930',text:'Bank',debitOre:0,creditOre:125000}]}
];
function demoOverview(){const rows=demoEntries.flatMap(e=>e.lines.map(l=>({...l,entryId:e.id,postingDate:e.postingDate}))).filter(r=>(!from||r.postingDate>=from)&&(!to||r.postingDate<=to));const map=new Map();for(const r of rows){const x=map.get(r.account)||{account:r.account,debitOre:0,creditOre:0,balanceOre:0};x.debitOre+=r.debitOre;x.creditOre+=r.creditOre;x.balanceOre=x.debitOre-x.creditOre;map.set(r.account,x)}const trial=[...map.values()].sort((a,b)=>a.account.localeCompare(b.account));const incomeAccounts=trial.filter(a=>Number(a.account)>=3000&&Number(a.account)<=8999).map(a=>({...a,class:Number(a.account)<4000?'revenue':'cost',reportAmountOre:Number(a.account)<4000?a.creditOre-a.debitOre:a.debitOre-a.creditOre}));const revenueOre=incomeAccounts.filter(a=>a.class==='revenue').reduce((s,a)=>s+a.reportAmountOre,0),costOre=incomeAccounts.filter(a=>a.class==='cost').reduce((s,a)=>s+a.reportAmountOre,0);const balanceAccounts=trial.filter(a=>Number(a.account)>=1000&&Number(a.account)<=2999).map(a=>({...a,class:Number(a.account)<2000?'asset':'equity-liability',reportAmountOre:Number(a.account)<2000?a.debitOre-a.creditOre:a.creditOre-a.debitOre}));const assetsOre=balanceAccounts.filter(a=>a.class==='asset').reduce((s,a)=>s+a.reportAmountOre,0),equityLiabilitiesOre=balanceAccounts.filter(a=>a.class==='equity-liability').reduce((s,a)=>s+a.reportAmountOre,0);const vatAccounts=trial.filter(a=>/^26[1-5]/.test(a.account));const outputVatOre=vatAccounts.filter(a=>Number(a.account)>=2610&&Number(a.account)<=2639).reduce((s,a)=>s+a.creditOre-a.debitOre,0),inputVatOre=vatAccounts.filter(a=>Number(a.account)>=2640&&Number(a.account)<=2649).reduce((s,a)=>s+a.debitOre-a.creditOre,0);return{entryCount:new Set(rows.map(r=>r.entryId)).size,lineCount:rows.length,trialBalance:trial,incomeStatement:{accounts:incomeAccounts,revenueOre,costOre,resultOre:revenueOre-costOre},balanceSheet:{accounts:balanceAccounts,assetsOre,equityLiabilitiesOre,differenceOre:assetsOre-equityLiabilitiesOre},vatSummary:{accounts:vatAccounts,outputVatOre,inputVatOre,settlementOre:0,netVatPayableOre:outputVatOre-inputVatOre}}}
function filterEntries(source){return source.filter(e=>(!from||e.postingDate>=from)&&(!to||e.postingDate<=to))}
function toolbar(){return `<section class="report-toolbar"><div class="tabs">${[['journal','Verifikationer'],['trial','Saldobalans'],['income','Resultat'],['balance','Balans'],['vat','Momsöversikt']].map(([id,label])=>`<button class="tab ${tab===id?'active':''}" data-tab="${id}">${label}</button>`).join('')}</div><form id="report-filter"><label>Från<input type="date" name="from" value="${esc(from)}"></label><label>Till<input type="date" name="to" value="${esc(to)}"></label><button class="button small" type="submit">Visa</button><button class="button ghost small" type="button" data-action="clear-range">Rensa</button></form></section>`}
function journalView(){const list=filterEntries(entries);return `<section class="report-panel"><div class="panel-head"><div><span class="eyebrow">Huvudbok</span><h2>Verifikationer</h2></div><strong>${list.length} poster</strong></div>${list.map(e=>`<article class="entry"><div class="entry-head"><div><b>${esc(e.number)}</b><span>${esc(e.postingDate)} · ${esc(e.description)}</span></div><small>${esc(e.sourceType)}</small></div><table><thead><tr><th>Konto</th><th>Text</th><th>Debet</th><th>Kredit</th></tr></thead><tbody>${(e.lines||[]).map(l=>`<tr><td>${esc(l.account)}</td><td>${esc(l.text||'')}</td><td class="money">${l.debitOre?ore(l.debitOre):'—'}</td><td class="money">${l.creditOre?ore(l.creditOre):'—'}</td></tr>`).join('')}</tbody></table></article>`).join('')||'<p class="empty pad">Inga verifikationer i valt intervall.</p>'}</section>`}
function trialView(){const rows=report?.trialBalance||[];return `<section class="report-panel"><div class="panel-head"><div><span class="eyebrow">Rapport</span><h2>Saldobalans</h2></div><strong>${rows.length} konton</strong></div><table class="report-table"><thead><tr><th>Konto</th><th>Debet</th><th>Kredit</th><th>Saldo D−K</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.account)}</td><td class="money">${ore(r.debitOre)}</td><td class="money">${ore(r.creditOre)}</td><td class="money">${ore(r.balanceOre)}</td></tr>`).join('')}</tbody></table></section>`}
function incomeView(){const r=report?.incomeStatement||{accounts:[],revenueOre:0,costOre:0,resultOre:0};return `<section class="report-panel"><div class="summary-cards"><article><span>Intäkter</span><strong>${ore(r.revenueOre)}</strong></article><article><span>Kostnader</span><strong>${ore(r.costOre)}</strong></article><article><span>Periodresultat</span><strong>${ore(r.resultOre)}</strong></article></div><table class="report-table"><thead><tr><th>Konto</th><th>Typ</th><th>Belopp</th></tr></thead><tbody>${r.accounts.map(a=>`<tr><td>${esc(a.account)}</td><td>${a.class==='revenue'?'Intäkt':'Kostnad'}</td><td class="money">${ore(a.reportAmountOre)}</td></tr>`).join('')}</tbody></table></section>`}
function balanceView(){const r=report?.balanceSheet||{accounts:[],assetsOre:0,equityLiabilitiesOre:0,differenceOre:0};return `<section class="report-panel"><div class="summary-cards"><article><span>Tillgångar</span><strong>${ore(r.assetsOre)}</strong></article><article><span>Eget kapital & skulder</span><strong>${ore(r.equityLiabilitiesOre)}</strong></article><article><span>Skillnad / aktuellt resultat</span><strong>${ore(r.differenceOre)}</strong></article></div><div class="notice">Detta är en kontobaserad balansöversikt. Slutlig rapportpresentation och årsredovisningsmappning byggs separat.</div><table class="report-table"><thead><tr><th>Konto</th><th>Klass</th><th>Belopp</th></tr></thead><tbody>${r.accounts.map(a=>`<tr><td>${esc(a.account)}</td><td>${a.class==='asset'?'Tillgång':'Eget kapital/skuld'}</td><td class="money">${ore(a.reportAmountOre)}</td></tr>`).join('')}</tbody></table></section>`}
function vatView(){const r=report?.vatSummary||{accounts:[],outputVatOre:0,inputVatOre:0,netVatPayableOre:0};return `<section class="report-panel"><div class="summary-cards"><article><span>Utgående moms</span><strong>${ore(r.outputVatOre)}</strong></article><article><span>Ingående moms</span><strong>${ore(r.inputVatOre)}</strong></article><article><span>Kontobaserat netto</span><strong>${ore(r.netVatPayableOre)}</strong></article></div><div class="notice warning"><b>Inte en momsdeklaration.</b> Detta är en kontrollöversikt av bokförda momskonton. Deklarationsrutor och slutlig skattemappning ska konfigureras och verifieras innan skarp drift.</div><table class="report-table"><thead><tr><th>Konto</th><th>Debet</th><th>Kredit</th></tr></thead><tbody>${r.accounts.map(a=>`<tr><td>${esc(a.account)}</td><td class="money">${ore(a.debitOre)}</td><td class="money">${ore(a.creditOre)}</td></tr>`).join('')}</tbody></table></section>`}
function view(){if(tab==='journal')return journalView();if(tab==='trial')return trialView();if(tab==='income')return incomeView();if(tab==='balance')return balanceView();return vatView()}
function render(){app.innerHTML=`<div class="accounting-shell">${sidebar()}<section class="accounting-main"><header class="topbar"><div><h1>Bokföring & rapporter</h1><p>Verifikationer · saldobalans · resultat · balans · moms</p></div><div class="user-chip"><b>${esc(session?.user?.displayName||'Demoanvändare')}</b></div></header><main class="content">${isDemo?'<div class="demo-banner"><b>GitHub Pages-demo.</b> Rapporten bygger på fiktiva verifikationer.</div>':''}${message?`<div class="notice">${esc(message)}</div>`:''}<div class="page-heading"><div><span class="eyebrow">Ekonomisk kontroll</span><h2>Från bokförd händelse till granskningsbar rapport</h2><p>Rapporterna läser samma persistenta verifikationslager som betalningsbokföringen använder i backend.</p></div></div>${toolbar()}${view()}</main></section></div>`}
async function reload(){if(isDemo){entries=structuredClone(demoEntries);report=demoOverview();render();return}const q=suffix();entries=(await api(`/accounting/entries${q}`)).entries||[];report=(await api(`/accounting/reports/overview${q}`)).report;render()}
async function load(){if(isDemo){session={user:{displayName:'Demoekonom'},company:{name:'Rollands Frukt o Grönt AB'}};return reload()}const s=await api('/session');if(!s.authenticated){location.href='./index.html';return}session=s;await reload()}
document.addEventListener('click',async e=>{const t=e.target.closest('[data-tab]');if(t){tab=t.dataset.tab;render();return}if(e.target.closest('[data-action="clear-range"]')){from='';to='';await reload()}});
document.addEventListener('submit',async e=>{if(e.target.id!=='report-filter')return;e.preventDefault();const fd=new FormData(e.target);from=String(fd.get('from')||'');to=String(fd.get('to')||'');try{await reload()}catch(error){message=error.message;render()}});
load().catch(error=>{app.innerHTML=`<main class="boot"><strong>Bokföringen kunde inte laddas</strong><span>${esc(error.message)}</span></main>`});
