const app=document.getElementById('accounting-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const csrfToken=sessionStorage.getItem('rollands-csrf')||'';
const Demo=globalThis.RollandsDemoScenario;
let session=null,entries=[],periods=[],unlockRequests=[],selectedEntry=null;
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ore(v){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(v||0)/100)}
function today(){return isDemo&&Demo?Demo.AS_OF_DATE:new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function currentPeriod(){return today().slice(0,7)}
function url(path){return `${path}${isDemo?'?demo=1':''}`}
async function api(path,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.method&&options.method!=='GET'&&csrfToken?{'X-CSRF-Token':csrfToken}:{})};const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',...options,headers,body:options.body?JSON.stringify(options.body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(data.error||'Begäran misslyckades.');e.code=data.code;throw e}return data}
function sidebar(){return `<aside class="sidebar"><div class="logo"><strong>${esc(isDemo?'Rollands':session?.company?.name||'Företaget')}</strong><small>LT STUDIO</small></div><div class="company-pill">${esc(session?.company?.name||(isDemo?'Rollands Frukt o Grönt AB':'Företaget'))}<br>${isDemo?'Demoföretag':'Skyddad företagsmiljö'}</div><div class="side-group"><span>Arbetsyta</span><a class="side-link" href="${url('./dashboard.html')}">Översikt</a></div><div class="side-group"><span>Ekonomi</span><a class="side-link" href="${url('./payables.html')}">Leverantörsfakturor</a><a class="side-link active" href="${url('./accounting.html')}">Bokföring</a><a class="side-link" href="${url('./reports.html')}">Rapporter</a><a class="side-link" href="${url('./documents.html')}">Dokument</a></div><div class="sidebar-footer">${isDemo?'Gemensamt UAT-scenario · ingen skarp bokföring':'Personlig session · servervaliderad behörighet'}</div></aside>`}
function statusLabel(status){return status==='locked'?'Låst':status==='pending'?'Väntar beslut':status==='approved'?'Godkänd':status==='rejected'?'Avslagen':'Öppen'}
function entryTotal(entry){return (entry.lines||[]).reduce((sum,line)=>sum+Number(line.debitOre||0),0)}
function syncDemo(selectedId){const state=Demo.state();entries=structuredClone(state.accountingEntries);periods=structuredClone(state.accountingPeriods);unlockRequests=structuredClone(state.accountingUnlockRequests);selectedEntry=entries.find(e=>e.id===(selectedId||selectedEntry?.id))||entries[0]||null}
function render(){const current=periods.find(p=>p.period===currentPeriod())||{period:currentPeriod(),status:'open'};app.innerHTML=`<div class="accounting-shell">${sidebar()}<section class="accounting-main"><header class="topbar"><div><h1>Bokföring & perioder</h1><p>Verifikationer bevaras. Rättelser sker med nya spårbara poster.</p></div><div class="user-chip"><b>${esc(session?.user?.displayName||'Demoanvändare')}</b></div></header><main class="accounting-content">${isDemo?'<div class="demo-banner"><b>Gemensamt UAT-scenario.</b> Här visas även verifikationer som skapas av andra demoflöden, till exempel bekräftade leverantörsbetalningar.</div>':''}<section class="accounting-grid"><article class="panel"><span class="eyebrow">Verifikationer</span><h2>Bokförda poster</h2><p>Klicka på en rad för att se exakt konto, debet och kredit.</p>${entryTable()}${entryDetail()}</article><article class="panel"><span class="eyebrow">Periodkontroll</span><h2>${esc(current.period)} · <span class="status-pill ${current.status==='locked'?'locked':''}">${statusLabel(current.status)}</span></h2><p>En låst period kan inte ta emot nya verifikationer. Upplåsning kräver separat beslut.</p>${periodControls(current)}${periodList()}${unlockList()}</article></section></main></section></div>`;bind()}
function entryTable(){return `<div style="overflow:auto"><table class="accounting-table"><thead><tr><th>Nr</th><th>Datum</th><th>Text</th><th>Källa</th><th class="money">Belopp</th></tr></thead><tbody>${entries.map(e=>`<tr data-entry="${esc(e.id)}"><td><b>${esc(e.number)}</b></td><td>${esc(e.postingDate)}</td><td>${esc(e.description)}</td><td>${esc(e.sourceType)}</td><td class="money">${ore(entryTotal(e))}</td></tr>`).join('')||'<tr><td colspan="5" class="empty-state">Inga verifikationer ännu.</td></tr>'}</tbody></table></div>`}
function entryDetail(){if(!selectedEntry)return'';return `<div class="entry-detail"><div class="section-head"><div><span class="eyebrow">${esc(selectedEntry.number)}</span><h2>${esc(selectedEntry.description)}</h2></div></div><div class="entry-lines">${(selectedEntry.lines||[]).map(line=>`<div class="entry-line"><b>${esc(line.account)}</b><span>${esc(line.text||'')}</span><span class="money">Debet ${line.debitOre?ore(line.debitOre):'—'}</span><span class="money">Kredit ${line.creditOre?ore(line.creditOre):'—'}</span></div>`).join('')}</div><div class="notice-box">Originalverifikationen ändras aldrig. En rättelse skapar en ny motverifikation med omvänd debet/kredit.</div><form class="accounting-form" id="correction-form"><label>Rättelsedatum<input name="postingDate" type="date" value="${today()}" required></label><label>Orsak<textarea name="reason" minlength="5" maxlength="500" required></textarea></label><button class="button" type="submit">Skapa motverifikation</button><p class="form-error"></p></form></div>`}
function periodControls(current){if(current.status==='locked')return `<form class="accounting-form" id="unlock-form"><label>Orsak till upplåsning<textarea name="reason" minlength="5" maxlength="500" required></textarea></label><button class="button" type="submit">Begär upplåsning</button><p class="form-error"></p></form>`;return `<div class="toolbar"><button class="button" data-action="lock-current" type="button">Lås ${esc(current.period)}</button></div>`}
function periodList(){return `<div class="period-list">${periods.map(p=>`<div class="period-row"><div><b>${esc(p.period)}</b><br><small>${p.lockedAt?`Låst ${esc(String(p.lockedAt).slice(0,10))}`:'Öppen för bokföring'}</small></div><span class="status-pill ${p.status==='locked'?'locked':''}">${statusLabel(p.status)}</span><span></span></div>`).join('')}</div>`}
function unlockList(){const pending=unlockRequests.filter(r=>r.status==='pending');return `<div class="entry-detail"><span class="eyebrow">Upplåsningskö</span><h2>Väntande beslut</h2>${pending.map(r=>`<div class="period-row"><div><b>${esc(r.period)}</b><br><small>${esc(r.reason)}</small></div><span class="status-pill pending">Väntar beslut</span>${isDemo?`<button class="button ghost small" type="button" data-action="approve-unlock" data-id="${esc(r.id)}">Godkänn demo</button>`:'<span></span>'}</div>`).join('')||'<p class="empty-state">Ingen väntande begäran.</p>'}</div>`}
async function loadApi(){const s=await api('/session');if(!s.authenticated){location.href='./index.html';return false}session=s;const entryData=await api('/accounting/entries');entries=entryData.entries||[];const detailed=[];for(const entry of entries.slice(0,200)){try{detailed.push((await api(`/accounting/entries/${encodeURIComponent(entry.id)}`)).entry)}catch{detailed.push(entry)}}entries=detailed;selectedEntry=entries[0]||null;periods=(await api('/accounting/periods')).periods||[];unlockRequests=(await api('/accounting/unlock-requests?status=all')).requests||[];return true}
function setError(form,message){const el=form.querySelector('.form-error');if(el)el.textContent=message||''}
function bind(){document.querySelectorAll('[data-entry]').forEach(row=>row.addEventListener('click',()=>{selectedEntry=entries.find(e=>e.id===row.dataset.entry)||null;render()}));document.querySelector('[data-action="lock-current"]')?.addEventListener('click',async()=>{const period=currentPeriod();try{if(isDemo){Demo.patch(state=>{const existing=state.accountingPeriods.find(p=>p.period===period);if(existing){existing.status='locked';existing.lockedAt=new Date().toISOString();existing.lockedBy='demo-user'}else state.accountingPeriods.push({period,status:'locked',lockedBy:'demo-user',lockedAt:new Date().toISOString()})});syncDemo();return render()}await api(`/accounting/periods/${period}/lock`,{method:'POST'});await loadApi();render()}catch(e){alert(e.message)}});document.getElementById('unlock-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,reason=String(new FormData(form).get('reason')||'');try{if(isDemo){Demo.patch(state=>state.accountingUnlockRequests.push({id:`u-${Date.now()}`,period:currentPeriod(),reason,status:'pending',requestedBy:'demo-user',requestedAt:new Date().toISOString()}));syncDemo();return render()}await api(`/accounting/periods/${currentPeriod()}/unlock-request`,{method:'POST',body:{reason}});await loadApi();render()}catch(e){setError(form,e.message)}});document.getElementById('correction-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),original=selectedEntry;try{if(isDemo){const reversal={id:`demo-c-${Date.now()}`,number:`${original.number}R`,postingDate:String(data.get('postingDate')),description:`Motverifikation ${original.number} – ${String(data.get('reason'))}`,sourceType:'accounting-correction-reversal',sourceId:original.id,lines:original.lines.map(l=>({...l,debitOre:l.creditOre,creditOre:l.debitOre}))};Demo.patch(state=>state.accountingEntries.unshift(reversal));syncDemo(reversal.id);return render()}await api(`/accounting/entries/${encodeURIComponent(original.id)}/correct`,{method:'POST',body:{postingDate:data.get('postingDate'),reason:data.get('reason')}});await loadApi();render()}catch(e){setError(form,e.message)}});document.querySelectorAll('[data-action="approve-unlock"]').forEach(button=>button.addEventListener('click',()=>{if(!isDemo)return;Demo.patch(state=>{const request=state.accountingUnlockRequests.find(r=>r.id===button.dataset.id);if(request){request.status='approved';const period=state.accountingPeriods.find(p=>p.period===request.period);if(period){period.status='open';period.lockedAt=null;period.lockedBy=null}}});syncDemo();render()}))}
async function init(){if(isDemo){if(!Demo)throw new Error('Det gemensamma demoscenariot kunde inte laddas.');session={user:{displayName:'Demoanvändare'},company:{name:'Rollands Frukt o Grönt AB'}};syncDemo();return render()}if(await loadApi())render()}
init().catch(error=>{app.innerHTML=`<main class="boot"><strong>Bokföringen kunde inte laddas</strong><span>${esc(error.message)}</span></main>`});
