const app=document.getElementById('portal-app');
const R=window.RollandsReceivables;
const isPagesDemo=location.hostname.endsWith('github.io') || new URLSearchParams(location.search).has('demo');
const COLUMN_KEY='rollands-portal-receivable-columns-v1';
const COMMENT_KEY='rollands-portal-demo-comments-v1';
const REMINDER_KEY='rollands-portal-demo-reminders-v1';
let mode=isPagesDemo?'demo':'api';
let session=null;
let csrfToken=sessionStorage.getItem('rollands-csrf') || '';
let legalRates=null;
let invoices=[];
let loginCompanies=[];
let contextMenu=null;
let modal=null;
let visibleColumns=new Set(loadJson(COLUMN_KEY,R.RECEIVABLE_COLUMNS.filter(c=>c.defaultVisible).map(c=>c.id)));

const demoInvoices=[
  {id:'demo-i1',kind:'customer',customerNumber:'K-1001',customerName:'Västra Hamnen Logistik AB',invoiceNumber:'310001',ocr:'310001',invoiceDate:'2026-08-18',postingDate:'2026-08-18',dueDate:'2026-09-17',totalOre:420000,remainingOre:420000,vatOre:45000,status:'Förfallen',paymentMethod:'Bankgiro',paymentAccount:'BG 123-4567',invoiceAccount:'1510',batchNumber:'1028',journalNumber:'A28',customerType:'business',reminderFeeAgreed:true,commentCount:1,transactions:[],reminders:[{id:'demo-r1',sentAt:'2026-09-19T09:00:00.000Z',kind:'payment-reminder'}]},
  {id:'demo-i2',kind:'customer',customerNumber:'K-1002',customerName:'Nordic Office Göteborg AB',invoiceNumber:'310002',ocr:'310002',invoiceDate:'2026-08-22',postingDate:'2026-08-22',dueDate:'2026-09-21',totalOre:785000,remainingOre:392500,vatOre:157000,status:'Delbetald',paymentMethod:'Bankgiro',paymentAccount:'BG 123-4567',invoiceAccount:'1510',batchNumber:'1029',journalNumber:'A29',customerType:'business',reminderFeeAgreed:true,commentCount:0,reminders:[],transactions:[{id:'demo-t1',transactionType:'payment',paymentMethod:'Bankgiro',paymentDate:'2026-09-10',postingDate:'2026-09-10',batchNumber:'1041',journalNumber:'A41',amountOre:-392500,approved:true,account:'1930'}]},
  {id:'demo-i3',kind:'customer',customerNumber:'K-1003',customerName:'Havsbris Konferens AB',invoiceNumber:'310003',ocr:'310003',invoiceDate:'2026-09-02',postingDate:'2026-09-02',dueDate:'2026-10-02',totalOre:1260000,remainingOre:1260000,vatOre:135000,status:'Bokförd',paymentMethod:'Bankgiro',paymentAccount:'BG 123-4567',invoiceAccount:'1510',batchNumber:'1030',journalNumber:'A30',customerType:'business',reminderFeeAgreed:false,commentCount:0,transactions:[],reminders:[]},
  {id:'demo-i4',kind:'customer',customerNumber:'K-1004',customerName:'Majorna Fastigheter AB',invoiceNumber:'310004',ocr:'310004',invoiceDate:'2026-09-05',postingDate:'2026-09-05',dueDate:'2026-10-05',totalOre:235000,remainingOre:0,vatOre:47000,status:'Betald',paymentMethod:'Bankgiro',paymentAccount:'BG 123-4567',invoiceAccount:'1510',batchNumber:'1031',journalNumber:'A31',customerType:'business',reminderFeeAgreed:true,commentCount:0,reminders:[],transactions:[{id:'demo-t2',transactionType:'payment',paymentMethod:'Bankgiro',paymentDate:'2026-09-12',postingDate:'2026-09-12',batchNumber:'1042',journalNumber:'A42',amountOre:-235000,approved:true,account:'1930'}]}
];

function loadJson(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return value ?? fallback}catch{return fallback}}
function saveJson(key,value){localStorage.setItem(key,JSON.stringify(value))}
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function ore(value){if(value==null||value==='')return '—';return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value)/100)}
function shortDate(value){return value?String(value).slice(0,10):'—'}
function initials(name){return String(name||'Demo').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function today(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function dueClass(invoice){return invoice.remainingOre>0 && invoice.dueDate<today()?'overdue':''}
function apiUrl(path){return `/api/v1${path}`}

async function api(path,options={}){
  const headers={'Accept':'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};
  if(options.method && options.method!=='GET' && csrfToken)headers['X-CSRF-Token']=csrfToken;
  const response=await fetch(apiUrl(path),{credentials:'same-origin',...options,headers,body:options.body?JSON.stringify(options.body):undefined});
  const data=await response.json().catch(()=>({}));
  if(!response.ok){const error=new Error(data.error||'Begäran misslyckades.');error.status=response.status;error.code=data.code;error.data=data;throw error}
  return data;
}

function demoComments(invoiceId){const all=loadJson(COMMENT_KEY,{});return all[invoiceId]||[]}
function setDemoComments(invoiceId,comments){const all=loadJson(COMMENT_KEY,{});all[invoiceId]=comments;saveJson(COMMENT_KEY,all)}
function demoReminders(invoiceId){const all=loadJson(REMINDER_KEY,{});return all[invoiceId]||[]}
function setDemoReminders(invoiceId,reminders){const all=loadJson(REMINDER_KEY,{});all[invoiceId]=reminders;saveJson(REMINDER_KEY,all)}
function invoiceById(id){return invoices.find(invoice=>invoice.id===id)}
function withDemoState(invoice){if(mode!=='demo')return invoice;const comments=demoComments(invoice.id);const savedReminders=demoReminders(invoice.id);return {...invoice,commentCount:Math.max(invoice.commentCount||0,comments.length),reminders:[...(invoice.reminders||[]),...savedReminders]}}

function loginView(error=''){
  const companyField=loginCompanies.length?`<label class="field">Företag<select name="companyId" required><option value="">Välj företag</option>${loginCompanies.map(c=>`<option value="${escapeHtml(c.id)}">${escapeHtml(c.name)}</option>`).join('')}</select></label>`:'';
  app.innerHTML=`<div class="login-shell"><section class="login-brand"><span class="eyebrow">Rollands Plattform</span><h1>Ett arbetsflöde.<br>Hela företaget.</h1><p>Den privata portalen kräver ett personligt konto. Roller och företagstillhörighet kontrolleras på servern vid varje skyddad åtgärd.</p></section><section class="login-panel"><form class="login-card" id="login-form"><span class="eyebrow">Privat företagsportal</span><h2>Logga in</h2><p>Administrationsdelen är skild från den publika hemsidan.</p><label class="field">Användarnamn<input name="username" autocomplete="username" required></label><label class="field">Lösenord<input name="password" type="password" autocomplete="current-password" required></label><label class="field">MFA-kod <span style="font-weight:400;color:#69766f">(om rollen kräver det)</span><input name="totp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}"></label>${companyField}<p class="form-error">${escapeHtml(error)}</p><button class="button" type="submit">Logga in säkert</button></form></section></div>`;
}

function sidebar(){return `<aside class="sidebar"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">${escapeHtml(session?.company?.name||'Rollands Frukt o Grönt AB')}<br>${mode==='demo'?'Demoföretag':'Skyddad företagsmiljö'}</div><div class="side-group"><span>Arbetsyta</span><button class="side-link disabled">Översikt</button></div><div class="side-group"><span>Försäljning</span><button class="side-link active">Kundreskontra</button><button class="side-link disabled">Kundfakturor</button><button class="side-link disabled">Kunder</button></div><div class="side-group"><span>Ekonomi</span><button class="side-link disabled">Bank & avstämning</button><button class="side-link disabled">Bokföring</button><button class="side-link disabled">Rapporter</button></div><div class="sidebar-footer">${mode==='demo'?'Öppen GitHub Pages-demo. Inga riktiga företagsuppgifter får användas här.':'Servervaliderad session · default deny'}</div></aside>`}

function metrics(){const list=invoices.map(withDemoState);const open=list.filter(i=>i.remainingOre>0);const overdue=open.filter(i=>i.dueDate<today());const comments=list.reduce((sum,i)=>sum+(i.commentCount||0),0);return `<section class="metrics"><article class="metric"><span>Öppet saldo</span><strong>${ore(open.reduce((n,i)=>n+i.remainingOre,0))}</strong></article><article class="metric"><span>Förfallet</span><strong>${ore(overdue.reduce((n,i)=>n+i.remainingOre,0))}</strong></article><article class="metric"><span>Öppna fakturor</span><strong>${open.length}</strong></article><article class="metric"><span>Interna kommentarer</span><strong>${comments}</strong></article></section>`}

function columnPicker(){return `<details class="column-picker"><summary>☷ Välj kolumner</summary><div class="column-menu">${R.RECEIVABLE_COLUMNS.map(column=>`<label><input type="checkbox" data-column="${escapeHtml(column.id)}" ${visibleColumns.has(column.id)?'checked':''}>${escapeHtml(column.label)}</label>`).join('')}<button class="button ghost small" data-action="reset-columns" type="button">Återställ alla</button></div></details>`}

function cell(column,row){let value=row[column.id];if(column.money)return `<td class="money">${ore(value)}</td>`;if(column.id==='dueDate')return `<td class="${row.remainingOre>0&&value<today()?'overdue':''}">${escapeHtml(shortDate(value))}</td>`;return `<td>${escapeHtml(value==null||value===''?'—':value)}</td>`}
function mappedTransaction(transaction){return {...transaction,type:transaction.transactionType==='payment'?'payment':transaction.transactionType,method:transaction.paymentMethod,date:transaction.paymentDate,postingDate:transaction.postingDate,batch:transaction.batchNumber,transactionNumber:transaction.journalNumber,bookingType:transaction.transactionType==='payment'?'Inbetalning':transaction.transactionType,amountOre:transaction.amountOre}}

function table(){const columns=R.RECEIVABLE_COLUMNS.filter(column=>visibleColumns.has(column.id));const head=columns.map(c=>`<th>${escapeHtml(c.label)}</th>`).join('');const bodies=invoices.map(raw=>{const invoice=withDemoState(raw);const base=R.receivableRow(invoice);const comments=invoice.commentCount||0;const invoiceRow=`<tr class="invoice-row" data-invoice-id="${escapeHtml(invoice.id)}"><td class="customer-cell"><b>${escapeHtml(invoice.customerNumber||'—')}</b><br>${escapeHtml(invoice.customerName||'Okänd kund')}${comments?`<span class="comment-badge">💬 ${comments}</span>`:''}</td>${columns.map(c=>cell(c,base)).join('')}</tr>`;const txRows=(invoice.transactions||[]).map(tx=>{const row=R.receivableRow(invoice,mappedTransaction(tx));return `<tr class="transaction-row"><td class="customer-cell"><span>↳ transaktion</span></td>${columns.map(c=>cell(c,row)).join('')}</tr>`}).join('');return invoiceRow+txRows}).join('');return `<div class="table-scroll"><table class="res-table"><thead><tr><th class="customer-cell">Kund</th>${head}</tr></thead><tbody>${bodies||`<tr><td colspan="${columns.length+1}" class="empty">Inga kundfakturor.</td></tr>`}</tbody></table></div>`}

function contextHtml(){if(!contextMenu)return '';return `<div class="context-menu" style="left:${contextMenu.x}px;top:${contextMenu.y}px"><button data-action="comment" data-id="${escapeHtml(contextMenu.invoiceId)}">💬 Skriv fakturakommentar</button><button data-action="reminder" data-id="${escapeHtml(contextMenu.invoiceId)}">↗ Skapa betalningspåminnelse</button><button data-action="close-context">Avbryt</button></div>`}

function commentsModal(){const invoice=invoiceById(modal.invoiceId);const list=modal.comments||[];return `<div class="modal-backdrop" data-action="close-modal"><section class="modal" data-stop><header class="modal-head"><div><span class="eyebrow">${escapeHtml(invoice?.invoiceNumber||'Faktura')}</span><h3>Fakturakommentar</h3></div><button data-action="close-modal" aria-label="Stäng">×</button></header><div class="modal-body"><div class="notice">Kommentarer är interna. I skarp drift visas de endast för behöriga användare i samma företag och sparas med namn och tid.</div><div class="comments">${list.map(c=>`<article class="comment"><p>${escapeHtml(c.text)}</p><small>${escapeHtml(c.authorName)} · ${escapeHtml(new Date(c.createdAt).toLocaleString('sv-SE'))}</small></article>`).join('')||'<p class="empty">Ingen kommentar ännu.</p>'}</div><form data-form="comment"><label class="field">Ny kommentar<textarea name="text" maxlength="2000" rows="4" required placeholder="Skriv vad andra behöriga användare behöver känna till…"></textarea></label><p class="form-error"></p><div class="modal-actions"><button type="button" class="button ghost" data-action="close-modal">Avbryt</button><button class="button" type="submit">Spara kommentar</button></div></form></div></section></div>`}

function reminderBreakdown(preview){if(!preview)return '<p class="notice warning">Välj datum och inställningar och klicka på Beräkna innan påminnelsen registreras.</p>';return `<div class="reminder-summary"><span>Utestående kapital</span><strong>${ore(preview.principalOre)}</strong><span>Dröjsmålsränta</span><strong>${ore(preview.interestOre)}</strong><span>Påminnelseavgift</span><strong>${ore(preview.reminderFeeOre)}</strong><span>Förseningsersättning</span><strong>${ore(preview.businessLatePaymentCompensationOre)}</strong><span>Totalt enligt underlaget</span><strong>${ore(preview.totalDueOre)}</strong><span>Årsränta vid påminnelsedatum</span><strong>${(preview.statutoryRateOnSentDateBasisPoints/100).toFixed(2).replace('.',',')} %</strong></div>`}
function reminderModal(){const invoice=invoiceById(modal.invoiceId);const canFee=Boolean(invoice?.reminderFeeAgreed);return `<div class="modal-backdrop" data-action="close-modal"><section class="modal" data-stop><header class="modal-head"><div><span class="eyebrow">${escapeHtml(invoice?.invoiceNumber||'Faktura')}</span><h3>Betalningspåminnelse</h3></div><button data-action="close-modal">×</button></header><div class="modal-body"><div class="notice">Räntan beräknas med den konfigurerade referensräntan + 8 procentenheter. Påminnelseavgift kan bara väljas när avgiften är dokumenterat avtalad.</div><form data-form="reminder"><label class="field">Påminnelsedatum<input name="sentDate" type="date" value="${escapeHtml(modal.sentDate||today())}" required></label><label class="field"><span><input name="includeInterest" type="checkbox" checked> Beräkna dröjsmålsränta</span></label><label class="field"><span><input name="includeReminderFee" type="checkbox" ${canFee?'':'disabled'}> Lägg till påminnelseavgift 60 kr ${canFee?'':'(inte avtalad för denna kund)'}</span></label><label class="field"><span><input name="includeBusinessLatePaymentCompensation" type="checkbox"> Lägg till förseningsersättning 450 kr vid B2B-eskalering</span></label><label class="field">Anteckning<textarea name="note" maxlength="1000" rows="3"></textarea></label>${reminderBreakdown(modal.preview)}<p class="form-error">${escapeHtml(modal.error||'')}</p><div class="modal-actions"><button type="button" class="button ghost" data-action="preview-reminder">Beräkna</button><button class="button" type="submit" ${modal.preview?'':'disabled'}>Registrera påminnelse</button></div></form>${mode==='demo'?'<p class="notice warning">Demo: ingen e-post skickas. I backend registreras påminnelsen först; faktisk leverans kopplas senare till e-posttjänst.</p>':''}</div></section></div>`}
function modalHtml(){if(!modal)return '';if(modal.type==='comments')return commentsModal();if(modal.type==='reminder')return reminderModal();return ''}

function portalView(){const userName=session?.user?.displayName || 'Demoanvändare';app.innerHTML=`<div class="portal">${sidebar()}<section class="main"><header class="topbar"><div><h1>Kundreskontra</h1><p>Rollands / Försäljning / Kundreskontra</p></div><div class="user-chip"><div><b>${escapeHtml(userName)}</b><br><small>${mode==='demo'?'Demo':'Inloggad'}</small></div><div class="avatar">${escapeHtml(initials(userName))}</div>${mode==='api'?'<button class="button ghost small" data-action="logout">Logga ut</button>':''}</div></header><main class="content">${mode==='demo'?'<div class="demo-banner"><b>GitHub Pages-demo.</b> Kommentarer och kolumnval sparas bara i din webbläsare. Riktiga företagsuppgifter ska aldrig användas här.</div>':''}<div class="page-heading"><div><span class="eyebrow">Kundfordringar</span><h2>Fakturor och inbetalningar</h2><p>Alla läsbara fält från kravbilden finns med. Kolumner kan döljas individuellt. Högerklicka på en fakturarad för kommentar eller påminnelse.</p></div></div>${metrics()}<section class="panel"><div class="toolbar"><span class="hint">Högerklicka på en faktura för fler åtgärder.</span>${columnPicker()}</div>${table()}</section></main></section></div>${contextHtml()}${modalHtml()}`}

async function loadReceivables(){const data=await api('/receivables');invoices=data.invoices||[];portalView()}
async function openComments(invoiceId){contextMenu=null;let comments;if(mode==='demo')comments=demoComments(invoiceId);else comments=(await api(`/invoices/${encodeURIComponent(invoiceId)}/comments`)).comments;modal={type:'comments',invoiceId,comments};portalView()}
async function previewReminder(form){const invoice=invoiceById(modal.invoiceId);const values=Object.fromEntries(new FormData(form));const options={sentDate:values.sentDate,includeInterest:values.includeInterest==='on',includeReminderFee:values.includeReminderFee==='on',includeBusinessLatePaymentCompensation:values.includeBusinessLatePaymentCompensation==='on',customerType:invoice.customerType,reminderFeeAgreed:Boolean(invoice.reminderFeeAgreed)};try{const preview=mode==='demo'?R.reminderPreview({...invoice,reminders:[...(invoice.reminders||[]),...demoReminders(invoice.id)]},options,legalRates):(await api(`/invoices/${encodeURIComponent(invoice.id)}/reminders/preview`,{method:'POST',body:options})).preview;modal={...modal,preview,error:'',sentDate:values.sentDate,formValues:values};portalView()}catch(error){modal={...modal,preview:null,error:error.message,sentDate:values.sentDate};portalView()}}

function accessRecoveryView(message='Du saknar behörighet för den här arbetsytan.'){
  app.innerHTML=`<main class="access-recovery"><section class="access-recovery-card"><span class="eyebrow">Behörighet</span><h1>Den här arbetsytan är inte tillgänglig</h1><p>${escapeHtml(message)}</p><p>Du är fortfarande säkert inloggad. Logga ut och byt konto, eller gå till företagets översikt.</p><div class="access-recovery-actions"><button class="button" data-action="logout" type="button">Logga ut och byt konto</button><a class="button ghost" href="./dashboard.html">Gå till översikten</a></div></section></main>`;
}
async function boot(){
  try{legalRates=await fetch('../config/legal-rates.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('Räntekonfigurationen kunde inte laddas.');return r.json()});if(!R)throw new Error('Reskontramodulen kunde inte laddas.');if(mode==='demo'){invoices=structuredClone(demoInvoices);session={user:{displayName:'Demoanvändare'},company:{name:'Rollands Frukt o Grönt AB'}};portalView();return}const state=await api('/session');if(!state.authenticated){loginView();return}session={user:state.user,company:{id:state.companyId,name:'Företaget'}};await loadReceivables()}catch(error){if(error.code==='ACCESS_DENIED'){accessRecoveryView(error.message);return}app.innerHTML=`<main class="boot"><strong>Kunde inte starta portalen</strong><span>${escapeHtml(error.message)}</span></main>`}}

document.addEventListener('submit',async event=>{
  const form=event.target;
  if(form.id==='login-form'){event.preventDefault();const values=Object.fromEntries(new FormData(form));try{const data=await api('/auth/login',{method:'POST',body:values});csrfToken=data.csrfToken;sessionStorage.setItem('rollands-csrf',csrfToken);session={user:data.user,company:data.company};loginCompanies=[];await loadReceivables()}catch(error){if(error.code==='COMPANY_REQUIRED'){loginCompanies=error.data.companies||[];loginView('Välj vilket företag du vill öppna.')}else loginView(error.message)}return}
  if(form.dataset.form==='comment'){event.preventDefault();const text=String(new FormData(form).get('text')||'');try{if(mode==='demo'){const actor={id:'demo-user',name:'Demoanvändare'};const comment=R.createInvoiceComment({invoiceId:modal.invoiceId,companyId:'demo-company',actor,text});const list=[...demoComments(modal.invoiceId),comment];setDemoComments(modal.invoiceId,list);const invoice=invoiceById(modal.invoiceId);invoice.commentCount=list.length;modal={...modal,comments:list};portalView()}else{await api(`/invoices/${encodeURIComponent(modal.invoiceId)}/comments`,{method:'POST',body:{text}});await openComments(modal.invoiceId);await loadReceivables();modal={type:'comments',invoiceId:modal?.invoiceId,comments:(await api(`/invoices/${encodeURIComponent(modal?.invoiceId)}/comments`)).comments};portalView()}}catch(error){const el=form.querySelector('.form-error');if(el)el.textContent=error.message}return}
  if(form.dataset.form==='reminder'){event.preventDefault();if(!modal.preview)return;const invoice=invoiceById(modal.invoiceId);const values=Object.fromEntries(new FormData(form));const body={sentDate:values.sentDate,includeInterest:values.includeInterest==='on',includeReminderFee:values.includeReminderFee==='on',includeBusinessLatePaymentCompensation:values.includeBusinessLatePaymentCompensation==='on',kind:values.includeBusinessLatePaymentCompensation==='on'?'escalation':'payment-reminder',note:values.note||''};try{if(mode==='demo'){const record=R.createReminderRecord({invoice:{...invoice,reminders:[...(invoice.reminders||[]),...demoReminders(invoice.id)]},companyId:'demo-company',actor:{id:'demo-user',name:'Demoanvändare'},options:{...body,reminderFeeAgreed:Boolean(invoice.reminderFeeAgreed),customerType:invoice.customerType},config:legalRates});setDemoReminders(invoice.id,[...demoReminders(invoice.id),record]);modal=null;portalView()}else{await api(`/invoices/${encodeURIComponent(invoice.id)}/reminders`,{method:'POST',body});modal=null;await loadReceivables()}}catch(error){modal={...modal,error:error.message};portalView()}return}
});

document.addEventListener('change',event=>{const id=event.target.dataset.column;if(!id)return;if(event.target.checked)visibleColumns.add(id);else visibleColumns.delete(id);saveJson(COLUMN_KEY,[...visibleColumns]);portalView()});
document.addEventListener('contextmenu',event=>{const row=event.target.closest('[data-invoice-id]');if(!row)return;event.preventDefault();contextMenu={invoiceId:row.dataset.invoiceId,x:Math.min(event.clientX,innerWidth-255),y:Math.min(event.clientY,innerHeight-150)};portalView()});
document.addEventListener('click',async event=>{if(event.target.matches('[data-stop]')||event.target.closest('[data-stop]'))event.stopPropagation();const button=event.target.closest('[data-action]');if(!button){if(contextMenu){contextMenu=null;portalView()}return}const action=button.dataset.action;try{if(action==='close-context'){contextMenu=null;portalView()}if(action==='comment')await openComments(button.dataset.id);if(action==='reminder'){contextMenu=null;modal={type:'reminder',invoiceId:button.dataset.id,preview:null,error:'',sentDate:today()};portalView()}if(action==='close-modal'){modal=null;portalView()}if(action==='reset-columns'){visibleColumns=new Set(R.RECEIVABLE_COLUMNS.map(c=>c.id));saveJson(COLUMN_KEY,[...visibleColumns]);portalView()}if(action==='preview-reminder'){const form=button.closest('form');await previewReminder(form)}if(action==='logout'&&mode==='api'){if(csrfToken)await api('/auth/logout',{method:'POST',body:{}}).catch(()=>{});sessionStorage.removeItem('rollands-csrf');csrfToken='';session=null;loginView()}}catch(error){if(modal){modal={...modal,error:error.message};portalView()}}});

boot();
