const app=document.getElementById('automation-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const csrfToken=sessionStorage.getItem('rollands-csrf')||'';
let session=null;
let proposals=[];
let accounts=[];
let filter='open';
let message='';

const demoAccounts=[
  ['1510','Kundfordringar','Fordringar'],['1930','Företagskonto / bank','Likvida medel'],['2440','Leverantörsskulder','Skulder'],['2641','Ingående moms','Moms'],
  ['4010','Inköp varor och material','Varuinköp'],['5010','Lokalhyra','Lokalkostnader'],['5410','Förbrukningsinventarier','Övriga kostnader'],['5460','Förbrukningsmaterial','Övriga kostnader'],
  ['5910','Annonsering','Marknadsföring'],['6110','Kontorsmaterial','Kontorskostnader'],['6212','Mobiltelefon','Telekommunikation'],['6230','Datakommunikation / internet','Telekommunikation'],['6540','IT-tjänster','Externa tjänster'],['6570','Bankkostnader','Finansiella kostnader']
].map(([number,name,group])=>({number,name,group}));
const demoProposals=[
  {id:'demo-p1',type:'bank-payment-match',sourceId:'bank-2026-0916-01',status:'ready-for-approval',confidence:1,deterministic:true,ambiguous:false,reason:'OCR 310001 och exakt restbelopp 4 200,00 kr matchar en enda kundfaktura.',decisionReason:'Deterministiska regler gav en entydig träff. En behörig person ska fortfarande godkänna åtgärden.',evidence:[{kind:'payment-reference',label:'OCR',value:'310001',sourceId:'bank-2026-0916-01'},{kind:'amount',label:'Belopp',value:'4 200,00 kr',sourceId:'bank-2026-0916-01'}],suggestion:{action:'match-customer-payment',bankPaymentId:'bank-2026-0916-01',invoiceId:'invoice-310001',invoiceNumber:'310001',customerName:'Västra Hamnen Logistik AB',amountOre:420000,bookingDate:'2026-09-16',bankAccount:'1930',receivableAccount:'1510'},context:{payerName:'Västra Hamnen Logistik AB',reference:'310001',invoiceOptions:[{id:'invoice-310001',invoiceNumber:'310001',customerName:'Västra Hamnen Logistik AB',remainingOre:420000,dueDate:'2026-09-10'}]},review:{actionKind:'bank-payment-match',actionLabel:'Omför inbetalning till kundfaktura',actionDescription:'Matcha inbetalningen mot kundfaktura 310001 och föreslå bokföring av bank mot kundfordran.',target:{invoiceId:'invoice-310001',invoiceNumber:'310001',bankPaymentId:'bank-2026-0916-01'},amountOre:420000,bookingDate:'2026-09-16',accountingLines:[{account:'1930',accountName:'Företagskonto / bank',debitOre:420000,creditOre:0,label:'Inbetalning till bank',editable:true},{account:'1510',accountName:'Kundfordringar',debitOre:0,creditOre:420000,label:'Minska kundfordran',editable:true}],editable:{accounts:true,targetInvoice:true}},engine:{kind:'rules',name:'incoming-payment-matcher',version:'2'},createdAt:'2026-09-16T05:20:00.000Z'},
  {id:'demo-p2',type:'supplier-invoice-coding',sourceId:'supplier-invoice-8871',status:'manual-review',confidence:.72,deterministic:false,ambiguous:true,reason:'Leverantören har tidigare bokats på flera kostnadskonton och fakturatexten är inte entydig.',decisionReason:'Underlaget ger flera möjliga tolkningar.',evidence:[{kind:'supplier-history',label:'Tidigare konton',value:'4010, 5460, 6110',sourceId:'supplier-invoice-8871'},{kind:'invoice-text',label:'Fakturatext',value:'Varor och service september',sourceId:'supplier-invoice-8871'}],suggestion:{invoiceId:'supplier-invoice-8871',totalOre:125000,vatOre:25000,lines:[{account:'4010',debitOre:100000,creditOre:0,text:'Kostnad/inköp'},{account:'2641',debitOre:25000,creditOre:0,text:'Ingående moms'},{account:'2440',debitOre:0,creditOre:125000,text:'Leverantörsskuld'}]},context:{invoiceNumber:'8871',supplierName:'Demo Grossisten AB'},review:{actionKind:'supplier-invoice-coding',actionLabel:'Kontera leverantörsfaktura',actionDescription:'Fördela leverantörsfakturan på kostnads-/inköpskonto, ingående moms och leverantörsskuld. Kontona kan ändras före godkännande.',target:{supplierInvoiceId:'supplier-invoice-8871'},amountOre:125000,bookingDate:'',accountingLines:[{account:'4010',accountName:'Inköp varor och material',debitOre:100000,creditOre:0,label:'Kostnad/inköp',editable:true},{account:'2641',accountName:'Ingående moms',debitOre:25000,creditOre:0,label:'Ingående moms',editable:true},{account:'2440',accountName:'Leverantörsskulder',debitOre:0,creditOre:125000,label:'Leverantörsskuld',editable:true}],editable:{accounts:true,targetInvoice:false}},engine:{kind:'rules',name:'supplier-coding-history',version:'1'},createdAt:'2026-09-16T05:25:00.000Z'},
  {id:'demo-p3',type:'supplier-payment-preparation',sourceId:'payment-demo-44',status:'manual-review',confidence:.93,deterministic:false,ambiguous:false,reason:'Attesterad leverantörsfaktura är klar för betalningsförberedelse.',decisionReason:'Betalningsuppgifterna ska granskas av en person före frisläppning.',evidence:[{kind:'invoice',label:'Leverantörsfaktura',value:'Demo Grossisten AB / 8871',sourceId:'payment-demo-44'}],suggestion:{paymentId:'payment-demo-44',amountOre:125000,paymentDate:'2026-09-16',liabilityAccount:'2440',bankAccount:'1930'},context:{supplierName:'Demo Grossisten AB',invoiceNumber:'8871'},review:{actionKind:'supplier-payment-preparation',actionLabel:'Förbered utbetalning',actionDescription:'Förbered en utbetalning av leverantörsskulden. Detta skickar inte pengar till banken.',target:{paymentId:'payment-demo-44'},amountOre:125000,bookingDate:'2026-09-16',accountingLines:[{account:'2440',accountName:'Leverantörsskulder',debitOre:125000,creditOre:0,label:'Minska leverantörsskuld',editable:true},{account:'1930',accountName:'Företagskonto / bank',debitOre:0,creditOre:125000,label:'Utbetalning från bank',editable:true}],editable:{accounts:true,targetInvoice:false}},engine:{kind:'rules',name:'supplier-payment-preparation',version:'1'},createdAt:'2026-09-16T05:30:00.000Z'}
];

function esc(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initials(name){return String(name||'Användare').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function percent(value){return `${(Number(value||0)*100).toFixed(0)} %`}
function money(value){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(value||0)/100)}
function when(value){if(!value)return '—';try{return new Date(value).toLocaleString('sv-SE')}catch{return String(value)}}
function typeLabel(type){return ({'bank-payment-match':'INBETALNING','booking-account-suggestion':'KONTERING','supplier-invoice-coding':'LEVERANTÖRSFAKTURA · KONTERING','supplier-payment-preparation':'UTBETALNING'})[type]||'AUTOMATION'}
function statusLabel(status){return ({'manual-review':'Manuell granskning','ready-for-approval':'Redo för godkännande','approved':'Godkänt – ej genomfört','rejected':'Avvisat','superseded':'Ersatt'})[status]||status}
function isOpen(proposal){return ['manual-review','ready-for-approval'].includes(proposal.status)}
function accountLabel(number){const row=accounts.find(a=>a.number===String(number));return row?`${row.number} – ${row.name}`:String(number||'')}
function accountOptions(selected){const selectedNumber=String(selected||'');const known=accounts.some(account=>account.number===selectedNumber);const currentUnknown=selectedNumber&&!known?`<option value="${esc(selectedNumber)}" selected>${esc(selectedNumber)} – Nuvarande konto (inte i listan)</option>`:'';const groups=new Map();for(const account of accounts){if(!groups.has(account.group))groups.set(account.group,[]);groups.get(account.group).push(account)}return currentUnknown+[...groups.entries()].map(([group,rows])=>`<optgroup label="${esc(group)}">${rows.map(a=>`<option value="${esc(a.number)}" ${a.number===selectedNumber?'selected':''}>${esc(a.number)} – ${esc(a.name)}</option>`).join('')}</optgroup>`).join('')}

async function api(path,options={}){
  const headers={'Accept':'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};
  if(options.method&&options.method!=='GET'&&csrfToken)headers['X-CSRF-Token']=csrfToken;
  const response=await fetch(`/api/v1${path}`,{credentials:'same-origin',...options,headers,body:options.body?JSON.stringify(options.body):undefined});
  const data=await response.json().catch(()=>({}));
  if(!response.ok){const error=new Error(data.error||'Begäran misslyckades.');error.code=data.code;error.status=response.status;throw error}
  return data;
}

function sidebar(){const q=isDemo?'?demo=1':'';return `<aside class="sidebar"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">${esc(isDemo?'Rollands Frukt o Grönt AB':'Skyddad företagsmiljö')}<br>${isDemo?'Demoföretag':'Personlig session'}</div><div class="side-group"><span>Arbetsyta</span><a class="side-link side-link-link" href="./dashboard.html${q}">Översikt</a></div><div class="side-group"><span>Ekonomi</span><a class="side-link side-link-link" href="./bank.html${q}">Bank & avstämning</a><a class="side-link side-link-link" href="./payables.html${q}">Leverantörsfakturor</a><a class="side-link side-link-link" href="./accounting.html${q}">Bokföring</a><button class="side-link active">Automationskö</button><a class="side-link side-link-link" href="./reports.html${q}">Rapporter</a></div><div class="sidebar-footer">${isDemo?'Öppen demo. Alla förslag är exempeldata.':'Förslag granskas innan nästa kontrollerade steg.'}</div></aside>`}
function summary(){const open=proposals.filter(isOpen).length,ready=proposals.filter(p=>p.status==='ready-for-approval').length,review=proposals.filter(p=>p.status==='manual-review').length,done=proposals.filter(p=>['approved','rejected'].includes(p.status)).length;return `<section class="automation-summary"><article class="automation-card"><span>Öppna förslag</span><strong>${open}</strong></article><article class="automation-card"><span>Redo att godkänna</span><strong>${ready}</strong></article><article class="automation-card"><span>Kräver granskning</span><strong>${review}</strong></article><article class="automation-card"><span>Behandlade</span><strong>${done}</strong></article></section>`}
function visibleProposals(){if(filter==='all')return proposals;if(filter==='open')return proposals.filter(isOpen);return proposals.filter(p=>p.status===filter)}
function evidenceRows(proposal){return (proposal.evidence||[]).map(row=>`<div class="evidence-row"><b>${esc(row.label||row.kind)}</b>${esc(row.value)}${row.sourceId?`<br><small>Källa: ${esc(row.sourceId)}</small>`:''}</div>`).join('')||'<p class="empty">Inget underlag registrerat.</p>'}
function targetInfo(proposal){const r=proposal.review||{},c=proposal.context||{},s=proposal.suggestion||{};if(proposal.type==='bank-payment-match')return `<div class="action-facts"><span><b>Inbetalare</b>${esc(c.payerName||s.customerName||'—')}</span><span><b>Belopp</b>${esc(money(r.amountOre))}</span><span><b>Bankdatum</b>${esc(r.bookingDate||'—')}</span><span><b>Faktura</b>${esc(s.invoiceNumber||c.invoiceNumber||'—')}</span></div>`;if(proposal.type==='supplier-invoice-coding')return `<div class="action-facts"><span><b>Leverantör</b>${esc(c.supplierName||'—')}</span><span><b>Faktura</b>${esc(c.invoiceNumber||'—')}</span><span><b>Totalbelopp</b>${esc(money(r.amountOre))}</span><span><b>Moms</b>${esc(money(s.vatOre||0))}</span></div>`;if(proposal.type==='supplier-payment-preparation')return `<div class="action-facts"><span><b>Mottagare</b>${esc(c.supplierName||'—')}</span><span><b>Faktura</b>${esc(c.invoiceNumber||'—')}</span><span><b>Utbetalning</b>${esc(money(r.amountOre))}</span><span><b>Betaldatum</b>${esc(r.bookingDate||'—')}</span></div>`;return r.amountOre?`<div class="action-facts"><span><b>Belopp</b>${esc(money(r.amountOre))}</span></div>`:''}
function targetEditor(proposal){if(!isOpen(proposal)||!proposal.review?.editable?.targetInvoice)return'';const options=proposal.context?.invoiceOptions||[];if(!options.length)return'';return `<label class="target-editor"><span>Vilken kundfaktura ska inbetalningen kopplas till?</span><select data-target-invoice="${esc(proposal.id)}">${options.map(row=>`<option value="${esc(row.id)}" ${row.id===proposal.review?.target?.invoiceId?'selected':''}>${esc(row.invoiceNumber)} – ${esc(row.customerName)} – ${esc(money(row.remainingOre))}</option>`).join('')}</select><small>Endast öppna fakturor med samma restbelopp visas i denna version.</small></label>`}
function accountingTable(proposal){const lines=proposal.review?.accountingLines||[];if(!lines.length)return'<div class="no-booking"><b>Ingen kontering hör till detta förslag ännu.</b><span>Förslaget avser i första hand en arbetsflödesåtgärd.</span></div>';const editable=isOpen(proposal)&&proposal.review?.editable?.accounts;return `<div class="booking-box"><div class="booking-head"><div><span class="eyebrow">Föreslagen kontering</span><h4>Så här föreslås bokföringen</h4></div><span>${editable?'Konton kan ändras':'Låst efter behandling'}</span></div><div class="booking-table"><div class="booking-row booking-title"><span>Konto</span><span>Förklaring</span><span>Debet</span><span>Kredit</span></div>${lines.map((row,index)=>`<div class="booking-row" data-booking-row="${index}"><span>${editable?`<select data-account="${esc(proposal.id)}" data-line="${index}">${accountOptions(row.account)}</select>`:`<b>${esc(accountLabel(row.account))}</b>`}</span><span>${esc(row.label||row.accountName||'')}</span><span>${row.debitOre?esc(money(row.debitOre)):'—'}</span><span>${row.creditOre?esc(money(row.creditOre)):'—'}</span><input type="hidden" data-debit="${index}" value="${Number(row.debitOre||0)}"><input type="hidden" data-credit="${index}" value="${Number(row.creditOre||0)}"><input type="hidden" data-line-text="${index}" value="${esc(row.label||'')}"></div>`).join('')}</div></div>`}
function proposalCard(proposal){const actionable=isOpen(proposal);const approvedText=proposal.status==='approved'?`Godkänt ${esc(when(proposal.approvedAt))}`:proposal.status==='rejected'?`Avvisat: ${esc(proposal.rejectionReason||'Ingen motivering')}`:'';return `<article class="proposal" data-proposal="${esc(proposal.id)}" data-dirty="0"><header class="proposal-head"><div><span class="action-kind ${esc(proposal.type)}">${esc(typeLabel(proposal.type))}</span><h3>${esc(proposal.review?.actionLabel||'Granska förslag')}</h3><p class="action-description">${esc(proposal.review?.actionDescription||proposal.reason)}</p></div><span class="proposal-status ${esc(proposal.status)}">${esc(statusLabel(proposal.status))}</span></header><div class="proposal-body-v2"><section class="action-panel"><h4>Det här vill systemet göra</h4>${targetInfo(proposal)}${targetEditor(proposal)}${accountingTable(proposal)}<div class="execution-warning"><b>Inget genomförs bara för att du granskar eller ändrar förslaget.</b> Godkännande i Automationskön betyder fortfarande att förslaget är granskat. Bokföring, bankmatchning eller utbetalning går vidare genom respektive kontrollerade arbetsflöde.</div></section><details class="technical-details"><summary>Varför föreslår systemet detta?</summary><div class="details-grid"><div><h4>Bedömning</h4><dl class="proposal-grid"><dt>Säkerhet</dt><dd>${esc(percent(proposal.confidence))}</dd><dt>Entydig regelträff</dt><dd>${proposal.deterministic?'Ja':'Nej'}</dd><dt>Osäkert/tvetydigt</dt><dd>${proposal.ambiguous?'Ja':'Nej'}</dd><dt>Skapat</dt><dd>${esc(when(proposal.createdAt))}</dd><dt>Motor</dt><dd>${esc(`${proposal.engine?.name||'okänd'} ${proposal.engine?.version||''}`)}</dd></dl><div class="confidence"><span style="width:${Math.max(0,Math.min(100,Number(proposal.confidence||0)*100))}%"></span></div><div class="notice">${esc(proposal.decisionReason)}</div>${approvedText?`<div class="notice">${approvedText}</div>`:''}</div><div><h4>Underlag som användes</h4><div class="evidence-list">${evidenceRows(proposal)}</div></div></div></details></div>${actionable?`<footer class="proposal-actions"><span class="dirty-note" data-dirty-note="${esc(proposal.id)}"></span><input class="reason-input" data-reason="${esc(proposal.id)}" maxlength="2000" placeholder="Motivering krävs vid avvisning"><button class="button secondary" data-action="save" data-id="${esc(proposal.id)}">Spara ändringar</button><button class="button danger" data-action="reject" data-id="${esc(proposal.id)}">Avvisa</button><button class="button" data-action="approve" data-id="${esc(proposal.id)}">Godkänn granskat förslag</button></footer>`:''}</article>`}
function filters(){const items=[['open','Öppna'],['ready-for-approval','Redo'],['manual-review','Manuell granskning'],['approved','Godkända'],['rejected','Avvisade'],['all','Alla']];return `<div class="automation-filter">${items.map(([id,label])=>`<button data-filter="${id}" class="${filter===id?'active':''}">${label}</button>`).join('')}</div>`}
function render(){const userName=session?.user?.displayName||(isDemo?'Demoanvändare':'Inloggad användare');const list=visibleProposals();app.innerHTML=`<div class="portal">${sidebar()}<section class="main"><header class="topbar"><div><h1>Automationskö</h1><p>Rollands / Ekonomi / Automationskö</p></div><div class="user-chip"><div><b>${esc(userName)}</b><br><small>${isDemo?'Demo':'Inloggad'}</small></div><div class="avatar">${esc(initials(userName))}</div></div></header><main class="content automation-content">${isDemo?'<div class="demo-banner"><b>GitHub Pages-demo.</b> Förslagen är exempeldata. Du kan prova att byta konto och fakturamål utan att något bokförs.</div>':''}<div class="page-heading"><div><span class="eyebrow">Människa i kontroll</span><h2>Se exakt vad systemet vill göra</h2><p>Varje förslag visar åtgärdstyp, belopp och föreslagen kontering i klartext. Är något otydligt kan du ändra konton och relevanta val innan du godkänner.</p></div></div><div class="automation-note"><b>Viktigt:</b> Automationskön är en granskningsyta. Den visar och sparar förslaget, men utför inte själv bokföring eller bankbetalning.</div>${message?`<div class="notice">${esc(message)}</div>`:''}${summary()}<section class="panel"><div class="toolbar"><span class="hint">Filtrera efter status</span>${filters()}</div></section><section class="proposal-list">${list.map(proposalCard).join('')||'<div class="automation-empty">Inga förslag i det här urvalet.</div>'}</section></main></section></div>`}

async function load(){if(isDemo){session={user:{displayName:'Demoanvändare'}};accounts=structuredClone(demoAccounts);proposals=structuredClone(demoProposals);render();return}const state=await api('/session');if(!state.authenticated){app.innerHTML='<main class="boot"><strong>Inloggning krävs</strong><span>Öppna företagsportalen och logga in först.</span><p><a class="button" href="./index.html">Gå till inloggning</a></p></main>';return}session={user:state.user,companyId:state.companyId};const data=await api('/automation/proposals');proposals=data.proposals||[];accounts=data.accounts||[];render()}
function collectEdits(id){const proposal=proposals.find(p=>p.id===id);if(!proposal)throw new Error('Förslaget hittades inte.');const card=document.querySelector(`[data-proposal="${CSS.escape(id)}"]`);const lines=(proposal.review?.accountingLines||[]).map((row,index)=>({account:card?.querySelector(`[data-account="${CSS.escape(id)}"][data-line="${index}"]`)?.value||row.account,debitOre:Number(row.debitOre||0),creditOre:Number(row.creditOre||0),text:row.label||''}));const target=card?.querySelector(`[data-target-invoice="${CSS.escape(id)}"]`);return{...(lines.length?{accountingLines:lines}:{}),...(target?{invoiceId:target.value}: {})}}
async function saveSuggestion(id,{silent=false}={}){const proposal=proposals.find(p=>p.id===id);if(!proposal||!isOpen(proposal))return;if(isDemo){const edits=collectEdits(id);if(edits.accountingLines){proposal.review.accountingLines=edits.accountingLines.map(row=>({...row,accountName:accounts.find(a=>a.number===row.account)?.name||'Annat konto',label:row.text,editable:true}))}if(edits.invoiceId){const target=(proposal.context?.invoiceOptions||[]).find(row=>row.id===edits.invoiceId);if(target){proposal.suggestion.invoiceId=target.id;proposal.suggestion.invoiceNumber=target.invoiceNumber;proposal.suggestion.customerName=target.customerName;proposal.review.target.invoiceId=target.id;proposal.review.target.invoiceNumber=target.invoiceNumber}}proposal.status='manual-review';proposal.deterministic=false;proposal.ambiguous=true;proposal.decisionReason='Förslaget ändrades manuellt och behöver därför granskas på nytt.';if(!silent)message='Dina ändringar i demoförslaget sparades lokalt. Inget bokfördes.';render();return}if(!csrfToken)throw new Error('Säkerhetstoken saknas. Logga in igen i samma flik.');const data=await api(`/automation/proposals/${encodeURIComponent(id)}/suggestion`,{method:'PUT',body:collectEdits(id)});const index=proposals.findIndex(p=>p.id===id);if(index>=0)proposals[index]=data.proposal;if(!silent)message=data.message||'Ändringarna sparades.';render()}
async function approve(id){const card=document.querySelector(`[data-proposal="${CSS.escape(id)}"]`);if(card?.dataset.dirty==='1')await saveSuggestion(id,{silent:true});if(isDemo){const proposal=proposals.find(p=>p.id===id);if(proposal){proposal.status='approved';proposal.approvedBy='demo-user';proposal.approvedAt=new Date().toISOString();message='Demoförslaget markerades som godkänt. Ingen bokföring eller betalning utfördes.'}render();return}if(!csrfToken)throw new Error('Säkerhetstoken saknas. Logga in igen i samma flik.');const data=await api(`/automation/proposals/${encodeURIComponent(id)}/approve`,{method:'POST',body:{}});message=data.message||'Förslaget godkändes utan automatisk exekvering.';await load()}
async function reject(id,reason){if(!String(reason||'').trim())throw new Error('Skriv varför förslaget avvisas.');if(isDemo){const proposal=proposals.find(p=>p.id===id);if(proposal){proposal.status='rejected';proposal.rejectionReason=String(reason).trim();proposal.rejectedAt=new Date().toISOString();message='Demoförslaget avvisades.'}render();return}if(!csrfToken)throw new Error('Säkerhetstoken saknas. Logga in igen i samma flik.');await api(`/automation/proposals/${encodeURIComponent(id)}/reject`,{method:'POST',body:{reason:String(reason).trim()}});message='Förslaget avvisades och beslutet sparades i revisionsloggen.';await load()}

document.addEventListener('change',event=>{const editor=event.target.closest('[data-account],[data-target-invoice]');if(!editor)return;const card=editor.closest('[data-proposal]');if(!card)return;card.dataset.dirty='1';const note=card.querySelector('[data-dirty-note]');if(note)note.textContent='Du har osparade ändringar – de sparas automatiskt om du godkänner.'});
document.addEventListener('click',async event=>{const filterButton=event.target.closest('[data-filter]');if(filterButton){filter=filterButton.dataset.filter;render();return}const button=event.target.closest('[data-action]');if(!button)return;button.disabled=true;try{if(button.dataset.action==='save')await saveSuggestion(button.dataset.id);if(button.dataset.action==='approve')await approve(button.dataset.id);if(button.dataset.action==='reject'){const input=document.querySelector(`[data-reason="${CSS.escape(button.dataset.id)}"]`);await reject(button.dataset.id,input?.value||'')}}catch(error){message=error.message;render()}});
load().catch(error=>{app.innerHTML=`<main class="boot"><strong>Kunde inte ladda automationskön</strong><span>${esc(error.message)}</span><p><a class="button" href="./index.html">Till företagsportalen</a></p></main>`});
