const app=document.getElementById('automation-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const csrfToken=sessionStorage.getItem('rollands-csrf')||'';
const Demo=globalThis.RollandsDemoScenario;
let session=null,proposals=[],accounts=[],filter='open',message='';
const reclassRequests=new Map();
const fallbackAccounts=[['1510','Kundfordringar','Fordringar'],['1930','Företagskonto / bank','Likvida medel'],['2440','Leverantörsskulder','Skulder'],['2641','Ingående moms','Moms'],['4010','Inköp varor och material','Varuinköp'],['5010','Lokalhyra','Lokalkostnader'],['5410','Förbrukningsinventarier','Övriga kostnader'],['5460','Förbrukningsmaterial','Övriga kostnader'],['5510','Reparation och underhåll','Övriga kostnader'],['5910','Annonsering','Marknadsföring'],['6110','Kontorsmaterial','Kontorskostnader'],['6212','Mobiltelefon','Telekommunikation'],['6230','Datakommunikation / internet','Telekommunikation'],['6540','IT-tjänster','Externa tjänster'],['6570','Bankkostnader','Finansiella kostnader']].map(([number,name,group])=>({number,name,group}));
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initials(name){return String(name||'Användare').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function percent(v){return `${Math.round(Number(v||0)*100)} %`}
function money(v){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(v||0)/100)}
function when(v){if(!v)return'—';try{return new Date(v).toLocaleString('sv-SE')}catch{return String(v)}}
function typeLabel(type){return ({'bank-payment-match':'INBETALNING','booking-account-suggestion':'KONTERING','supplier-invoice-coding':'LEVERANTÖRSFAKTURA · KONTERING','supplier-payment-preparation':'UTBETALNING'})[type]||'AUTOMATION'}
function statusLabel(value){const p=typeof value==='object'?value:null,status=p?p.status:value;if(p?.type==='bank-payment-match'&&status==='approved'&&p.executionStatus==='executed')return'Bokförd';return ({'manual-review':'Manuell granskning','ready-for-approval':'Redo för godkännande','approved':'Godkänt – ej genomfört','rejected':'Avvisat','superseded':'Ersatt'})[status]||status}
function isOpen(p){return ['manual-review','ready-for-approval'].includes(p.status)}
function accountName(number){return accounts.find(a=>a.number===String(number))?.name||'Annat konto'}
function accountOptions(selected){const value=String(selected||''),known=accounts.some(a=>a.number===value);const current=!known&&value?`<option value="${esc(value)}" selected>${esc(value)} – Nuvarande konto (inte i listan)</option>`:'';const groups=new Map();for(const a of accounts){if(!groups.has(a.group))groups.set(a.group,[]);groups.get(a.group).push(a)}return current+[...groups].map(([group,rows])=>`<optgroup label="${esc(group)}">${rows.map(a=>`<option value="${esc(a.number)}" ${a.number===value?'selected':''}>${esc(a.number)} – ${esc(a.name)}</option>`).join('')}</optgroup>`).join('')}
async function api(path,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.method&&options.method!=='GET'&&csrfToken?{'X-CSRF-Token':csrfToken}:{})};const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',...options,headers,body:options.body?JSON.stringify(options.body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Begäran misslyckades.');return data}
function sidebar(){const q=isDemo?'?demo=1':'';return `<aside class="sidebar"><div class="logo"><strong>${esc(isDemo?'Rollands':session?.company?.name||'Företaget')}</strong><small>LT STUDIO</small></div><div class="company-pill">${esc(session?.company?.name||(isDemo?'Rollands Frukt o Grönt AB':'Företaget'))}<br>${isDemo?'Demoföretag':'Personlig session'}</div><div class="side-group"><span>Arbetsyta</span><a class="side-link" href="./dashboard.html${q}">Översikt</a></div><div class="side-group"><span>Ekonomi</span><a class="side-link" href="./bank.html${q}">Bank & avstämning</a><a class="side-link" href="./payables.html${q}">Leverantörsfakturor</a><a class="side-link" href="./accounting.html${q}">Bokföring</a><button class="side-link active">Automationskö</button><a class="side-link" href="./reports.html${q}">Rapporter</a></div><div class="sidebar-footer">${isDemo?'Gemensamt UAT-scenario · alla poster är fiktiva.':'Förslag granskas innan nästa kontrollerade steg.'}</div></aside>`}
function summary(){const open=proposals.filter(isOpen).length,ready=proposals.filter(p=>p.status==='ready-for-approval').length,review=proposals.filter(p=>p.status==='manual-review').length,done=proposals.filter(p=>['approved','rejected'].includes(p.status)).length;return `<section class="automation-summary"><article class="automation-card"><span>Öppna förslag</span><strong>${open}</strong></article><article class="automation-card"><span>Redo att godkänna</span><strong>${ready}</strong></article><article class="automation-card"><span>Kräver granskning</span><strong>${review}</strong></article><article class="automation-card"><span>Behandlade</span><strong>${done}</strong></article></section>`}
function targetFacts(p){const s=p.suggestion||{},c=p.context||{},r=p.review||{};if(p.type==='bank-payment-match'){const current=p.currentAllocation;return `<div class="action-facts"><span><b>Inbetalare</b>${esc(c.payerName||s.customerName||'—')}</span><span><b>Belopp</b>${money(r.amountOre)}</span><span><b>Bankdatum</b>${esc(r.bookingDate||'—')}</span><span><b>${p.executionStatus==='executed'?'Aktuell faktura':'Faktura/avi'}</b>${esc(current?.invoiceNumber||s.invoiceNumber||c.invoiceNumber||'—')}${current?.customerName?`<small>${esc(current.customerName)}</small>`:''}</span></div>`;}if(p.type==='supplier-invoice-coding')return `<div class="action-facts"><span><b>Leverantör</b>${esc(c.supplierName||'—')}</span><span><b>Faktura</b>${esc(c.invoiceNumber||'—')}</span><span><b>Totalbelopp</b>${money(r.amountOre)}</span><span><b>Moms</b>${money(s.vatOre||0)}</span></div>`;if(p.type==='supplier-payment-preparation')return `<div class="action-facts"><span><b>Mottagare</b>${esc(c.supplierName||'—')}</span><span><b>Faktura</b>${esc(c.invoiceNumber||'—')}</span><span><b>Utbetalning</b>${money(r.amountOre)}</span><span><b>Betaldatum</b>${esc(r.bookingDate||'—')}</span></div>`;return''}
function targetEditor(p){if(!isOpen(p)||!p.review?.editable?.targetInvoice)return'';const options=p.context?.invoiceOptions||[];return options.length?`<label class="target-editor"><span>Vilken kundfaktura/avi ska inbetalningen kopplas till?</span><select data-target-invoice="${esc(p.id)}">${options.map(row=>`<option value="${esc(row.id)}" ${row.id===p.review?.target?.invoiceId?'selected':''}>${esc(row.invoiceNumber)} – ${esc(row.customerName)} – ${money(row.remainingOre)}</option>`).join('')}</select><small>Endast öppna fakturor med samma restbelopp visas.</small></label>`:''}
function booking(p){const lines=p.review?.accountingLines||[];if(!lines.length)return'<div class="no-booking"><b>Ingen föreslagen kontering finns.</b></div>';const editable=isOpen(p)&&p.review?.editable?.accounts;return `<div class="booking-box"><div class="booking-head"><div><span class="eyebrow">Föreslagen kontering</span><h4>Så här föreslås bokföringen</h4></div><span>${editable?'Konton kan ändras':'Låst efter behandling'}</span></div><div class="booking-table"><div class="booking-row booking-title"><span>Konto</span><span>Förklaring</span><span>Debet</span><span>Kredit</span></div>${lines.map((row,i)=>`<div class="booking-row"><span>${editable?`<select data-account="${esc(p.id)}" data-line="${i}">${accountOptions(row.account)}</select>`:`<b>${esc(row.account)} – ${esc(accountName(row.account))}</b>`}</span><span>${esc(row.label||row.accountName||'')}</span><span>${row.debitOre?money(row.debitOre):'—'}</span><span>${row.creditOre?money(row.creditOre):'—'}</span></div>`).join('')}</div></div>`}
function executionControls(p){
  if(isDemo||p.type!=='bank-payment-match'||p.status!=='approved')return'';
  if(p.executionStatus!=='executed')return `<footer class="proposal-actions"><span class="dirty-note">Godkänd av människa men ännu inte bokförd.</span><button class="button" data-action="execute" data-id="${esc(p.id)}">Bokför kundbetalning</button></footer>`;
  const options=p.context?.invoiceOptions||[];
  if(!options.length)return '<footer class="proposal-actions"><span class="dirty-note">Betalningen är bokförd. Ingen annan öppen faktura med exakt samma restbelopp finns att omföra till.</span></footer>';
  const today=new Date().toISOString().slice(0,10);
  return `<footer class="proposal-actions reclass-controls"><label><span>Omför till</span><select data-reclass-target="${esc(p.id)}">${options.map(row=>`<option value="${esc(row.id)}">${esc(row.invoiceNumber)} – ${esc(row.customerName)} – ${money(row.remainingOre)}</option>`).join('')}</select></label><label><span>Rättelsedatum</span><input type="date" data-reclass-date="${esc(p.id)}" value="${today}"></label><input class="reason-input" data-reclass-reason="${esc(p.id)}" maxlength="500" placeholder="Varför ska betalningen omföras?"><button class="button secondary" data-action="reclassify" data-id="${esc(p.id)}">Omför betalning</button></footer>`;
}
function evidence(p){return (p.evidence||[]).map(e=>`<div class="evidence-row"><b>${esc(e.label||e.kind)}</b>${esc(e.value)}</div>`).join('')||'<p class="empty">Inget underlag registrerat.</p>'}
function card(p){const open=isOpen(p);return `<article class="proposal" data-proposal="${esc(p.id)}" data-dirty="0"><header class="proposal-head"><div><span class="action-kind ${esc(p.type)}">${esc(typeLabel(p.type))}</span><h3>${esc(p.review?.actionLabel||'Granska förslag')}</h3><p class="action-description">${esc(p.review?.actionDescription||p.reason||'')}</p></div><span class="proposal-status ${esc(p.status)}">${esc(statusLabel(p))}</span></header><div class="proposal-body-v2"><section class="action-panel"><h4>Det här vill systemet göra</h4>${targetFacts(p)}${targetEditor(p)}${booking(p)}<div class="execution-warning"><b>Godkännande är inte samma sak som genomförande.</b> Förslaget går vidare till respektive kontrollerade arbetsflöde.</div></section><details class="technical-details"><summary>Varför föreslår systemet detta?</summary><div class="details-grid"><div><h4>Bedömning</h4><dl class="proposal-grid"><dt>Säkerhet</dt><dd>${percent(p.confidence)}</dd><dt>Entydig regelträff</dt><dd>${p.deterministic?'Ja':'Nej'}</dd><dt>Osäkert/tvetydigt</dt><dd>${p.ambiguous?'Ja':'Nej'}</dd><dt>Skapat</dt><dd>${esc(when(p.createdAt))}</dd></dl><div class="notice">${esc(p.decisionReason||'')}</div></div><div><h4>Underlag</h4><div class="evidence-list">${evidence(p)}</div></div></div></details></div>${open?`<footer class="proposal-actions"><span class="dirty-note" data-dirty-note="${esc(p.id)}"></span><input class="reason-input" data-reason="${esc(p.id)}" maxlength="2000" placeholder="Motivering krävs vid avvisning"><button class="button secondary" data-action="save" data-id="${esc(p.id)}">Spara ändringar</button><button class="button danger" data-action="reject" data-id="${esc(p.id)}">Avvisa</button><button class="button" data-action="approve" data-id="${esc(p.id)}">Godkänn granskat förslag</button></footer>`:executionControls(p)}</article>`}
function visible(){if(filter==='all')return proposals;if(filter==='open')return proposals.filter(isOpen);return proposals.filter(p=>p.status===filter)}
function filters(){return [['open','Öppna'],['ready-for-approval','Redo'],['manual-review','Manuell granskning'],['approved','Godkända'],['rejected','Avvisade'],['all','Alla']].map(([id,label])=>`<button data-filter="${id}" class="${filter===id?'active':''}">${label}</button>`).join('')}
function render(){const name=session?.user?.displayName||(isDemo?'Demoanvändare':'Inloggad användare');app.innerHTML=`<div class="portal">${sidebar()}<section class="main"><header class="topbar"><div><h1>Automationskö</h1><p>${esc(session?.company?.name||(isDemo?'Rollands':'Företaget'))} / Ekonomi / Automationskö</p></div><div class="user-chip"><div><b>${esc(name)}</b></div><div class="avatar">${esc(initials(name))}</div></div></header><main class="content automation-content">${isDemo?'<div class="demo-banner"><b>Gemensamt UAT-scenario.</b> Här syns samma fakturor och betalningar som i övriga ekonomimoduler.</div>':''}<div class="page-heading"><div><span class="eyebrow">Människa i kontroll</span><h2>Se exakt vad systemet vill göra</h2><p>Typ av åtgärd, mål, belopp och kontering visas i klartext. Konton kan ändras innan godkännande.</p></div></div>${message?`<div class="notice">${esc(message)}</div>`:''}${summary()}<section class="panel"><div class="toolbar"><span class="hint">Filtrera efter status</span><div class="automation-filter">${filters()}</div></div></section><section class="proposal-list">${visible().map(card).join('')||'<div class="automation-empty">Inga förslag i urvalet.</div>'}</section></main></section></div>`}
function collect(id){const p=proposals.find(x=>x.id===id),el=document.querySelector(`[data-proposal="${CSS.escape(id)}"]`);if(!p||!el)throw new Error('Förslaget hittades inte.');const accountingLines=(p.review?.accountingLines||[]).map((row,i)=>({account:el.querySelector(`[data-account="${CSS.escape(id)}"][data-line="${i}"]`)?.value||row.account,debitOre:Number(row.debitOre||0),creditOre:Number(row.creditOre||0),text:row.label||''}));const target=el.querySelector(`[data-target-invoice="${CSS.escape(id)}"]`);return{accountingLines,...(target?{invoiceId:target.value}:{})}}
function persistDemo(){if(!Demo)return;Demo.patch(state=>{state.automationProposals=structuredClone(proposals)})}
async function saveSuggestion(id,{silent=false}={}){const p=proposals.find(x=>x.id===id);if(!p||!isOpen(p))return;const edits=collect(id);if(isDemo){p.review.accountingLines=edits.accountingLines.map(row=>({...row,accountName:accountName(row.account),label:row.text,editable:true}));p.suggestion.accountingLines=structuredClone(edits.accountingLines);if(edits.invoiceId){const target=(p.context?.invoiceOptions||[]).find(row=>row.id===edits.invoiceId);if(target){p.suggestion.invoiceId=target.id;p.suggestion.invoiceNumber=target.invoiceNumber;p.suggestion.customerName=target.customerName;p.review.target.invoiceId=target.id;p.review.target.invoiceNumber=target.invoiceNumber}}p.status='manual-review';p.deterministic=false;p.ambiguous=true;p.decisionReason='Förslaget ändrades manuellt och behöver därför granskas på nytt.';persistDemo();if(!silent)message='Ändringarna sparades i det gemensamma demoscenariot.';render();return}const data=await api(`/automation/proposals/${encodeURIComponent(id)}/suggestion`,{method:'PUT',body:edits});const index=proposals.findIndex(x=>x.id===id);if(index>=0)proposals[index]=data.proposal;if(!silent)message=data.message||'Ändringarna sparades.';render()}
async function approve(id){const el=document.querySelector(`[data-proposal="${CSS.escape(id)}"]`);if(el?.dataset.dirty==='1')await saveSuggestion(id,{silent:true});if(isDemo){const p=proposals.find(x=>x.id===id);if(p){p.status='approved';p.approvedBy='demo-user';p.approvedAt=new Date().toISOString();persistDemo();message='Förslaget är godkänt i demon. Ingen bokföring eller bankbetalning genomfördes automatiskt.'}render();return}const data=await api(`/automation/proposals/${encodeURIComponent(id)}/approve`,{method:'POST',body:{}});message=data.message||'Förslaget godkändes utan automatisk exekvering.';await load()}
async function reject(id,reason){if(!String(reason||'').trim())throw new Error('Skriv varför förslaget avvisas.');if(isDemo){const p=proposals.find(x=>x.id===id);if(p){p.status='rejected';p.rejectionReason=String(reason).trim();p.rejectedAt=new Date().toISOString();persistDemo();message='Förslaget avvisades i demon.'}render();return}await api(`/automation/proposals/${encodeURIComponent(id)}/reject`,{method:'POST',body:{reason:String(reason).trim()}});message='Förslaget avvisades.';await load()}
async function executeApproved(id){const data=await api(`/automation/proposals/${encodeURIComponent(id)}/execute`,{method:'POST',body:{}});message=data.message||'Kundbetalningen bokfördes.';await load()}
function reclassRequest(id,payload){const signature=JSON.stringify([payload.targetInvoiceId,payload.correctionDate,payload.reason]);const existing=reclassRequests.get(id);if(existing?.signature===signature)return existing.requestId;const requestId=`customer-reclass-${crypto.randomUUID()}`;reclassRequests.set(id,{signature,requestId});return requestId}
async function reclassify(id){
  const targetInvoiceId=document.querySelector(`[data-reclass-target="${CSS.escape(id)}"]`)?.value||'';
  const correctionDate=document.querySelector(`[data-reclass-date="${CSS.escape(id)}"]`)?.value||'';
  const reason=document.querySelector(`[data-reclass-reason="${CSS.escape(id)}"]`)?.value||'';
  if(!targetInvoiceId)throw new Error('Välj vilken faktura betalningen ska flyttas till.');
  if(!correctionDate)throw new Error('Ange rättelsedatum.');
  if(String(reason).trim().length<5)throw new Error('Skriv varför betalningen ska omföras.');
  const payload={targetInvoiceId,correctionDate,reason:String(reason).trim()};
  const requestId=reclassRequest(id,payload);
  const data=await api(`/automation/proposals/${encodeURIComponent(id)}/reclassify`,{method:'POST',body:{...payload,requestId}});
  reclassRequests.delete(id);message=data.message||'Kundbetalningen omfördes.';await load();
}
async function load(){if(isDemo){if(!Demo)throw new Error('Det gemensamma demoscenariot kunde inte laddas.');session={user:{displayName:'Demoanvändare'}};accounts=structuredClone(fallbackAccounts);proposals=Demo.section('automationProposals');render();return}const state=await api('/session');if(!state.authenticated){location.href='./index.html';return}session=state;const data=await api('/automation/proposals');proposals=data.proposals||[];accounts=data.accounts||fallbackAccounts;render()}
document.addEventListener('change',event=>{const editor=event.target.closest('[data-account],[data-target-invoice]');if(!editor)return;const card=editor.closest('[data-proposal]');if(card){card.dataset.dirty='1';const note=card.querySelector('[data-dirty-note]');if(note)note.textContent='Osparade ändringar – de sparas automatiskt om du godkänner.'}});
document.addEventListener('click',async event=>{const f=event.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render();return}const b=event.target.closest('[data-action]');if(!b)return;b.disabled=true;try{if(b.dataset.action==='save')await saveSuggestion(b.dataset.id);if(b.dataset.action==='approve')await approve(b.dataset.id);if(b.dataset.action==='reject')await reject(b.dataset.id,document.querySelector(`[data-reason="${CSS.escape(b.dataset.id)}"]`)?.value||'');if(b.dataset.action==='execute')await executeApproved(b.dataset.id);if(b.dataset.action==='reclassify')await reclassify(b.dataset.id)}catch(error){message=error.message;render()}});
load().catch(error=>{app.innerHTML=`<main class="boot"><strong>Kunde inte ladda automationskön</strong><span>${esc(error.message)}</span></main>`});
