const app=document.getElementById('bank-app');
const isDemo=new URLSearchParams(location.search).get('demo')==='1';
const isSupabase=location.hostname==='ludwigberglund-coder.github.io'&&!isDemo;
const csrfToken=sessionStorage.getItem('rollands-csrf')||'';
const Demo=globalThis.RollandsDemoScenario;
let session=null;
let payments=[];
let supabaseCtx=null,openInvoices=[];
let message='';
let refreshing=false;

function esc(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ore(value){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(value||0)/100)}
function normalizeText(value){return String(value??'').trim().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('sv').replace(/[^a-z0-9]+/g,' ').trim()}
function compact(value){return normalizeText(value).replace(/\s+/g,'')}
function digits(value){return String(value??'').replace(/\D+/g,'')}
function words(value){return normalizeText(value).split(/\s+/).filter(token=>token.length>=3)}
function canonicalName(value){const ignored=new Set(['ab','aktiebolag','hb','handelsbolag','kb','kommanditbolag','sweden','sverige']);return normalizeText(value).split(/\s+/).filter(token=>token&&!ignored.has(token)).join(' ')}
function referenceMatches(payment,value){const targetText=compact(value),targetDigits=digits(value);if(!targetText&&!targetDigits)return false;for(const source of [payment.reference,payment.message].filter(Boolean)){if(targetDigits&&targetDigits.length>=4){const sourceTokens=String(source).split(/[^0-9]+/).filter(Boolean);if(sourceTokens.includes(targetDigits))return true}if(targetText&&targetText.length>=4&&words(source).some(token=>compact(token)===targetText))return true;if(targetText&&compact(source)===targetText)return true}return false}
function nameSimilarity(leftValue,rightValue){const left=canonicalName(leftValue),right=canonicalName(rightValue);if(!left||!right)return 0;if(left===right)return 1;if(left.length>=6&&right.length>=6&&(left.includes(right)||right.includes(left)))return .9;const a=new Set(left.split(/\s+/)),b=new Set(right.split(/\s+/)),intersection=[...a].filter(v=>b.has(v)).length,union=new Set([...a,...b]).size;return union?intersection/union:0}
function scoreCandidate(payment,invoice){const amount=Number(payment.amountOre),remaining=Number(invoice.remainingOre),amountMatch=amount===remaining,partialAmount=amount>0&&amount<remaining,amountWithinBalance=amount>0&&amount<=remaining,ocrMatch=referenceMatches(payment,invoice.ocr),invoiceNumberMatch=referenceMatches(payment,invoice.invoiceNumber),customerNameScore=nameSimilarity(payment.payerName,invoice.customerName);let score=0,deterministic=false;const evidence=[];if(ocrMatch){score+=.62;evidence.push({kind:'payment-reference',label:'OCR',value:String(invoice.ocr||''),sourceId:payment.id})}else if(invoiceNumberMatch){score+=.56;evidence.push({kind:'payment-reference',label:'Fakturanummer',value:String(invoice.invoiceNumber||''),sourceId:payment.id})}if(amountMatch){score+=.32;evidence.push({kind:'amount',label:'Exakt restbelopp',value:String(payment.amountOre),sourceId:payment.id})}else if(partialAmount){score+=.18;evidence.push({kind:'amount',label:'Delbetalning inom restbelopp',value:String(payment.amountOre),sourceId:payment.id})}if(customerNameScore>=.9){score+=.14;evidence.push({kind:'payer-name',label:'Betalarnamn',value:String(payment.payerName||''),sourceId:payment.id})}else if(customerNameScore>=.5){score+=.07;evidence.push({kind:'payer-name',label:'Delvis namnmatchning',value:String(payment.payerName||''),sourceId:payment.id})}score=Math.min(1,score);if((ocrMatch||invoiceNumberMatch)&&amountMatch)deterministic=true;return{invoice,score,deterministic,amountWithinBalance,ocrMatch,invoiceNumberMatch,customerNameScore,evidence}}
function analyzeIncomingPayment(payment){const scored=openInvoices.map(invoice=>scoreCandidate(payment,invoice)).filter(candidate=>candidate.amountWithinBalance&&candidate.score>=.45).sort((a,b)=>b.score-a.score||String(a.invoice.id).localeCompare(String(b.invoice.id)));if(!scored.length)return{status:'no-match',reason:'Ingen öppen kundfaktura gav tillräckligt starka matchningssignaler.',candidates:[]};const best=scored[0],second=scored[1],ambiguous=Boolean(second&&second.score>=best.score-.05),confidence=ambiguous?Math.min(best.score,.69):best.score,status=confidence>=.75?'proposal':'manual-review';const reason=[];if(best.ocrMatch)reason.push('OCR matchar');else if(best.invoiceNumberMatch)reason.push('fakturanummer matchar');if(Number(payment.amountOre)===Number(best.invoice.remainingOre))reason.push('beloppet matchar restbeloppet');else reason.push('beloppet är en delbetalning inom restbeloppet');if(best.customerNameScore>=.9)reason.push('betalarnamnet matchar kunden');if(ambiguous)reason.push('flera fakturor ligger nära samma matchningspoäng');return{status,confidence,deterministic:best.deterministic&&!ambiguous,ambiguous,targetInvoiceId:best.invoice.id,targetInvoiceNumber:best.invoice.invoiceNumber,targetCustomerName:best.invoice.customerName,reason:reason.join(', ')||'Matchning baserad på betalningsinformationen.',evidence:best.evidence,candidates:scored.slice(0,5).map(candidate=>({invoiceId:candidate.invoice.id,invoiceNumber:candidate.invoice.invoiceNumber,customerName:candidate.invoice.customerName,remainingOre:candidate.invoice.remainingOre,score:candidate.score}))}}
async function supabaseContext(){supabaseCtx=supabaseCtx?.authenticated?supabaseCtx:await window.LTSupabaseUat.context();if(!supabaseCtx?.authenticated||!supabaseCtx.company){location.href='./index.html';throw new Error('Ingen aktiv Supabase-session.')}return supabaseCtx}
async function loadSupabaseBank(){const ctx=await supabaseContext(),filter='company_id=eq.'+encodeURIComponent(ctx.company.id);const [bankRows,invoiceRows,customerRows]=await Promise.all([window.LTSupabase.from('bank_payments',ctx.accessToken).select('*',filter+'&order=booking_date.desc,created_at.desc'),window.LTSupabase.from('invoices',ctx.accessToken).select('*',filter+'&remaining_ore=gt.0'),window.LTSupabase.from('customers',ctx.accessToken).select('*',filter)]);const customers=new Map((customerRows||[]).map(r=>[String(r.id),r]));payments=(bankRows||[]).map(r=>({id:r.id,companyId:r.company_id,externalId:r.external_id,bookingDate:r.booking_date,valueDate:r.value_date,amountOre:Number(r.amount_ore||0),currency:r.currency,reference:r.reference||'',message:r.message||'',payerName:r.payer_name||'',payerAccount:r.payer_account||'',status:r.status,createdAt:r.created_at,updatedAt:r.updated_at}));openInvoices=(invoiceRows||[]).filter(r=>Number(r.total_ore)>0&&Number(r.remaining_ore)>0&&String(r.invoice_account||'1510')==='1510').map(r=>{const customer=customers.get(String(r.customer_id))||{};return{id:r.id,companyId:r.company_id,invoiceNumber:r.invoice_number,ocr:r.ocr||r.invoice_number,remainingOre:Number(r.remaining_ore||0),customerName:customer.name||'',customerNumber:customer.customer_number||''}});session={user:ctx.user,company:ctx.company}}
function initials(name){return String(name||'Användare').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function statusLabel(status){return ({unmatched:'Ej matchad','proposal-created':'Förslag skapat',reviewed:'Granskad',posted:'Bokförd inbetalning',ignored:'Ignorerad'})[status]||status}
async function api(path,options={}){const headers={'Accept':'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};if(options.method&&options.method!=='GET'&&csrfToken)headers['X-CSRF-Token']=csrfToken;const response=await fetch(`/api/v1${path}`,{credentials:'same-origin',cache:'no-store',...options,headers,body:options.body?JSON.stringify(options.body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||'Begäran misslyckades.');error.code=data.code;throw error}return data}
function sidebar(){return `<aside class="sidebar"><div class="logo"><strong>${esc(isDemo?'Rollands':session?.company?.name||'Företaget')}</strong><small>LT STUDIO</small></div><div class="company-pill">${esc(session?.company?.name||(isDemo?'Rollands Frukt o Grönt AB':'Företaget'))}<br>${isDemo?'Demoföretag':'Personlig session'}</div><div class="side-group"><span>Arbetsyta</span><a class="side-link side-link-link" href="./dashboard.html${isDemo?'?demo=1':''}">Översikt</a></div><div class="side-group"><span>Försäljning</span><a class="side-link side-link-link" href="./index.html${isDemo?'?demo=1':''}">Kundreskontra</a></div><div class="side-group"><span>Ekonomi</span><button class="side-link active">Bank & avstämning</button><a class="side-link side-link-link" href="./automation.html${isDemo?'?demo=1':''}">Automationskö</a><a class="side-link side-link-link" href="./accounting.html${isDemo?'?demo=1':''}">Bokföring</a><a class="side-link side-link-link" href="./reports.html${isDemo?'?demo=1':''}">Rapporter</a></div><div class="sidebar-footer">${isDemo?'Gemensamt UAT-scenario. Ingen riktig bank är ansluten.':'Bankdata isoleras per företag och kräver personlig session.'}</div></aside>`}
function summary(){const unmatched=payments.filter(p=>p.status==='unmatched').length,proposals=payments.filter(p=>p.status==='proposal-created').length,total=payments.reduce((s,p)=>s+p.amountOre,0);return `<section class="bank-summary"><article><span>Dagens inbetalningar</span><strong>${payments.length}</strong></article><article><span>Ej matchade</span><strong>${unmatched}</strong></article><article><span>Förslag skapade</span><strong>${proposals}</strong></article><article><span>Importerat belopp</span><strong>${ore(total)}</strong></article></section>`}
function rows(){return payments.map(p=>`<tr><td>${esc(p.bookingDate)}</td><td><b>${esc(p.payerName||'Okänd')}</b><br><small>${esc(p.payerAccount||'—')}</small></td><td>${esc(p.reference||'—')}<br><small>${esc(p.message||'')}</small></td><td class="money">${esc(ore(p.amountOre))}</td><td><span class="bank-status ${esc(p.status)}">${esc(statusLabel(p.status))}</span></td><td>${p.status==='unmatched'?`<button class="button small" data-match="${esc(p.id)}">Analysera matchning</button>`:`<a class="button ghost small" href="./automation.html${isDemo?'?demo=1':''}">Öppna förslag</a>`}</td></tr>`).join('')}
function render(){const userName=session?.user?.displayName||(isDemo?'Demoanvändare':'Inloggad användare');app.innerHTML=`<div class="portal">${sidebar()}<section class="main"><header class="topbar"><div><h1>Bank & avstämning</h1><p>${esc(session?.company?.name||(isDemo?'Rollands':'Företaget'))} / Ekonomi / Bank</p></div><div class="user-chip"><div><b>${esc(userName)}</b><br><small>${isDemo?'Demo':'Inloggad'}</small></div><div class="avatar">${esc(initials(userName))}</div></div></header><main class="content bank-content">${isDemo?'<div class="demo-banner"><b>Gemensamt UAT-scenario.</b> Samma fakturanummer och belopp används i Kundreskontra, Bank, Automationskö och Bokföring.</div>':''}<div class="page-heading"><div><span class="eyebrow">Automatisk avstämning</span><h2>Inkommande betalningar</h2><p>Matchningsmotorn jämför referens, fakturanummer, restbelopp och betalarnamn och skickar ett begripligt förslag till Automationskön.</p></div></div>${message?`<div class="notice">${esc(message)}</div>`:''}${summary()}<section class="panel"><div class="toolbar"><span class="hint">Ingen rad bokförs automatiskt från denna vy.</span><div class="bank-toolbar-actions"><button class="button ghost small" type="button" data-action="refresh-bank" ${refreshing?'disabled':''}>${refreshing?'Uppdaterar…':'Uppdatera'}</button><a class="button ghost small" href="./automation.html${isDemo?'?demo=1':''}">Öppna Automationskö</a></div></div><div class="table-scroll"><table class="res-table bank-table"><thead><tr><th>Datum</th><th>Betalare</th><th>Referens</th><th>Belopp</th><th>Status</th><th>Åtgärd</th></tr></thead><tbody>${rows()||'<tr><td colspan="6" class="empty">Inga inbetalningar.</td></tr>'}</tbody></table></div></section></main></section></div>`}
async function refreshPayments({feedback=false}={}){
  if(refreshing)return;
  refreshing=true;if(feedback){message='';render()}
  try{
    payments=isDemo?Demo.section('bankPayments'):isSupabase?(await loadSupabaseBank(),payments):(await api('/bank/payments')).payments||[];
    if(feedback)message=`Bankhändelserna är uppdaterade ${new Intl.DateTimeFormat('sv-SE',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())}.`;
  }finally{refreshing=false;render()}
}
async function load(){
  if(isDemo){if(!Demo)throw new Error('Det gemensamma demoscenariot kunde inte laddas.');session={user:{displayName:'Demoanvändare'}};await refreshPayments();return}
  if(isSupabase){await loadSupabaseBank();render();return}
  const state=await api('/session');
  if(!state.authenticated){app.innerHTML='<main class="boot"><strong>Inloggning krävs</strong><span>Logga in i företagsportalen först.</span><p><a class="button" href="./index.html">Gå till inloggning</a></p></main>';return}
  session=state;await refreshPayments();
}
async function matchPayment(id){if(isDemo){const proposal=Demo.bankMatchProposal(id);if(!proposal){message='Ingen säker träff hittades. Betalningen behöver manuell hantering.';render();return}Demo.patch(state=>{const payment=state.bankPayments.find(p=>p.id===id);if(payment)payment.status='proposal-created';if(!state.automationProposals.some(p=>p.sourceId===id))state.automationProposals.unshift(proposal)});payments=Demo.section('bankPayments');message=`Förslag skapat: koppla inbetalningen till kundfaktura/avi ${proposal.suggestion.invoiceNumber}. Granska konteringen i Automationskön.`;render();return}
  if(isSupabase){const ctx=await supabaseContext(),payment=payments.find(p=>p.id===id);if(!payment)throw new Error('Bankhändelsen hittades inte.');const analysis=analyzeIncomingPayment(payment);if(analysis.status==='no-match'){message=analysis.reason;render();return}const saved=(await window.LTSupabase.rpc('create_bank_match_proposal',{p_company_id:ctx.company.id,p_bank_payment_id:payment.id,p_target_invoice_id:analysis.targetInvoiceId,p_confidence_ppm:Math.round(analysis.confidence*1000000),p_deterministic:analysis.deterministic,p_ambiguous:analysis.ambiguous,p_reason:analysis.reason,p_evidence:analysis.evidence},ctx.accessToken))?.[0];if(!saved)throw new Error('Matchningsförslaget kunde inte sparas i Supabase.');await loadSupabaseBank();message=`Förslag skapat för faktura ${analysis.targetInvoiceNumber}. Granska och godkänn det i Automationskön.`;render();return}
  if(!csrfToken)throw new Error('Säkerhetstoken saknas. Logga in igen i samma flik.');const data=await api(`/bank/payments/${encodeURIComponent(id)}/match`,{method:'POST',body:{}});message=data.proposal?'Matchningsförslag skapat. Granska det i Automationskön.':(data.analysis?.reason||'Ingen säker träff hittades.');await load()}
document.addEventListener('click',async event=>{
  const refreshButton=event.target.closest('[data-action="refresh-bank"]');
  if(refreshButton){void refreshPayments({feedback:true}).catch(error=>{refreshing=false;message=error.message;render()});return}
  const button=event.target.closest('[data-match]');if(!button)return;
  button.disabled=true;try{await matchPayment(button.dataset.match)}catch(error){message=error.message;render()}
});
load().catch(error=>{app.innerHTML=`<main class="boot"><strong>Kunde inte ladda bankavstämningen</strong><span>${esc(error.message)}</span></main>`});
