const app=document.getElementById('bank-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const csrfToken=sessionStorage.getItem('rollands-csrf')||'';
const Demo=globalThis.RollandsDemoScenario;
let session=null;
let payments=[];
let overview={rows:[],totals:{incomingOre:0,outgoingOre:0,netOre:0,count:0}};
let overviewPeriod='month';
let message='';

function esc(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ore(value){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(value||0)/100)}
function initials(name){return String(name||'Användare').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function today(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function dateIso(dt){return dt.toISOString().slice(0,10)}
function periodBounds(date,period){const [y,m,d]=date.split('-').map(Number),dt=new Date(Date.UTC(y,m-1,d));if(period==='day')return{from:date,to:date};if(period==='week'){const dow=dt.getUTCDay()||7,start=new Date(dt);start.setUTCDate(dt.getUTCDate()-(dow-1));const end=new Date(start);end.setUTCDate(start.getUTCDate()+6);return{from:dateIso(start),to:dateIso(end)}}if(period==='quarter'){const qm=Math.floor((m-1)/3)*3;return{from:dateIso(new Date(Date.UTC(y,qm,1))),to:dateIso(new Date(Date.UTC(y,qm+3,0)))}}return{from:`${date.slice(0,7)}-01`,to:dateIso(new Date(Date.UTC(y,m,0)))}}
function statusLabel(status){return ({unmatched:'Ej matchad','proposal-created':'Förslag skapat',reviewed:'Granskad',posted:'Bokförd',ignored:'Ignorerad',prepared:'Förberedd',released:'Frisläppt',paid:'Betald',cancelled:'Avbruten'})[status]||status}
async function api(path,options={}){const headers={'Accept':'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};if(options.method&&options.method!=='GET'&&csrfToken)headers['X-CSRF-Token']=csrfToken;const response=await fetch(`/api/v1${path}`,{credentials:'same-origin',...options,headers,body:options.body?JSON.stringify(options.body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||'Begäran misslyckades.');error.code=data.code;throw error}return data}
function sidebar(){return `<aside class="sidebar"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">${esc(isDemo?'Rollands Frukt o Grönt AB':'Skyddad företagsmiljö')}<br>${isDemo?'Demoföretag':'Personlig session'}</div><div class="side-group"><span>Arbetsyta</span><a class="side-link side-link-link" href="./dashboard.html${isDemo?'?demo=1':''}">Översikt</a></div><div class="side-group"><span>Försäljning</span><a class="side-link side-link-link" href="./index.html${isDemo?'?demo=1':''}">Kundreskontra</a></div><div class="side-group"><span>Ekonomi</span><button class="side-link active">Bank & avstämning</button><a class="side-link side-link-link" href="./automation.html${isDemo?'?demo=1':''}">Automationskö</a><a class="side-link side-link-link" href="./accounting.html${isDemo?'?demo=1':''}">Bokföring</a><a class="side-link side-link-link" href="./reports.html${isDemo?'?demo=1':''}">Rapporter</a></div><div class="sidebar-footer">${isDemo?'Gemensamt UAT-scenario. Ingen riktig bank är ansluten.':'Bankdata isoleras per företag och kräver personlig session.'}</div></aside>`}
function summary(){const unmatched=payments.filter(p=>p.status==='unmatched').length,proposals=payments.filter(p=>p.status==='proposal-created').length,total=payments.reduce((s,p)=>s+p.amountOre,0);return `<section class="bank-summary"><article><span>Dagens inbetalningar</span><strong>${payments.length}</strong></article><article><span>Ej matchade</span><strong>${unmatched}</strong></article><article><span>Förslag skapade</span><strong>${proposals}</strong></article><article><span>Importerat belopp</span><strong>${ore(total)}</strong></article></section>`}
function demoOverview(){
  const range=periodBounds(today(),overviewPeriod);
  const rows=[
    ...Demo.section('bankPayments').map(p=>({id:p.id,date:p.bookingDate,direction:'in',counterparty:p.payerName,reference:p.reference,amountOre:p.amountOre,account:'',status:p.status,sourceType:'bank-payment',sourceId:p.id})),
    ...Demo.section('supplierPayments').map(p=>({id:p.id,date:p.paymentDate,direction:'out',counterparty:p.supplierName,reference:p.supplierInvoiceNumber,amountOre:p.amountOre,account:'1930',status:p.status,sourceType:'supplier-payment',sourceId:p.id}))
  ].filter(p=>p.date>=range.from&&p.date<=range.to).sort((a,b)=>b.date.localeCompare(a.date));
  const incomingOre=rows.filter(r=>r.direction==='in').reduce((s,r)=>s+Number(r.amountOre||0),0),outgoingOre=rows.filter(r=>r.direction==='out').reduce((s,r)=>s+Number(r.amountOre||0),0);
  return{...range,rows,totals:{incomingOre,outgoingOre,netOre:incomingOre-outgoingOre,count:rows.length}};
}
function overviewSummary(){return `<section class="bank-summary"><article><span>Inbetalningar</span><strong>${ore(overview.totals.incomingOre)}</strong></article><article><span>Utbetalningar</span><strong>${ore(overview.totals.outgoingOre)}</strong></article><article><span>Netto</span><strong>${ore(overview.totals.netOre)}</strong></article><article><span>Betalningar</span><strong>${overview.totals.count}</strong></article></section>`}
function overviewRows(){return overview.rows.map(p=>`<tr><td>${esc(p.date)}</td><td><b>${p.direction==='in'?'Inbetalning':'Utbetalning'}</b></td><td>${esc(p.counterparty||'—')}</td><td>${esc(p.reference||'—')}</td><td>${esc(p.account||'—')}</td><td class="money">${esc(ore(p.amountOre))}</td><td><span class="bank-status ${esc(p.status)}">${esc(statusLabel(p.status))}</span></td></tr>`).join('')}
function overviewSection(){return `<section class="panel"><div class="panel-heading"><div><span class="eyebrow">Betalningsöversikt</span><h2>In- och utbetalningar</h2><p>${esc(overview.from||'')} – ${esc(overview.to||'')}. Samma källdata ligger kvar i respektive bank- och leverantörsflöde.</p></div></div><div class="toolbar payment-periods"><span class="hint">Visa per:</span>${[['day','Dag'],['week','Vecka'],['month','Månad'],['quarter','Kvartal']].map(([id,label])=>`<button type="button" class="button small ${overviewPeriod===id?'':'ghost'}" data-period="${id}">${label}</button>`).join('')}</div>${overviewSummary()}<div class="table-scroll"><table class="res-table bank-table"><thead><tr><th>Datum</th><th>Riktning</th><th>Motpart</th><th>Referens</th><th>Konto</th><th>Belopp</th><th>Status</th></tr></thead><tbody>${overviewRows()||'<tr><td colspan="7" class="empty">Inga betalningar i vald period.</td></tr>'}</tbody></table></div></section>`}
function rows(){return payments.map(p=>`<tr><td>${esc(p.bookingDate)}</td><td><b>${esc(p.payerName||'Okänd')}</b><br><small>${esc(p.payerAccount||'—')}</small></td><td>${esc(p.reference||'—')}<br><small>${esc(p.message||'')}</small></td><td class="money">${esc(ore(p.amountOre))}</td><td><span class="bank-status ${esc(p.status)}">${esc(statusLabel(p.status))}</span></td><td>${p.status==='unmatched'?`<button class="button small" data-match="${esc(p.id)}">Analysera matchning</button>`:`<a class="button ghost small" href="./automation.html${isDemo?'?demo=1':''}">Öppna förslag</a>`}</td></tr>`).join('')}
function render(){const userName=session?.user?.displayName||(isDemo?'Demoanvändare':'Inloggad användare');app.innerHTML=`<div class="portal">${sidebar()}<section class="main"><header class="topbar"><div><h1>Bank & avstämning</h1><p>Rollands / Ekonomi / Bank</p></div><div class="user-chip"><div><b>${esc(userName)}</b><br><small>${isDemo?'Demo':'Inloggad'}</small></div><div class="avatar">${esc(initials(userName))}</div></div></header><main class="content bank-content">${isDemo?'<div class="demo-banner"><b>Gemensamt UAT-scenario.</b> Samma fakturanummer och belopp används i Kundreskontra, Bank, Automationskö och Bokföring.</div>':''}<div class="page-heading"><div><span class="eyebrow">Betalningar</span><h2>Överblick och avstämning</h2><p>Se företagets in- och utbetalningar i samma arbetsyta. Matchning och bokföring sker fortfarande i respektive originalflöde.</p></div></div>${message?`<div class="notice">${esc(message)}</div>`:''}${overviewSection()}<div class="page-heading"><div><span class="eyebrow">Automatisk avstämning</span><h2>Inkommande bankhändelser att matcha</h2><p>Matchningsmotorn jämför referens, fakturanummer, restbelopp och betalarnamn och skickar ett begripligt förslag till Automationskön.</p></div></div>${summary()}<section class="panel"><div class="toolbar"><span class="hint">Ingen rad bokförs automatiskt från denna vy.</span><a class="button ghost small" href="./automation.html${isDemo?'?demo=1':''}">Öppna Automationskö</a></div><div class="table-scroll"><table class="res-table bank-table"><thead><tr><th>Datum</th><th>Betalare</th><th>Referens</th><th>Belopp</th><th>Status</th><th>Åtgärd</th></tr></thead><tbody>${rows()||'<tr><td colspan="6" class="empty">Inga inbetalningar.</td></tr>'}</tbody></table></div></section></main></section></div>`}
async function loadOverview(){overview=isDemo?demoOverview():await api(`/bank/overview?date=${encodeURIComponent(today())}&period=${encodeURIComponent(overviewPeriod)}`)}
async function load(){if(isDemo){if(!Demo)throw new Error('Det gemensamma demoscenariot kunde inte laddas.');session={user:{displayName:'Demoanvändare'}};payments=Demo.section('bankPayments');await loadOverview();render();return}const state=await api('/session');if(!state.authenticated){app.innerHTML='<main class="boot"><strong>Inloggning krävs</strong><span>Logga in i företagsportalen först.</span><p><a class="button" href="./index.html">Gå till inloggning</a></p></main>';return}session={user:state.user,companyId:state.companyId};const [bank]=await Promise.all([api('/bank/payments'),loadOverview()]);payments=bank.payments||[];render()}
async function matchPayment(id){if(isDemo){const proposal=Demo.bankMatchProposal(id);if(!proposal){message='Ingen säker träff hittades. Betalningen behöver manuell hantering.';render();return}Demo.patch(state=>{const payment=state.bankPayments.find(p=>p.id===id);if(payment)payment.status='proposal-created';if(!state.automationProposals.some(p=>p.sourceId===id))state.automationProposals.unshift(proposal)});payments=Demo.section('bankPayments');message=`Förslag skapat: koppla inbetalningen till kundfaktura/avi ${proposal.suggestion.invoiceNumber}. Granska konteringen i Automationskön.`;render();return}if(!csrfToken)throw new Error('Säkerhetstoken saknas. Logga in igen i samma flik.');const data=await api(`/bank/payments/${encodeURIComponent(id)}/match`,{method:'POST',body:{}});message=data.proposal?'Matchningsförslag skapat. Granska det i Automationskön.':(data.analysis?.reason||'Ingen säker träff hittades.');await load()}
document.addEventListener('click',async event=>{const periodButton=event.target.closest('[data-period]');if(periodButton){overviewPeriod=periodButton.dataset.period;periodButton.disabled=true;try{await loadOverview();render()}catch(error){message=error.message;render()}return}const button=event.target.closest('[data-match]');if(!button)return;button.disabled=true;try{await matchPayment(button.dataset.match)}catch(error){message=error.message;render()}});
load().catch(error=>{app.innerHTML=`<main class="boot"><strong>Kunde inte ladda bankavstämningen</strong><span>${esc(error.message)}</span></main>`});
