const app=document.getElementById('bank-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const csrfToken=sessionStorage.getItem('rollands-csrf')||'';
const Demo=globalThis.RollandsDemoScenario;
let session=null;
let payments=[];
let message='';

function esc(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ore(value){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(value||0)/100)}
function initials(name){return String(name||'Användare').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function statusLabel(status){return ({unmatched:'Ej matchad','proposal-created':'Förslag skapat',reviewed:'Granskad',posted:'Bokförd inbetalning',ignored:'Ignorerad'})[status]||status}
async function api(path,options={}){const headers={'Accept':'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};if(options.method&&options.method!=='GET'&&csrfToken)headers['X-CSRF-Token']=csrfToken;const response=await fetch(`/api/v1${path}`,{credentials:'same-origin',...options,headers,body:options.body?JSON.stringify(options.body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||'Begäran misslyckades.');error.code=data.code;throw error}return data}
function sidebar(){return `<aside class="sidebar"><div class="logo"><strong>${esc(isDemo?'Rollands':session?.company?.name||'Företaget')}</strong><small>LT STUDIO</small></div><div class="company-pill">${esc(session?.company?.name||(isDemo?'Rollands Frukt o Grönt AB':'Företaget'))}<br>${isDemo?'Demoföretag':'Personlig session'}</div><div class="side-group"><span>Arbetsyta</span><a class="side-link side-link-link" href="./dashboard.html${isDemo?'?demo=1':''}">Översikt</a></div><div class="side-group"><span>Försäljning</span><a class="side-link side-link-link" href="./index.html${isDemo?'?demo=1':''}">Kundreskontra</a></div><div class="side-group"><span>Ekonomi</span><button class="side-link active">Bank & avstämning</button><a class="side-link side-link-link" href="./automation.html${isDemo?'?demo=1':''}">Automationskö</a><a class="side-link side-link-link" href="./accounting.html${isDemo?'?demo=1':''}">Bokföring</a><a class="side-link side-link-link" href="./reports.html${isDemo?'?demo=1':''}">Rapporter</a></div><div class="sidebar-footer">${isDemo?'Gemensamt UAT-scenario. Ingen riktig bank är ansluten.':'Bankdata isoleras per företag och kräver personlig session.'}</div></aside>`}
function summary(){const unmatched=payments.filter(p=>p.status==='unmatched').length,proposals=payments.filter(p=>p.status==='proposal-created').length,total=payments.reduce((s,p)=>s+p.amountOre,0);return `<section class="bank-summary"><article><span>Dagens inbetalningar</span><strong>${payments.length}</strong></article><article><span>Ej matchade</span><strong>${unmatched}</strong></article><article><span>Förslag skapade</span><strong>${proposals}</strong></article><article><span>Importerat belopp</span><strong>${ore(total)}</strong></article></section>`}
function rows(){return payments.map(p=>`<tr><td>${esc(p.bookingDate)}</td><td><b>${esc(p.payerName||'Okänd')}</b><br><small>${esc(p.payerAccount||'—')}</small></td><td>${esc(p.reference||'—')}<br><small>${esc(p.message||'')}</small></td><td class="money">${esc(ore(p.amountOre))}</td><td><span class="bank-status ${esc(p.status)}">${esc(statusLabel(p.status))}</span></td><td>${p.status==='unmatched'?`<button class="button small" data-match="${esc(p.id)}">Analysera matchning</button>`:`<a class="button ghost small" href="./automation.html${isDemo?'?demo=1':''}">Öppna förslag</a>`}</td></tr>`).join('')}
function render(){const userName=session?.user?.displayName||(isDemo?'Demoanvändare':'Inloggad användare');app.innerHTML=`<div class="portal">${sidebar()}<section class="main"><header class="topbar"><div><h1>Bank & avstämning</h1><p>${esc(session?.company?.name||(isDemo?'Rollands':'Företaget'))} / Ekonomi / Bank</p></div><div class="user-chip"><div><b>${esc(userName)}</b><br><small>${isDemo?'Demo':'Inloggad'}</small></div><div class="avatar">${esc(initials(userName))}</div></div></header><main class="content bank-content">${isDemo?'<div class="demo-banner"><b>Gemensamt UAT-scenario.</b> Samma fakturanummer och belopp används i Kundreskontra, Bank, Automationskö och Bokföring.</div>':''}<div class="page-heading"><div><span class="eyebrow">Automatisk avstämning</span><h2>Inkommande betalningar</h2><p>Matchningsmotorn jämför referens, fakturanummer, restbelopp och betalarnamn och skickar ett begripligt förslag till Automationskön.</p></div></div>${message?`<div class="notice">${esc(message)}</div>`:''}${summary()}<section class="panel"><div class="toolbar"><span class="hint">Ingen rad bokförs automatiskt från denna vy.</span><a class="button ghost small" href="./automation.html${isDemo?'?demo=1':''}">Öppna Automationskö</a></div><div class="table-scroll"><table class="res-table bank-table"><thead><tr><th>Datum</th><th>Betalare</th><th>Referens</th><th>Belopp</th><th>Status</th><th>Åtgärd</th></tr></thead><tbody>${rows()||'<tr><td colspan="6" class="empty">Inga inbetalningar.</td></tr>'}</tbody></table></div></section></main></section></div>`}
async function load(){if(isDemo){if(!Demo)throw new Error('Det gemensamma demoscenariot kunde inte laddas.');session={user:{displayName:'Demoanvändare'}};payments=Demo.section('bankPayments');render();return}const state=await api('/session');if(!state.authenticated){app.innerHTML='<main class="boot"><strong>Inloggning krävs</strong><span>Logga in i företagsportalen först.</span><p><a class="button" href="./index.html">Gå till inloggning</a></p></main>';return}session=state;payments=(await api('/bank/payments')).payments||[];render()}
async function matchPayment(id){if(isDemo){const proposal=Demo.bankMatchProposal(id);if(!proposal){message='Ingen säker träff hittades. Betalningen behöver manuell hantering.';render();return}Demo.patch(state=>{const payment=state.bankPayments.find(p=>p.id===id);if(payment)payment.status='proposal-created';if(!state.automationProposals.some(p=>p.sourceId===id))state.automationProposals.unshift(proposal)});payments=Demo.section('bankPayments');message=`Förslag skapat: koppla inbetalningen till kundfaktura/avi ${proposal.suggestion.invoiceNumber}. Granska konteringen i Automationskön.`;render();return}if(!csrfToken)throw new Error('Säkerhetstoken saknas. Logga in igen i samma flik.');const data=await api(`/bank/payments/${encodeURIComponent(id)}/match`,{method:'POST',body:{}});message=data.proposal?'Matchningsförslag skapat. Granska det i Automationskön.':(data.analysis?.reason||'Ingen säker träff hittades.');await load()}
document.addEventListener('click',async event=>{const button=event.target.closest('[data-match]');if(!button)return;button.disabled=true;try{await matchPayment(button.dataset.match)}catch(error){message=error.message;render()}});
load().catch(error=>{app.innerHTML=`<main class="boot"><strong>Kunde inte ladda bankavstämningen</strong><span>${esc(error.message)}</span></main>`});
