const app=document.getElementById('control-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const Demo=globalThis.RollandsDemoScenario;
let session=null,events=[],query='';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function when(v){try{return new Intl.DateTimeFormat('sv-SE',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Stockholm'}).format(new Date(v))}catch{return String(v||'—')}}
function sidebar(){return `<aside class="sidebar"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">Rollands Frukt o Grönt AB</div></aside>`}
async function api(path){const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',headers:{Accept:'application/json'}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Begäran misslyckades.');return data}
function demoEvents(){const state=Demo.state(),rows=[];for(const i of state.accountingEntries||[])rows.push({id:`ae-${i.id}`,createdAt:`${i.postingDate}T10:00:00Z`,action:'ACCOUNTING_ENTRY_POSTED',entityType:'accounting-entry',entityId:i.id,actorName:'Demoekonom',details:{number:i.number,description:i.description}});for(const p of state.automationProposals||[])rows.push({id:`ap-${p.id}`,createdAt:p.createdAt||`${Demo.AS_OF_DATE}T08:00:00Z`,action:'AUTOMATION_PROPOSAL_CREATED',entityType:'automation-proposal',entityId:p.id,actorName:'Systemet',details:{type:p.type,status:p.status}});for(const d of state.documents||[])rows.push({id:`doc-${d.id}`,createdAt:d.createdAt,action:'DOCUMENT_REGISTERED',entityType:'document',entityId:d.id,actorName:d.uploadedBy||'Demoanvändare',details:{fileName:d.fileName,category:d.category}});return rows.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}
function taskRows(){if(!isDemo)return[];const s=Demo.state(),rows=[];const supplierChanges=(s.supplierPendingChanges||[]).filter(x=>x.status==='pending');if(supplierChanges.length)rows.push({kind:'Leverantörer',count:supplierChanges.length,text:'Ändrade betalningsuppgifter väntar separat godkännande.',href:'./suppliers.html?demo=1'});const approvals=(s.supplierInvoices||[]).filter(x=>x.status==='coded');if(approvals.length)rows.push({kind:'Attest',count:approvals.length,text:'Leverantörsfakturor väntar attest.',href:'./payables.html?demo=1'});const coding=(s.supplierInvoices||[]).filter(x=>['registered','coding-review'].includes(x.status));if(coding.length)rows.push({kind:'Kontering',count:coding.length,text:'Leverantörsfakturor behöver konteras.',href:'./payables.html?demo=1'});const bank=(s.bankPayments||[]).filter(x=>x.status==='unmatched');if(bank.length)rows.push({kind:'Bank',count:bank.length,text:'Bankhändelser behöver matchas eller granskas.',href:'./bank.html?demo=1'});const unlock=(s.accountingUnlockRequests||[]).filter(x=>x.status==='pending');if(unlock.length)rows.push({kind:'Perioder',count:unlock.length,text:'Upplåsningsbegäran väntar kontroll.',href:'./accounting.html?demo=1'});return rows}
const integrations=[
  {name:'Bank – inkommande',status:'demo',text:'Import och matchningsflöde finns. Ingen riktig bank är ansluten i GitHub Pages.'},
  {name:'Bank – utbetalningar',status:'not-connected',text:'Betalningar kan förberedas och frisläppas internt. Riktig banköverföring kräver bankleverantör/API.'},
  {name:'E-post',status:'not-connected',text:'Intern outbox och leveransstatus finns. Ingen e-postleverantör är ansluten, därför markeras inget som levererat.'},
  {name:'AI',status:'rules',text:'Förslagsmotorn är förklarbar och regelbaserad i denna version. Ingen extern AI-tjänst är ansluten.'},
  {name:'Lön',status:'import',text:'Lönejournal kan importeras, valideras och bokföras. Själva löneberäkningen kan ligga i externt lönesystem.'}
];
function visibleEvents(){const n=query.trim().toLocaleLowerCase('sv-SE');if(!n)return events;return events.filter(e=>JSON.stringify(e).toLocaleLowerCase('sv-SE').includes(n))}
function label(action){return ({ACCOUNTING_ENTRY_POSTED:'Bokföring',AUTOMATION_PROPOSAL_CREATED:'Automationsförslag',DOCUMENT_REGISTERED:'Dokument',SESSION_LOGIN:'Inloggning',INVOICE_COMMENT_ADDED:'Fakturakommentar',PAYMENT_REMINDER_CREATED:'Betalningspåminnelse',SUPPLIER_INVOICE_APPROVED:'Leverantörsfaktura attesterad',SUPPLIER_PAYMENT_CONFIRMED_AND_POSTED:'Betalning bokförd'})[action]||String(action||'Händelse').replaceAll('_',' ')}
function render(){const tasks=taskRows(),rows=visibleEvents();app.innerHTML=`<div class="portal">${sidebar()}<section class="main"><header class="topbar"><div><h1>Kontrollcenter</h1><p>Att göra · revisionsspår · integrationer</p></div><div class="user-chip"><b>${esc(session?.user?.displayName||'Demo kontroll')}</b></div></header><main class="content control-content">${isDemo?'<div class="demo-banner"><b>Kontrollvy för UAT.</b> Integrationsstatusen visar avsiktligt vad som inte är anslutet – systemet får aldrig simulera extern leverans som verklig.</div>':''}<section class="control-hero"><div><span class="eyebrow">Kontroll & trygghet</span><h2>Se vad som väntar, vad som har hänt och vad som faktiskt är anslutet</h2><p>Det här är företagets kontrollbord. Arbetsköer leder vidare till rätt modul och revisionsspåret gör viktiga händelser sökbara.</p></div></section><section class="control-grid"><div class="panel control-tasks"><div class="control-head"><div><span class="eyebrow">Att göra</span><h3>Väntar på åtgärd</h3></div><strong>${tasks.reduce((s,t)=>s+t.count,0)}</strong></div>${tasks.length?tasks.map(t=>`<a class="task-row" href="${t.href}"><span class="task-count">${t.count}</span><span><b>${esc(t.kind)}</b><small>${esc(t.text)}</small></span><span>→</span></a>`).join(''):'<p class="empty">Inga väntande demoåtgärder.</p>'}</div><div class="panel integrations"><div class="control-head"><div><span class="eyebrow">Integrationer</span><h3>Verklig status</h3></div></div>${integrations.map(i=>`<article class="integration-row"><span class="integration-dot ${i.status}"></span><div><b>${esc(i.name)}</b><small>${esc(i.text)}</small></div><span class="integration-status ${i.status}">${i.status==='not-connected'?'Inte ansluten':i.status==='demo'?'Demo/import':'Intern motor'}</span></article>`).join('')}</div></section><section class="panel audit-panel"><div class="control-head audit-head"><div><span class="eyebrow">Revisionsspår</span><h3>Senaste händelser</h3></div><input id="audit-search" value="${esc(query)}" placeholder="Sök händelse, id eller innehåll"></div><div class="audit-list">${rows.slice(0,100).map(e=>`<article class="audit-row"><span class="audit-time">${esc(when(e.createdAt))}</span><span><b>${esc(label(e.action))}</b><small>${esc(e.entityType||'')} · ${esc(e.entityId||'')}</small></span><span><b>${esc(e.actorName||e.userId||'System')}</b><small>${esc(Object.values(e.details||{}).filter(v=>typeof v!=='object').join(' · '))}</small></span></article>`).join('')||'<p class="empty">Inga händelser matchar sökningen.</p>'}</div></section></main></section></div>`}
async function load(){if(isDemo){if(!Demo)throw new Error('Demoscenariot kunde inte laddas.');session={user:{displayName:'Demokontrollant'}};events=demoEvents();render();return}const s=await api('/session');if(!s.authenticated){location.href='./index.html';return}session=s;events=(await api('/audit')).events||[];render()}
document.addEventListener('input',e=>{if(e.target.id!=='audit-search')return;query=e.target.value;render();const input=document.getElementById('audit-search');input?.focus();input?.setSelectionRange(query.length,query.length)});
load().catch(error=>{app.innerHTML=`<main class="boot"><strong>Kontrollcentret kunde inte laddas</strong><span>${esc(error.message)}</span></main>`});
