const app=document.getElementById('customers-app');
const Demo=globalThis.RollandsDemoScenario;
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
let editing=null,message='',privateCustomers=[],csrfToken=sessionStorage.getItem('rollands-csrf')||'',createRequestId='',showArchived=false;
const copy=value=>JSON.parse(JSON.stringify(value));
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function url(path){return `${path}${isDemo?(path.includes('?')?'&':'?')+'demo=1':''}`;}
function demoCustomers(){const s=Demo.state(),map=new Map();for(const i of s.customerInvoices||[])if(!map.has(i.customerNumber))map.set(i.customerNumber,{id:'customer-'+i.customerNumber,customerNumber:i.customerNumber,name:i.customerName,paymentTermsDays:30,reminderFeeAgreed:Boolean(i.reminderFeeAgreed)});for(const c of s.customers||[])map.set(c.customerNumber,c);return [...map.values()];}
function customers(){return isDemo?demoCustomers():privateCustomers;}
function stats(number){if(!isDemo)return {count:0,open:0};const list=(Demo.state().customerInvoices||[]).filter(i=>i.customerNumber===number);return {count:list.length,open:list.reduce((s,i)=>s+Math.max(0,Number(i.remainingOre||0)),0)};}
function money(v){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK'}).format(v/100);}
function addressText(c){return typeof c.address==='string'?c.address:(c.address?.full||'');}
function editCustomer(c){editing={...copy(c),address:addressText(c)};createRequestId='';message='';}
function requestedCustomer(){const number=new URLSearchParams(location.search).get('customer');return number?customers().find(c=>c.customerNumber===number)||null:null;}
function returnToInvoice(){return new URLSearchParams(location.search).get('return')==='invoice';}
function resumeInvoice(){location.href=url('./invoices.html?resume=1');}
function form(){const c=editing;const field=(label,key,type='text')=>`<label>${label}<input name="${key}" type="${type}" value="${esc(c[key]||'')}" maxlength="${key==='name'?160:254}" ${key==='name'?'required':''}></label>`;return `<section class="sales-panel"><h2>${c.customerNumber?'Redigera kund '+esc(c.customerNumber):'Ny kund'}</h2><form id="customer-form" class="sales-form">${field('Kundnamn *','name')}${field('Organisationsnummer','orgNumber')}${field('E-post','email','email')}<label class="full">Fakturaadress, postnummer och ort<textarea name="address" rows="3" maxlength="500">${esc(addressText(c))}</textarea></label><label>Påminnelseavgift avtalad<select name="reminderFeeAgreed"><option value="false" ${!c.reminderFeeAgreed?'selected':''}>Nej</option><option value="true" ${c.reminderFeeAgreed?'selected':''}>Ja</option></select></label><div class="full sales-actions"><button class="button" type="submit">Spara kund</button><button class="button ghost" type="button" data-cancel>Avbryt</button></div></form></section>`;}
function render(){const all=customers(),list=all.filter(c=>showArchived?Boolean(c.archivedAt):!c.archivedAt),activeCount=all.filter(c=>!c.archivedAt).length,archivedCount=all.filter(c=>c.archivedAt).length;app.innerHTML=`<div class="portal"><aside class="sidebar"></aside><section class="main"><header class="topbar"><div><h1>Kunder</h1><p>Register & verksamhet / Kundregister</p></div></header><main class="content sales-content">${isDemo?'<div class="demo-banner">Fiktiv demodata. Kunduppgifterna sparas i denna webbläsare.</div>':''}<div class="sales-head"><div><h2>Kundregister & faktureringsuppgifter</h2><p>${isDemo?'Demoregister i webbläsaren.':'Skyddat kundregister i företagets privata databas. Kunder med fakturahistorik arkiveras i stället för att raderas.'}</p></div><div class="sales-actions"><a class="button ghost" href="${url('./invoices.html')}">Kundfakturor</a><button class="button ghost" type="button" data-toggle-archived>${showArchived?'Visa aktiva':'Visa arkiverade'} (${showArchived?activeCount:archivedCount})</button><button class="button" data-new>+ Ny kund</button></div></div>${message?`<p class="notice" role="alert">${esc(message)}</p>`:''}${editing?form():`<section class="sales-grid"><article class="sales-metric"><span>${showArchived?'Arkiverade':'Aktiva kunder'}</span><strong>${list.length}</strong></article></section><section class="sales-panel"><div class="table-scroll"><table class="sales-table"><thead><tr><th>Kundnummer</th><th>Kund</th><th>Kontakt / adress</th><th>Historik</th><th>Åtgärd</th></tr></thead><tbody>${list.map(c=>`<tr><td>${esc(c.customerNumber)}</td><td><b>${esc(c.name)}</b><br>${esc(c.orgNumber||'')}${c.archivedAt?'<br><small>Arkiverad</small>':''}</td><td>${esc(c.email||'–')}<br>${esc(addressText(c))}</td><td>${Number(c.invoiceCount||0)} faktura${Number(c.invoiceCount||0)===1?'':'or'}</td><td><div class="sales-actions"><button class="button ghost small" type="button" data-edit-customer="${esc(c.id)}">Redigera</button>${c.archivedAt?`<button class="button ghost small" type="button" data-restore-customer="${esc(c.id)}">Återställ</button>`:`<button class="button ghost small" type="button" data-delete-customer="${esc(c.id)}">${Number(c.invoiceCount||0)>0?'Arkivera':'Ta bort'}</button>`}</div></td></tr>`).join('')||`<tr><td colspan="5">${showArchived?'Inga arkiverade kunder.':'Inga aktiva kunder ännu.'}</td></tr>`}</tbody></table></div></section>`}</main></section></div>`;}
async function loadPrivateCustomers(){const response=await fetch('/api/v1/customers?includeArchived=1',{credentials:'same-origin',cache:'no-store'});if(!response.ok)throw new Error((await response.json()).error||'Kundregistret kunde inte laddas.');privateCustomers=(await response.json()).customers||[];}
async function bootPrivate(){const sessionResponse=await fetch('/api/v1/session',{credentials:'same-origin',cache:'no-store'});const session=await sessionResponse.json();if(!session.authenticated){location.href='./index.html';return;}if(!csrfToken){location.href='./index.html';return;}await loadPrivateCustomers();const requested=requestedCustomer();if(requested)editCustomer(requested);render();}
document.addEventListener('click',async event=>{const edit=event.target.closest('[data-edit-customer]');if(edit){const customer=customers().find(c=>c.id===edit.dataset.editCustomer);if(customer){editCustomer(customer);render();}return;}if(event.target.closest('[data-toggle-archived]')){showArchived=!showArchived;message='';render();return;}const remove=event.target.closest('[data-delete-customer]');if(remove&&!isDemo){const customer=customers().find(c=>c.id===remove.dataset.deleteCustomer);if(!customer)return;const hasHistory=Number(customer.invoiceCount||0)>0;const ok=confirm(hasHistory?`Kunden har ${customer.invoiceCount} faktura/fakturor och kan därför inte raderas. Arkivera ${customer.customerNumber} i stället?`:`Ta bort ${customer.customerNumber} permanent? Kunden har ingen fakturahistorik.`);if(!ok)return;try{const response=await fetch('/api/v1/customers/'+encodeURIComponent(customer.id),{method:'DELETE',credentials:'same-origin',headers:{'X-CSRF-Token':csrfToken}}),data=await response.json();if(!response.ok)throw new Error(data.error||'Kunden kunde inte tas bort.');await loadPrivateCustomers();message=data.archived?`Kund ${customer.customerNumber} är arkiverad eftersom fakturahistorik finns kvar.`:`Kund ${customer.customerNumber} är borttagen.`;render();}catch(error){message=error.message;render();}return;}const restore=event.target.closest('[data-restore-customer]');if(restore&&!isDemo){try{const response=await fetch('/api/v1/customers/'+encodeURIComponent(restore.dataset.restoreCustomer)+'/restore',{method:'POST',credentials:'same-origin',headers:{'X-CSRF-Token':csrfToken}}),data=await response.json();if(!response.ok)throw new Error(data.error||'Kunden kunde inte återställas.');await loadPrivateCustomers();message=`Kund ${data.customer.customerNumber} är aktiv igen.`;render();}catch(error){message=error.message;render();}return;}if(event.target.closest('[data-new]')){editing={reminderFeeAgreed:false};createRequestId=crypto.randomUUID();message='';render();return;}if(event.target.closest('[data-cancel]')){if(returnToInvoice()){resumeInvoice();return;}editing=null;createRequestId='';message='';render();}});
document.addEventListener('submit',async event=>{if(event.target.id!=='customer-form')return;event.preventDefault();const fd=new FormData(event.target),payload={name:fd.get('name'),orgNumber:fd.get('orgNumber'),email:fd.get('email'),address:fd.get('address'),reminderFeeAgreed:fd.get('reminderFeeAgreed')==='true'};if(isDemo){const name=String(payload.name||'').trim();if(!name){message='Ange kundens namn.';render();return;}const existing=customers();if(editing?.customerNumber){const updated={...editing,...payload,name,address:String(payload.address||'')};Demo.patch(state=>{const stored=(state.customers||[]).filter(c=>c.customerNumber!==updated.customerNumber);state.customers=[...stored,updated];});editing=null;if(returnToInvoice()){resumeInvoice();return;}message=`Kund ${updated.customerNumber} är uppdaterad i demot.`;render();return;}const number='K-'+String(existing.reduce((n,c)=>Math.max(n,Number(String(c.customerNumber).replace(/\D/g,''))||0),1000)+1).padStart(4,'0'),customer={id:crypto.randomUUID(),customerNumber:number,...payload,name,type:'business',address:String(payload.address||'')};Demo.patch(state=>{state.customers=[...(state.customers||[]),customer];});editing=null;message='Kunden är sparad i demot.';render();return;}try{const updating=Boolean(editing?.id);if(!updating&&!createRequestId)createRequestId=crypto.randomUUID();const endpoint=updating?'/api/v1/customers/'+encodeURIComponent(editing.id):'/api/v1/customers',body=updating?payload:{...payload,requestId:createRequestId},response=await fetch(endpoint,{method:updating?'PUT':'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw new Error(data.error||'Kunden kunde inte sparas.');privateCustomers=updating?privateCustomers.map(c=>c.id===data.customer.id?data.customer:c):privateCustomers.some(c=>c.id===data.customer.id)?privateCustomers:[...privateCustomers,data.customer];editing=null;createRequestId='';if(updating&&returnToInvoice()){resumeInvoice();return;}message=`Kund ${data.customer.customerNumber} är ${updating?'uppdaterad':'sparad'} i den privata databasen.`;render();}catch(error){message=error.message;render();}});
if(isDemo){const requested=requestedCustomer();if(requested)editCustomer(requested);render();}else bootPrivate().catch(error=>{app.innerHTML=`<main class="content"><h1>Kunder</h1><p role="alert">${esc(error.message)}</p><a href="./index.html">Till säker inloggning</a></main>`;});
