const app=document.getElementById('customers-app');
const Demo=globalThis.RollandsDemoScenario;
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
let editing=null,message='',privateCustomers=[],csrfToken='';
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function url(path){return `${path}${isDemo?(path.includes('?')?'&':'?')+'demo=1':''}`;}
function demoCustomers(){const s=Demo.state(),map=new Map();for(const i of s.customerInvoices||[])if(!map.has(i.customerNumber))map.set(i.customerNumber,{id:'customer-'+i.customerNumber,customerNumber:i.customerNumber,name:i.customerName,paymentTermsDays:30,reminderFeeAgreed:Boolean(i.reminderFeeAgreed)});for(const c of s.customers||[])map.set(c.customerNumber,c);return [...map.values()];}
function customers(){return isDemo?demoCustomers():privateCustomers;}
function stats(number){if(!isDemo)return {count:0,open:0};const list=(Demo.state().customerInvoices||[]).filter(i=>i.customerNumber===number);return {count:list.length,open:list.reduce((s,i)=>s+Math.max(0,Number(i.remainingOre||0)),0)};}
function money(v){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK'}).format(v/100);}
function addressText(c){return typeof c.address==='string'?c.address:(c.address?.full||'');}
function form(){const c=editing;const field=(label,key,type='text')=>`<label>${label}<input name="${key}" type="${type}" value="${esc(c[key]||'')}" maxlength="${key==='name'?160:254}" ${key==='name'?'required':''}></label>`;return `<section class="sales-panel"><h2>${c.customerNumber?'Redigera kund '+esc(c.customerNumber):'Ny kund'}</h2><form id="customer-form" class="sales-form">${field('Kundnamn *','name')}${field('Organisationsnummer','orgNumber')}${field('E-post','email','email')}<label class="full">Fakturaadress, postnummer och ort<textarea name="address" rows="3" maxlength="500">${esc(addressText(c))}</textarea></label><label>Påminnelseavgift avtalad<select name="reminderFeeAgreed"><option value="false" ${!c.reminderFeeAgreed?'selected':''}>Nej</option><option value="true" ${c.reminderFeeAgreed?'selected':''}>Ja</option></select></label><div class="full sales-actions"><button class="button" type="submit">Spara kund</button><button class="button ghost" type="button" data-cancel>Avbryt</button></div></form></section>`;}
function render(){const list=customers();app.innerHTML=`<div class="portal"><aside class="sidebar"></aside><section class="main"><header class="topbar"><div><h1>Kunder</h1><p>Register & verksamhet / Kundregister</p></div></header><main class="content sales-content">${isDemo?'<div class="demo-banner">Fiktiv demodata. Kunduppgifterna sparas i denna webbläsare.</div>':''}<div class="sales-head"><div><h2>Kundregister & faktureringsuppgifter</h2><p>${isDemo?'Demoregister i webbläsaren.':'Skyddat kundregister i företagets privata databas.'}</p></div><div class="sales-actions"><a class="button ghost" href="${url('./invoices.html')}">Kundfakturor</a><button class="button" data-new>+ Ny kund</button></div></div>${message?`<p class="notice" role="alert">${esc(message)}</p>`:''}${editing?form():`<section class="sales-grid"><article class="sales-metric"><span>Kunder</span><strong>${list.length}</strong></article></section><section class="sales-panel"><div class="table-scroll"><table class="sales-table"><thead><tr><th>Kundnummer</th><th>Kund</th><th>Kontakt / adress</th><th>Påminnelseavgift</th></tr></thead><tbody>${list.map(c=>`<tr><td>${esc(c.customerNumber)}</td><td><b>${esc(c.name)}</b><br>${esc(c.orgNumber||'')}</td><td>${esc(c.email||'–')}<br>${esc(addressText(c))}</td><td>${c.reminderFeeAgreed?'Avtalad':'Inte avtalad'}</td></tr>`).join('')||'<tr><td colspan="4">Inga kunder ännu.</td></tr>'}</tbody></table></div></section>`}</main></section></div>`;}
async function bootPrivate(){const sessionResponse=await fetch('/api/v1/session',{credentials:'same-origin',cache:'no-store'});const session=await sessionResponse.json();if(!session.authenticated){location.href='./index.html';return;}csrfToken=session.csrfToken||'';const response=await fetch('/api/v1/customers',{credentials:'same-origin',cache:'no-store'});if(!response.ok)throw new Error((await response.json()).error||'Kundregistret kunde inte laddas.');privateCustomers=(await response.json()).customers||[];render();}
document.addEventListener('click',event=>{if(event.target.closest('[data-new]')){editing={reminderFeeAgreed:false};message='';render();}if(event.target.closest('[data-cancel]')){editing=null;message='';render();}});
document.addEventListener('submit',async event=>{if(event.target.id!=='customer-form')return;event.preventDefault();const fd=new FormData(event.target);if(isDemo){const name=String(fd.get('name')||'').trim();if(!name){message='Ange kundens namn.';render();return;}const existing=customers(),number='K-'+String(existing.reduce((n,c)=>Math.max(n,Number(String(c.customerNumber).replace(/\D/g,''))||0),1000)+1).padStart(4,'0');const c={id:crypto.randomUUID(),customerNumber:number,name,type:'business',reminderFeeAgreed:fd.get('reminderFeeAgreed')==='true',orgNumber:String(fd.get('orgNumber')||''),email:String(fd.get('email')||''),address:String(fd.get('address')||'')};Demo.patch(state=>{state.customers=[...existing,c];});editing=null;message='Kunden är sparad i demot.';render();return;}try{const response=await fetch('/api/v1/customers',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify({name:fd.get('name'),orgNumber:fd.get('orgNumber'),email:fd.get('email'),address:fd.get('address'),reminderFeeAgreed:fd.get('reminderFeeAgreed')==='true'})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Kunden kunde inte sparas.');privateCustomers.push(data.customer);editing=null;message=`Kund ${data.customer.customerNumber} är sparad i den privata databasen.`;render();}catch(error){message=error.message;render();}});
if(isDemo)render();else bootPrivate().catch(error=>{app.innerHTML=`<main class="content"><h1>Kunder</h1><p role="alert">${esc(error.message)}</p><a href="./index.html">Till säker inloggning</a></main>`;});
