const app=document.getElementById('dashboard-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const Demo=globalThis.RollandsDemoScenario;
const csrfToken=sessionStorage.getItem('rollands-csrf')||'';
let session=null;
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ore(v){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(v||0)/100)}
function today(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function url(path){return `${path}${isDemo?(path.includes('?')?'&':'?')+'demo=1':''}`}
async function api(path){const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',headers:{Accept:'application/json',...(csrfToken?{'X-CSRF-Token':csrfToken}:{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Begäran misslyckades.');return data}
function sidebar(){return `<aside class="sidebar"><div class="logo"><strong>${esc(isDemo?'Rollands':session?.company?.name||'Företaget')}</strong><small>LT STUDIO</small></div><div class="company-pill">${esc(session?.company?.name||(isDemo?'Rollands Frukt o Grönt AB':'Företaget'))}<br>${isDemo?'Demoföretag':'Skyddad företagsmiljö'}</div><div class="side-group"><span>Arbetsyta</span><a class="side-link active" href="${url('./dashboard.html')}">Översikt</a></div><div class="side-group"><span>Försäljning</span>${isDemo?`<a class="side-link" href="${url('./invoices.html')}">Kundfakturor</a><a class="side-link" href="${url('./customers.html')}">Kunder</a><a class="side-link" href="${url('./receivables.html')}">Kundreskontra</a>`:`<a class="side-link" href="./index.html">Kundreskontra</a>`}</div><div class="side-group"><span>Ekonomi</span><a class="side-link" href="${url('./bank.html')}">Bank & avstämning</a><a class="side-link" href="${url('./payables.html')}">Leverantörsfakturor</a><a class="side-link" href="${url('./suppliers.html')}">Leverantörer</a><a class="side-link" href="${url('./inventory.html')}">Lager</a><a class="side-link" href="${url('./accounting.html')}">Bokföring</a><a class="side-link" href="${url('./reports.html')}">Rapporter</a><a class="side-link" href="${url('./payroll.html')}">Lön</a><a class="side-link" href="${url('./documents.html')}">Dokument</a><a class="side-link" href="${url('./automation.html')}">Automationskö</a></div><div class="side-group"><span>Administration</span><a class="side-link" href="${url('./website.html')}">Webbplats & innehåll</a></div>${isDemo?'<div class="side-group"><span>Test & granskning</span><a class="side-link" href="./uat.html?demo=1">Testa systemet</a></div>':''}<div class="sidebar-footer">${isDemo?'Öppen demo med fiktiv data.':'Personlig session · servervaliderad behörighet'}</div></aside>`}
function demoMetrics(){const s=Demo.state();const invoices=s.customerInvoices||[];const open=invoices.filter(i=>Number(i.remainingOre)>0);const overdue=open.filter(i=>i.dueDate<today());const payables=s.supplierInvoices||[];const payments=s.supplierPayments||[];const proposals=(s.automationProposals||[]).filter(p=>!['approved','rejected','posted'].includes(p.status));const pendingSuppliers=(s.supplierPendingChanges||[]).filter(x=>x.status==='pending');const items=s.inventoryItems||[];const adjustments=(s.inventoryAdjustments||[]).filter(x=>x.status==='pending');const documents=s.documents||[];const entries=s.accountingEntries||[];const unlocks=(s.accountingUnlockRequests||[]).filter(x=>x.status==='pending');return {receivables:{openOre:open.reduce((n,i)=>n+Number(i.remainingOre||0),0),overdueOre:overdue.reduce((n,i)=>n+Number(i.remainingOre||0),0),openCount:open.length,overdueCount:overdue.length,totalCount:invoices.length},payables:{approvalCount:payables.filter(i=>i.status==='coded').length,paymentCount:payables.filter(i=>['approved','payment-prepared','released'].includes(i.status)).length,todayOre:payments.filter(p=>p.paymentDate===today()).reduce((n,p)=>n+Number(p.amountOre||0),0)},bank:{reviewCount:(s.bankPayments||[]).filter(p=>p.status==='unmatched').length},automation:{reviewCount:proposals.length},suppliers:{pendingCount:pendingSuppliers.length},inventory:{itemCount:items.length,pendingCount:adjustments.length},reports:{netVatOre:0},payroll:{validatedCount:(s.payrollRuns||[]).filter(r=>r.status==='validated').length,grossOre:Number((s.payrollRuns||[])[0]?.grossSalaryOre||0)},documents:{count:documents.length},accounting:{entryCount:entries.length,pendingUnlocks:unlocks.length},website:{version:Number(s.websiteCms?.published?.version||0)}}}
async function loadMetrics(){
  if(isDemo)return {...demoMetrics(),loadErrors:[]};
  const result={receivables:{openOre:0,overdueOre:0,openCount:0,overdueCount:0,totalCount:0},payables:{approvalCount:0,paymentCount:0,todayOre:0},bank:{reviewCount:0},automation:{reviewCount:0},suppliers:{pendingCount:0},inventory:{itemCount:0,pendingCount:0},reports:{netVatOre:0},payroll:{validatedCount:0,grossOre:0},documents:{count:0},accounting:{entryCount:0,pendingUnlocks:0},website:{version:0},loadErrors:[]};
  async function attempt(label,fn){try{await fn()}catch{result.loadErrors.push(label)}}
  await attempt('kundreskontra',async()=>{const inv=(await api('/receivables')).invoices||[];const open=inv.filter(i=>Number(i.remainingOre)>0);const overdue=open.filter(i=>i.dueDate<today());result.receivables.openOre=open.reduce((s,i)=>s+Math.max(0,Number(i.remainingOre||0)),0);result.receivables.overdueOre=overdue.reduce((s,i)=>s+Math.max(0,Number(i.remainingOre||0)),0);result.receivables.openCount=open.length;result.receivables.overdueCount=overdue.length;result.receivables.totalCount=inv.length});
  await attempt('leverantörsfakturor',async()=>{const inv=(await api('/payables/invoices')).invoices||[];result.payables.approvalCount=inv.filter(i=>i.status==='coded').length;result.payables.paymentCount=inv.filter(i=>['approved','payment-prepared'].includes(i.status)).length});
  await attempt('bank',async()=>{const rows=(await api('/bank/payments')).payments||[];result.bank.reviewCount=rows.filter(p=>p.status==='unmatched').length});
  await attempt('automation',async()=>{const rows=(await api('/automation/proposals')).proposals||[];result.automation.reviewCount=rows.filter(p=>!['approved','rejected','posted'].includes(p.status)).length});
  await attempt('leverantörsändringar',async()=>{result.suppliers.pendingCount=((await api('/suppliers/pending-changes')).changes||[]).length});
  await attempt('lager',async()=>{result.inventory.pendingCount=((await api('/inventory/adjustments?status=pending')).adjustments||[]).length});
  await attempt('periodupplåsningar',async()=>{result.accounting.pendingUnlocks=((await api('/accounting/unlock-requests?status=pending')).requests||[]).length});
  await attempt('dokument',async()=>{result.documents.count=((await api('/documents')).documents||[]).length});
  await attempt('bokföring',async()=>{result.accounting.entryCount=((await api('/accounting/entries?limit=1000')).entries||[]).length});
  return result
}(){if(isDemo)return demoMetrics();const result={receivables:{openOre:0,overdueOre:0,openCount:0,totalCount:0},payables:{approvalCount:0,paymentCount:0,todayOre:0},bank:{reviewCount:0},automation:{reviewCount:0},suppliers:{pendingCount:0},inventory:{itemCount:0,pendingCount:0},reports:{netVatOre:0},payroll:{validatedCount:0,grossOre:0},documents:{count:0},accounting:{entryCount:0,pendingUnlocks:0},website:{version:0}};try{const inv=(await api('/receivables/invoices')).invoices||[];result.receivables.openOre=inv.reduce((s,i)=>s+Math.max(0,Number(i.remainingOre||0)),0);result.receivables.openCount=inv.filter(i=>Number(i.remainingOre)>0).length;result.receivables.totalCount=inv.length}catch{}try{const inv=(await api('/payables/invoices')).invoices||[];result.payables.approvalCount=inv.filter(i=>i.status==='coded').length;result.payables.paymentCount=inv.filter(i=>['approved','payment-prepared'].includes(i.status)).length}catch{}try{result.documents.count=((await api('/documents')).documents||[]).length}catch{}try{result.accounting.entryCount=((await api('/accounting/entries?limit=1000')).entries||[]).length}catch{}return result}
function metric(label,value,sub=''){return `<article class="dash-metric"><span>${esc(label)}</span><strong>${value}</strong>${sub?`<small>${esc(sub)}</small>`:''}</article>`}
function moduleCard(title,text,href,badge){return `<a class="module-card ready" href="${url(href)}"><div><span class="module-state">Öppna område</span><h3>${esc(title)}</h3><p>${esc(text)}</p></div><strong>${esc(String(badge))}</strong></a>`}
function taskCard(title,text,href,count,priority='normal'){return `<a class="task-card ${esc(priority)}" href="${url(href)}"><div><span class="task-state">Behöver åtgärd</span><h3>${esc(title)}</h3><p>${esc(text)}</p></div><strong>${esc(String(count))}</strong></a>`}
function worklist(m){
  const tasks=[];
  if(Number(m.receivables.overdueCount)>0)tasks.push(taskCard('Förfallna kundfakturor',`${ore(m.receivables.overdueOre)} är förfallet och behöver följas upp.`,isDemo?'./receivables.html':'./index.html',m.receivables.overdueCount,'high'));
  if(Number(m.payables.approvalCount)>0)tasks.push(taskCard('Leverantörsfakturor väntar på attest','Granska underlag och kontering innan nästa steg.','./payables.html',m.payables.approvalCount,'high'));
  if(Number(m.payables.paymentCount)>0)tasks.push(taskCard('Leverantörsfakturor behöver betalningsåtgärd','Godkända eller betalningsförberedda fakturor behöver hanteras.','./payables.html',m.payables.paymentCount));
  if(Number(m.bank.reviewCount)>0)tasks.push(taskCard('Bankhändelser behöver matchas','Inbetalningar saknar färdig matchning mot rätt affärshändelse.','./bank.html',m.bank.reviewCount,'high'));
  if(Number(m.automation.reviewCount)>0)tasks.push(taskCard('Förslag väntar på granskning','Automationsförslag kräver mänsklig kontroll innan de går vidare.','./automation.html',m.automation.reviewCount));
  if(Number(m.suppliers.pendingCount)>0)tasks.push(taskCard('Leverantörsändringar väntar på kontroll','Ändringar i leverantörsdata behöver granskas där kontrollflödet kräver det.','./suppliers.html',m.suppliers.pendingCount));
  if(Number(m.inventory.pendingCount)>0)tasks.push(taskCard('Lagerjusteringar väntar på beslut','Inventerings- eller justeringsförslag behöver granskas.','./inventory.html',m.inventory.pendingCount));
  if(Number(m.accounting.pendingUnlocks)>0)tasks.push(taskCard('Periodupplåsningar väntar på beslut','Begärda upplåsningar av bokföringsperiod behöver hanteras.','./accounting.html',m.accounting.pendingUnlocks,'high'));
  const incomplete=m.loadErrors?.length?`<div class="notice warning"><b>Arbetslistan är ofullständig.</b> Kunde inte läsa: ${esc(m.loadErrors.join(', '))}. Nollvärden från dessa områden betyder inte att arbetet är klart.</div>`:'';
  const empty=!tasks.length&&!m.loadErrors?.length?'<div class="worklist-empty"><b>Inga kända väntande uppgifter i de kontrollerade köerna.</b><span>Detta är inte ett bokförings- eller pilotgodkännande.</span></div>':'';
  return `${incomplete}<section class="attention worklist"><div class="section-head"><div><span class="eyebrow">Arbetslista</span><h2>Vad behöver göras nu?</h2></div></div><div class="task-grid">${tasks.join('')||empty}</div></section>`
}
function modules(m){return `<section class="attention modules-secondary"><div class="section-head"><div><span class="eyebrow">Alla områden</span><h2>Öppna ett arbetsområde</h2></div></div><div class="module-grid">${isDemo?moduleCard('Kundfakturor','Skapa faktura och bokför kundfordran direkt i samma demo.','./invoices.html',m.receivables.totalCount):''}${isDemo?moduleCard('Kunder','Kundregister och faktureringsvillkor.','./customers.html','Register'):''}${moduleCard('Kundreskontra','Öppna och betalda kundfordringar samt betalningshistorik.',isDemo?'./receivables.html':'./index.html',m.receivables.openCount)}${moduleCard('Bank & avstämning','Matcha inbetalningar och följ betalningsflöden.','./bank.html',m.bank.reviewCount)}${moduleCard('Automationskö','Granska regel- och automationsförslag innan nästa steg.','./automation.html',m.automation.reviewCount)}${moduleCard('Leverantörsfakturor','Registrering, kontering, attest och betalning.','./payables.html',m.payables.approvalCount+m.payables.paymentCount)}${moduleCard('Leverantörer','Masterdata och kontrollerade ändringar av betalningsuppgifter.','./suppliers.html',m.suppliers.pendingCount)}${moduleCard('Bokföring','Verifikationer, periodlås och spårbara rättelser.','./accounting.html',m.accounting.entryCount)}${moduleCard('Lager','Artiklar, saldo, svinn, inventering och justeringar.','./inventory.html',m.inventory.pendingCount||m.inventory.itemCount)}${moduleCard('Rapporter','Ekonomisk uppföljning från gemensamma bokföringsposter.','./reports.html','Öppna')}${moduleCard('Lön','Import, validering och lönejournal.','./payroll.html',m.payroll.validatedCount)}${moduleCard('Dokument','Originalunderlag och koppling till affärshändelser.','./documents.html',m.documents.count)}${moduleCard('Webbplats & innehåll','Redigera och förhandsgranska den publika webbplatsen.','./website.html',m.website.version?`v${m.website.version}`:'CMS')}</div></section>`}
function render(m){
  app.innerHTML=`<div class="dash-shell">${sidebar()}<section class="dash-main"><header class="topbar"><div><h1>Arbetslista</h1><p>${today()} · företagets arbetsdag</p></div><div class="user-chip"><b>${esc(session?.user?.displayName||'Demoanvändare')}</b></div></header><main class="content">${isDemo?'<div class="demo-banner"><b>Demo v1 är sammanhängande.</b> Kundfakturering, kundreskontra, bank, automation, bokföring och leverantörsflödet använder gemensam demodata.</div>':''}<section class="dash-hero"><div><span class="eyebrow">Dagens arbete</span><h2>Det som behöver uppmärksamhet först</h2><p>Arbetslistan bygger på de privata köerna i systemet. Öppna uppgiften direkt härifrån i stället för att leta efter rätt modul.</p>${isDemo?'<p><a class="button" href="./uat.html?demo=1">Starta testguiden</a></p>':''}</div><div class="hero-date">${today()}</div></section><section class="dash-metrics">${metric('Öppet kundsaldo',ore(m.receivables.openOre),`${m.receivables.openCount} öppna av ${m.receivables.totalCount} fakturor`)}${metric('Förfallet kundsaldo',ore(m.receivables.overdueOre),`${m.receivables.overdueCount||0} fakturor`)}${metric('Leverantörsåtgärder',m.payables.approvalCount+m.payables.paymentCount,'attest eller betalning')}${metric('Bank att matcha',m.bank.reviewCount,'inbetalningar behöver åtgärd')}</section>${worklist(m)}${modules(m)}</main></section></div>`
}
async function load(){if(isDemo){session={user:{displayName:'Demoanvändare'},company:{name:'Rollands Frukt o Grönt AB'}};render(await loadMetrics());return}const s=await api('/session');if(!s.authenticated){location.href='./index.html';return}session=s;render(await loadMetrics())}
load().catch(error=>{app.innerHTML=`<main class="boot"><strong>Översikten kunde inte laddas</strong><span>${esc(error.message)}</span></main>`});
