const app=document.getElementById('documents-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const csrfToken=sessionStorage.getItem('rollands-csrf')||'';
const Demo=globalThis.RollandsDemoScenario;
let session=null,documents=[],category='all',query='',message='',documentSearchOpen=false,documentSearchActiveIndex=-1;
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function url(path){return `${path}${isDemo?'?demo=1':''}`}
function size(bytes){const value=Number(bytes||0);return value<1024?`${value} B`:value<1024*1024?`${(value/1024).toFixed(1)} kB`:`${(value/1024/1024).toFixed(1)} MB`}
function date(value){try{return new Intl.DateTimeFormat('sv-SE',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Stockholm'}).format(new Date(value))}catch{return value}}
async function api(path,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.method&&options.method!=='GET'&&csrfToken?{'X-CSRF-Token':csrfToken}:{})};const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',...options,headers,body:options.body?JSON.stringify(options.body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Begäran misslyckades.');return data}
function sidebar(){return `<aside class="sidebar documents-nav"><div class="logo"><strong>${esc(isDemo?'Rollands':session?.company?.name||'Företaget')}</strong><small>LT STUDIO</small></div><div class="company-pill">${esc(session?.company?.name||(isDemo?'Rollands Frukt o Grönt AB':'Företaget'))}<br>${isDemo?'Demoföretag':'Skyddad företagsmiljö'}</div><div class="side-group"><span>Arbetsyta</span><a class="side-link" href="${url('./dashboard.html')}">Översikt</a></div><div class="side-group"><span>Ekonomi</span><a class="side-link" href="${url('./payables.html')}">Leverantörsfakturor</a><a class="side-link" href="${url('./accounting.html')}">Bokföring</a><a class="side-link active" href="${url('./documents.html')}">Dokument</a></div><div class="sidebar-footer">Originalunderlag är oföränderliga efter uppladdning.</div></aside>`}
function documentMatches(d,needle){const q=String(needle||'').trim().toLocaleLowerCase('sv-SE');if(!q)return true;return [d.title,d.fileName,d.category,...(d.links||[]).flatMap(l=>[l.entityType,l.entityId,l.label])].some(v=>String(v||'').toLocaleLowerCase('sv-SE').includes(q))}
function visibleDocs(){return documents.filter(d=>(category==='all'||d.category===category)&&documentMatches(d,query))}
function documentSearchSuggestions(){return query?visibleDocs().slice(0,8):[]}
function documentSearchResults(){const rows=documentSearchSuggestions();if(!rows.length)return '<div class="shared-search-empty">Inga dokument matchar sökningen.</div>';return rows.map((d,index)=>`<button type="button" class="shared-search-option ${index===documentSearchActiveIndex?'active':''}" role="option" aria-selected="${index===documentSearchActiveIndex?'true':'false'}" data-document-search-id="${esc(d.id)}"><span><b>${esc(d.title)}</b><small>${esc(d.fileName)} · ${esc(categoryLabel(d.category))}</small></span><strong>${size(d.sizeBytes)}</strong></button>`).join('')}
function closeDocumentSearch(){documentSearchOpen=false;documentSearchActiveIndex=-1;const field=document.querySelector('[data-filter="query"]'),results=document.getElementById('documents-search-results');field?.setAttribute('aria-expanded','false');if(results)results.hidden=true}
function categoryLabel(v){return ({'supplier-invoice':'Leverantörsfaktura',receipt:'Kvitto',bank:'Bank',accounting:'Bokföring',inventory:'Lager',other:'Övrigt'})[v]||v}
function render(){const rows=visibleDocs();app.innerHTML=`<div class="documents-shell">${sidebar()}<section class="documents-main"><header class="topbar"><div><h1>Dokument</h1><p>Originalunderlag · kontrollsumma · affärskoppling</p></div><div class="user-chip"><b>${esc(session?.user?.displayName||'Demo Dokument')}</b></div></header><main class="content">${isDemo?'<div class="demo-banner"><b>Gemensamt UAT-scenario.</b> Dokumentens kopplingar använder samma interna id som Leverantörsfakturor och Bokföring.</div>':''}${message?`<div class="notice">${esc(message)}</div>`:''}<div class="notice documents-note"><b>Spårbarhet:</b> ett original med kontrollsumma ersätts inte. En korrigerad version registreras som ett nytt dokument.</div><section class="documents-toolbar"><div class="documents-filters"><select data-filter="category"><option value="all">Alla kategorier</option>${['supplier-invoice','receipt','bank','accounting','inventory','other'].map(v=>`<option value="${v}" ${category===v?'selected':''}>${categoryLabel(v)}</option>`).join('')}</select><div class="shared-search-shell documents-search-shell"><input type="search" role="combobox" aria-autocomplete="list" aria-controls="documents-search-results" aria-expanded="${documentSearchOpen&&query?'true':'false'}" autocomplete="off" data-filter="query" value="${esc(query)}" placeholder="Sök titel, fil eller koppling"><div id="documents-search-results" class="shared-search-results" role="listbox" ${documentSearchOpen&&query?'':'hidden'}>${documentSearchOpen&&query?documentSearchResults():''}</div></div></div><button class="button" data-action="upload">Lägg till dokument</button></section><section class="documents-panel"><div class="documents-head"><div><span class="eyebrow">Arkiv</span><h2>${rows.length} dokument</h2></div><strong>${documents.length} totalt</strong></div><div class="documents-table-wrap"><table class="documents-table"><thead><tr><th>Kategori</th><th>Dokument</th><th>Koppling</th><th>Storlek</th><th>SHA-256</th><th>Registrerat</th><th></th></tr></thead><tbody>${rows.map(d=>`<tr data-document-id="${esc(d.id)}"><td><span class="doc-category">${esc(categoryLabel(d.category))}</span></td><td><b>${esc(d.title)}</b><small>${esc(d.fileName)} · ${esc(d.mimeType)}</small></td><td>${(d.links||[]).map(l=>`${esc(l.label||l.entityType)}<small>${esc(l.entityType)} · ${esc(l.entityId)}</small>`).join('<br>')||'—'}</td><td>${size(d.sizeBytes)}</td><td class="doc-sha" title="${esc(d.sha256||'')}">${esc((d.sha256||'').slice(0,12))}${d.sha256?'…':''}</td><td>${date(d.createdAt)}</td><td>${isDemo?'<span>Demo</span>':`<a class="button ghost small" href="/api/v1/documents/${encodeURIComponent(d.id)}/content" target="_blank" rel="noopener">Ladda ner</a>`}</td></tr>`).join('')||'<tr><td colspan="7" class="documents-empty">Inga dokument matchar filtret.</td></tr>'}</tbody></table></div></section></main></section></div>`}
function modal(){const requestId=crypto.randomUUID();document.body.insertAdjacentHTML('beforeend',`<div class="documents-modal-backdrop" data-close><section class="documents-modal"><header><div><span class="eyebrow">Nytt original</span><h2>Lägg till dokument</h2></div><button class="documents-close" type="button" data-close>×</button></header><form id="document-upload" data-request-id="${esc(requestId)}"><div class="two"><label>Titel<input name="title" required maxlength="180"></label><label>Kategori<select name="category"><option value="supplier-invoice">Leverantörsfaktura</option><option value="receipt">Kvitto</option><option value="bank">Bank</option><option value="accounting">Bokföring</option><option value="inventory">Lager</option><option value="other">Övrigt</option></select></label></div><label>Fil<input type="file" name="file" accept="application/pdf,.pdf" required><small>Endast PDF · max 10 MB</small></label><div class="two"><label>Kopplingstyp<input name="entityType" placeholder="t.ex. supplier-invoice"></label><label>Kopplings-id<input name="entityId" placeholder="internt id"></label></div><label>Kommentar<textarea name="note" rows="3" maxlength="1000"></textarea></label><div class="notice"><b>Originalprincip:</b> efter uppladdning kan filen inte bytas ut.</div><footer><button class="button ghost" type="button" data-close>Avbryt</button><button class="button" type="submit">Ladda upp</button></footer></form></section></div>`)}
async function upload(form){const fd=new FormData(form),file=fd.get('file');if(!(file instanceof File)||!file.size)throw new Error('Välj en fil.');if(file.size>10*1024*1024)throw new Error('PDF-filen får vara högst 10 MB.');const mime=file.type||({'pdf':'application/pdf'})[file.name.split('.').pop().toLowerCase()]||'';if(!/\.pdf$/i.test(file.name)||mime!=='application/pdf')throw new Error('Endast PDF-filer stöds.');const meta={requestId:String(form.dataset.requestId||''),title:String(fd.get('title')||''),category:String(fd.get('category')||'other'),fileName:file.name,mimeType:mime,note:String(fd.get('note')||''),entityType:String(fd.get('entityType')||''),entityId:String(fd.get('entityId')||'')};if(isDemo){const created={id:`doc-demo-${Date.now()}`,...meta,sha256:`demo-${Date.now().toString(16)}`,sizeBytes:file.size,uploadedBy:'demo-user',createdAt:new Date().toISOString(),links:meta.entityType&&meta.entityId?[{entityType:meta.entityType,entityId:meta.entityId,label:''}]:[]};Demo.patch(state=>state.documents.unshift(created));documents=Demo.section('documents');message='Dokumentmetadata sparades i det gemensamma demoscenariot. Filinnehållet sparades inte.';return}const created=(await api('/documents',{method:'POST',body:meta})).document;const r=await fetch(`/api/v1/documents/${encodeURIComponent(created.id)}/content`,{method:'PUT',credentials:'same-origin',headers:{'Content-Type':mime,'X-CSRF-Token':csrfToken},body:file});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Dokumentet registrerades men filinnehållet kunde inte sparas.');documents=(await api('/documents')).documents||[];message='Dokumentet sparades och fick en kontrollsumma.'}
document.addEventListener('change',e=>{if(e.target.dataset.filter==='category'){category=e.target.value;documentSearchActiveIndex=-1;render()}});
document.addEventListener('input',e=>{if(e.target.dataset.filter==='query'){query=e.target.value;documentSearchOpen=Boolean(query.trim());documentSearchActiveIndex=-1;render();requestAnimationFrame(()=>{const field=document.querySelector('[data-filter="query"]');field?.focus();field?.setSelectionRange?.(query.length,query.length)})}});
document.addEventListener('focusin',e=>{if(e.target.dataset.filter==='query'&&query.trim()){documentSearchOpen=true;const results=document.getElementById('documents-search-results');if(results){results.hidden=false;results.innerHTML=documentSearchResults()}e.target.setAttribute('aria-expanded','true')}});
document.addEventListener('keydown',e=>{if(e.target.dataset.filter!=='query')return;const rows=documentSearchSuggestions();if(e.key==='Escape'){closeDocumentSearch();return}if(!rows.length)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const step=e.key==='ArrowDown'?1:-1;documentSearchActiveIndex=(documentSearchActiveIndex+step+rows.length)%rows.length;documentSearchOpen=true;render();requestAnimationFrame(()=>document.querySelector('[data-filter="query"]')?.focus());return}if(e.key==='Enter'&&documentSearchOpen){e.preventDefault();const choice=rows[Math.max(0,documentSearchActiveIndex)];if(choice){query=choice.title||choice.fileName||'';documentSearchOpen=false;documentSearchActiveIndex=-1;render()}}});
document.addEventListener('click',e=>{const suggestion=e.target.closest('[data-document-search-id]');if(suggestion){const choice=documents.find(d=>d.id===suggestion.dataset.documentSearchId);if(choice){query=choice.title||choice.fileName||'';documentSearchOpen=false;documentSearchActiveIndex=-1;render()}return}if(!e.target.closest('.documents-search-shell')&&documentSearchOpen)closeDocumentSearch()if(e.target.closest('[data-action="upload"]'))modal();const backdrop=document.querySelector('.documents-modal-backdrop');if(!backdrop)return;const closeButton=e.target.closest('button[data-close]');if(closeButton||e.target===backdrop)backdrop.remove()});document.addEventListener('submit',async e=>{if(e.target.id!=='document-upload')return;e.preventDefault();const button=e.target.querySelector('[type="submit"]');button.disabled=true;try{await upload(e.target);document.querySelector('.documents-modal-backdrop')?.remove();render()}catch(err){message=err.message;button.disabled=false;render()}});
async function load(){if(isDemo){if(!Demo)throw new Error('Det gemensamma demoscenariot kunde inte laddas.');session={user:{displayName:'Demo Dokument'},company:{name:'Rollands Frukt o Grönt AB'}};documents=Demo.section('documents');render();return}const s=await api('/session');if(!s.authenticated){location.href='./index.html';return}session=s;documents=(await api('/documents')).documents||[];render()}
load().catch(err=>{app.innerHTML=`<main class="boot"><strong>Dokumentarkivet kunde inte laddas</strong><span>${esc(err.message)}</span></main>`});
