const app=document.getElementById('payables-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const csrfToken=sessionStorage.getItem('rollands-csrf')||'';
let session=null;
let invoices=[];
let selected=null;
let payments=[];
let message='';
let suggestionMeta=null;

const demoInvoices=[{id:'sinv-demo-1',supplierName:'Grön Grossist AB',supplierNumber:'L-100',supplierInvoiceNumber:'GG-4401',invoiceDate:'2026-09-10',dueDate:'2026-09-16',totalOre:125000,vatOre:25000,currency:'SEK',status:'coded',registeredBy:'demo-registrar',approvedBy:null,hasDocument:true,coding:[{account:'4010',debitOre:100000,creditOre:0,text:'Varuinköp',vatCode:'INPUT_VAT'},{account:'2641',debitOre:25000,creditOre:0,text:'Ingående moms',vatCode:'INPUT_VAT'},{account:'2440',debitOre:0,creditOre:125000,text:'Leverantörsskuld',vatCode:''}]}];
let demoPayments=[{id:'spay-demo-1',paymentDate:today(),supplierName:'Göteborg Fruktlager AB',supplierInvoiceNumber:'GF-8821',amountOre:84600,status:'prepared',preparedBy:'demo-accountant'}];

function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ore(v){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(v||0)/100)}
function today(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function statusLabel(v){return ({registered:'Registrerad','coding-review':'Kontering granskas',coded:'Konterad',approved:'Attesterad','payment-prepared':'Betalning förberedd',prepared:'Förberedd',released:'Frisläppt – ej skickad',paid:'Betald',cancelled:'Avbruten',rejected:'Avvisad'})[v]||v}
async function api(path,options={}){const headers={'Accept':'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};if(options.method&&options.method!=='GET'&&csrfToken)headers['X-CSRF-Token']=csrfToken;const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',...options,headers,body:options.body?JSON.stringify(options.body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Begäran misslyckades.');return data}

function makePdfBlob(){const body=['BT','/F1 18 Tf','50 790 Td','(Leverantorsfaktura GG-4401) Tj','0 -36 Td','/F1 11 Tf','(Grön Grossist AB) Tj','0 -22 Td','(Fakturadatum: 2026-09-10) Tj','0 -18 Td','(Forfallodatum: 2026-09-16) Tj','0 -30 Td','(Varuinkop 1000.00 SEK) Tj','0 -18 Td','(Moms 25% 250.00 SEK) Tj','0 -18 Td','(Att betala 1250.00 SEK) Tj','ET'].join('\n');const objects=[null,'<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>',`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>`,`<< /Length ${body.length} >>\nstream\n${body}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];let pdf='%PDF-1.4\n',offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return URL.createObjectURL(new Blob([pdf],{type:'application/pdf'}))}
function sidebar(){return `<aside class="sidebar payables-nav"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">${isDemo?'Rollands Frukt o Grönt AB':'Skyddad företagsmiljö'}<br>${isDemo?'Demoföretag':'Personlig session'}</div><div class="side-group"><span>Försäljning</span><a class="side-link" href="./index.html${isDemo?'?demo=1':''}">Kundreskontra</a></div><div class="side-group"><span>Ekonomi</span><a class="side-link" href="./bank.html${isDemo?'?demo=1':''}">Bank & avstämning</a><a class="side-link active" href="./payables.html${isDemo?'?demo=1':''}">Leverantörsfakturor</a><a class="side-link" href="./automation.html${isDemo?'?demo=1':''}">Automationskö</a></div><div class="sidebar-footer">PDF och kontering granskas tillsammans före attest.</div></aside>`}
function codingRows(invoice){return (invoice.coding||[]).map((line,index)=>`<tr><td><input data-line="${index}" data-field="account" value="${esc(line.account)}" ${['approved','payment-prepared','paid'].includes(invoice.status)?'disabled':''}></td><td><input data-line="${index}" data-field="text" value="${esc(line.text||'')}" ${['approved','payment-prepared','paid'].includes(invoice.status)?'disabled':''}></td><td><input class="amount" data-line="${index}" data-field="debitOre" value="${line.debitOre?String((line.debitOre/100).toFixed(2)).replace('.',','):''}" ${['approved','payment-prepared','paid'].includes(invoice.status)?'disabled':''}></td><td><input class="amount" data-line="${index}" data-field="creditOre" value="${line.creditOre?String((line.creditOre/100).toFixed(2)).replace('.',','):''}" ${['approved','payment-prepared','paid'].includes(invoice.status)?'disabled':''}></td></tr>`).join('')}
function paymentSummary(){const list=payments.filter(p=>p.paymentDate===today());const total=list.reduce((s,p)=>s+p.amountOre,0);const prepared=list.filter(p=>p.status==='prepared').reduce((s,p)=>s+p.amountOre,0);const released=list.filter(p=>p.status==='released').reduce((s,p)=>s+p.amountOre,0);const paid=list.filter(p=>p.status==='paid').reduce((s,p)=>s+p.amountOre,0);return `<section class="payments-panel"><div class="panel-head"><div><span class="eyebrow">${today()}</span><h3>Dagens utbetalningar</h3></div><strong>${list.length} betalningar</strong></div><div class="payment-summary"><article><span>Totalt</span><strong>${ore(total)}</strong></article><article><span>Förberedda</span><strong>${ore(prepared)}</strong></article><article><span>Frisläppta</span><strong>${ore(released)}</strong></article><article><span>Betalda</span><strong>${ore(paid)}</strong></article></div><div class="notice payment-note"><b>Viktigt:</b> Frisläppt betyder att en andra behörig person har godkänt betalningen för nästa steg. Pengarna är inte skickade till banken och betalningen är inte bokförd som genomförd förrän ett senare bank-/avstämningssteg bekräftar det.</div><div class="payment-list">${list.map(p=>`<div class="payment-row"><b>${esc(p.supplierName)}</b><span>${esc(p.supplierInvoiceNumber)}</span><span class="payment-status ${esc(p.status)}">${esc(statusLabel(p.status))}</span><strong class="money">${ore(p.amountOre)}</strong><div class="payment-action">${p.status==='prepared'?`<button class="button small" data-action="release-payment" data-payment-id="${esc(p.id)}">Frisläpp</button>`:'—'}</div></div>`).join('')||'<p class="empty">Inga utbetalningar planerade idag.</p>'}</div></section>`}
function suggestionBox(){if(!suggestionMeta)return `<div class="ai-box"><strong>Automatiskt konteringsförslag</strong>Hämta ett förslag baserat på leverantörens tidigare godkända konteringar och standardkonto. Förslaget är alltid redigerbart innan attest.</div>`;return `<div class="ai-box"><strong>Förslag: ${Math.round(Number(suggestionMeta.confidence||0)*100)} % säkerhet</strong>${esc(suggestionMeta.reason||'')}<br><small>${suggestionMeta.ambiguous?'Tvetydigt underlag – kontrollera extra noga.':'Underlaget har en tydlig huvudträff.'}</small></div>`}
function workspace(){if(!selected)return '<div class="panel"><p class="empty">Ingen leverantörsfaktura vald.</p></div>';const pdfSrc=isDemo?makePdfBlob():`/api/v1/payables/invoices/${encodeURIComponent(selected.id)}/document`;const locked=['approved','payment-prepared','paid'].includes(selected.status);return `<div class="payables-grid"><section class="pdf-panel"><div class="panel-head"><div><span class="eyebrow">Underlag</span><h3>Faktura ${esc(selected.supplierInvoiceNumber)}</h3></div><span class="status-pill ${esc(selected.status)}">${esc(statusLabel(selected.status))}</span></div><div class="invoice-meta"><div><span>Leverantör</span><strong>${esc(selected.supplierName)}</strong></div><div><span>Förfallodatum</span><strong>${esc(selected.dueDate)}</strong></div><div><span>Total</span><strong>${ore(selected.totalOre)}</strong></div><div><span>Moms</span><strong>${ore(selected.vatOre)}</strong></div></div><embed class="pdf-frame" type="application/pdf" src="${esc(pdfSrc)}"></section><section class="coding-panel"><div class="panel-head"><div><span class="eyebrow">Konteringsmodul</span><h3>Föreslagen kontering</h3></div>${!locked?'<button class="button ghost small" data-action="suggest-coding">Hämta konteringsförslag</button>':''}</div>${suggestionBox()}<table class="coding-table"><thead><tr><th>Konto</th><th>Text</th><th>Debet</th><th>Kredit</th></tr></thead><tbody>${codingRows(selected)}</tbody></table><div class="totals"><span>Fakturabelopp</span><strong>${ore(selected.totalOre)}</strong><span>Moms</span><strong>${ore(selected.vatOre)}</strong></div><div class="coding-actions">${!locked?'<button class="button ghost" data-action="save-coding">Spara kontering</button><button class="button" data-action="approve">Attestera faktura</button>':''}${selected.status==='approved'?'<button class="button" data-action="prepare-payment">Förbered betalning idag</button>':''}${selected.status==='payment-prepared'?'<span class="notice">Betalningen är förberedd och syns i dagens utbetalningar.</span>':''}</div></section></div>`}
function render(){app.innerHTML=`<div class="payables-shell">${sidebar()}<section class="payables-main"><header class="topbar"><div><h1>Leverantörsfakturor</h1><p>PDF · kontering · attest · betalning</p></div><div class="user-chip"><b>${esc(session?.user?.displayName||'Demoanvändare')}</b></div></header><main class="content">${isDemo?'<div class="demo-banner"><b>GitHub Pages-demo.</b> PDF och betalningar är exempeldata.</div>':''}${message?`<div class="notice">${esc(message)}</div>`:''}<div class="page-heading"><div><span class="eyebrow">Attestflöde</span><h2>Granska faktura och kontering tillsammans</h2><p>PDF-underlaget visas samtidigt som konteringen. Automatiska förslag går att ändra före attest och låses först efter godkännandet.</p></div></div>${workspace()}${paymentSummary()}</main></section></div>`}
function readCoding(){return [...document.querySelectorAll('[data-line][data-field="account"]')].map((_,i)=>{const value=f=>document.querySelector(`[data-line="${i}"][data-field="${f}"]`)?.value||'';const parse=v=>{const n=Number(String(v).replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)?Math.round(n*100):0};return{account:value('account'),text:value('text'),debitOre:parse(value('debitOre')),creditOre:parse(value('creditOre')),vatCode:''}})}
async function load(){if(isDemo){session={user:{displayName:'Demoattestant'}};invoices=structuredClone(demoInvoices);selected=invoices[0];payments=structuredClone(demoPayments);render();return}const s=await api('/session');if(!s.authenticated){location.href='./index.html';return}session=s;const invoiceData=await api('/payables/invoices');invoices=invoiceData.invoices||[];selected=invoices[0]?(await api(`/payables/invoices/${invoices[0].id}`)).invoice:null;payments=(await api(`/payables/payments?date=${today()}`)).payments||[];render()}
async function suggestCoding(){if(isDemo){selected.coding=[{account:'4010',debitOre:selected.totalOre-selected.vatOre,creditOre:0,text:`Leverantörsfaktura ${selected.supplierInvoiceNumber}`,vatCode:'INPUT_VAT'},{account:'2641',debitOre:selected.vatOre,creditOre:0,text:'Ingående moms',vatCode:'INPUT_VAT'},{account:'2440',debitOre:0,creditOre:selected.totalOre,text:'Leverantörsskuld',vatCode:''}];suggestionMeta={confidence:.96,reason:'Tre tidigare attesterade fakturor från leverantören har bokats på konto 4010.',ambiguous:false};message='Förslaget är inläst. Ändra valfri rad innan du sparar eller attesterar.';return}const data=await api(`/payables/invoices/${selected.id}/coding-suggestion`,{method:'POST',body:{}});selected={...selected,coding:data.coding};suggestionMeta=data.proposal;message='Konteringsförslaget är inläst men ännu inte sparat. Kontrollera och ändra vid behov.'}
async function releasePayment(paymentId){if(isDemo){const payment=payments.find(item=>item.id===paymentId);if(!payment)throw new Error('Demobetalningen hittades inte.');if(payment.status!=='prepared')throw new Error('Endast förberedda betalningar kan frisläppas.');payment.status='released';payment.releasedBy='demo-approver';payment.releasedAt=new Date().toISOString();message='Betalningen är frisläppt i demon. Den är fortfarande inte skickad till banken eller bokförd som betald.';return}const data=await api(`/payables/payments/${encodeURIComponent(paymentId)}/release`,{method:'POST',body:{}});message=data.message||'Betalningen frisläpptes men har inte skickats till banken.';payments=(await api(`/payables/payments?date=${today()}`)).payments||[]}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;try{if(b.dataset.action==='release-payment'){await releasePayment(b.dataset.paymentId);render();return}if(!selected)return;if(b.dataset.action==='suggest-coding')await suggestCoding();if(b.dataset.action==='save-coding'){const lines=readCoding();if(isDemo){selected.coding=lines;selected.status='coded';message='Konteringen sparades i demon.'}else selected=(await api(`/payables/invoices/${selected.id}/coding`,{method:'PUT',body:{lines}})).invoice}if(b.dataset.action==='approve'){const lines=readCoding();if(isDemo){selected.coding=lines;selected.status='approved';selected.approvedBy='demo-approver';message='Fakturan attesterades i demon. Konteringen är nu låst.'}else{await api(`/payables/invoices/${selected.id}/coding`,{method:'PUT',body:{lines}});selected=(await api(`/payables/invoices/${selected.id}/approve`,{method:'POST',body:{}})).invoice}}if(b.dataset.action==='prepare-payment'){if(isDemo){selected.status='payment-prepared';demoPayments.push({id:`spay-${Date.now()}`,paymentDate:today(),supplierName:selected.supplierName,supplierInvoiceNumber:selected.supplierInvoiceNumber,amountOre:selected.totalOre,status:'prepared',preparedBy:'demo-accountant'});payments=demoPayments;message='Betalningen är förberedd och tillagd i dagens utbetalningar.'}else{await api(`/payables/invoices/${selected.id}/prepare-payment`,{method:'POST',body:{paymentDate:today(),account:'1930'}});selected=(await api(`/payables/invoices/${selected.id}`)).invoice;payments=(await api(`/payables/payments?date=${today()}`)).payments||[]}}render()}catch(error){message=error.message;render()}});
load().catch(error=>{app.innerHTML=`<main class="boot"><strong>Kunde inte ladda leverantörsfakturor</strong><span>${esc(error.message)}</span></main>`});
