const app=document.getElementById('payments-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
let session=null,mode='month',anchor=today(),direction='',status='',query='',account='',sort='date',order='asc',data=null,message='';
function today(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ore(v){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(v||0)/100)}
async function api(path){const r=await fetch('/api/v1'+path,{credentials:'same-origin',headers:{Accept:'application/json'}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Begäran misslyckades.');return body}
function demo(){return{period:{mode,from:'2026-09-01',to:'2026-09-30',label:'2026-09'},filters:{direction:null,status:null},summary:{incomingOre:627500,outgoingOre:209600,netOre:417900,count:4},rows:[
{id:'demo-in-1',direction:'in',paymentDate:'2026-09-10',amountOre:392500,status:'posted',reference:'BG-1041',counterparty:'Nordic Office Göteborg AB',counterpartyAccount:'',invoiceNumber:'310002'},
{id:'demo-in-2',direction:'in',paymentDate:'2026-09-12',amountOre:235000,status:'posted',reference:'BG-1042',counterparty:'Majorna Fastigheter AB',counterpartyAccount:'',invoiceNumber:'310004'},
{id:'demo-out-1',direction:'out',paymentDate:'2026-09-14',amountOre:84600,status:'paid',reference:'987-6543',counterparty:'Göteborgs Fruktimport AB',counterpartyAccount:'987-6543',invoiceNumber:'GF-8821'},
{id:'demo-out-2',direction:'out',paymentDate:'2026-09-18',amountOre:125000,status:'prepared',reference:'555-2200',counterparty:'Lokal Grossist AB',counterpartyAccount:'555-2200',invoiceNumber:'LG-1020'}]}}
function sidebar(){return '<aside class="sidebar"></aside>'}
function toolbar(){return `<section class="report-toolbar"><label>Period<select data-field="mode"><option value="day" ${mode==='day'?'selected':''}>Dag</option><option value="week" ${mode==='week'?'selected':''}>Vecka</option><option value="month" ${mode==='month'?'selected':''}>Månad</option><option value="quarter" ${mode==='quarter'?'selected':''}>Kvartal</option></select></label><label>Datum<input type="date" data-field="anchor" value="${esc(anchor)}"></label><label>Riktning<select data-field="direction"><option value="">Alla</option><option value="in" ${direction==='in'?'selected':''}>Inbetalningar</option><option value="out" ${direction==='out'?'selected':''}>Utbetalningar</option></select></label><label>Status<input data-field="status" value="${esc(status)}" placeholder="Alla statusar"></label><label>Sök<input data-field="query" value="${esc(query)}" placeholder="Motpart, faktura, referens"></label><label>Konto<input data-field="account" value="${esc(account)}" inputmode="numeric" maxlength="4" placeholder="t.ex. 1930"></label><label>Sortera<select data-field="sort"><option value="date" ${sort==='date'?'selected':''}>Datum</option><option value="amount" ${sort==='amount'?'selected':''}>Belopp</option><option value="counterparty" ${sort==='counterparty'?'selected':''}>Motpart</option></select></label><label>Ordning<select data-field="order"><option value="asc" ${order==='asc'?'selected':''}>Stigande</option><option value="desc" ${order==='desc'?'selected':''}>Fallande</option></select></label><button class="button" data-action="reload">Uppdatera</button></section>`}
function summary(){if(!data)return'';return `<section class="report-summary"><article><span>Inbetalningar</span><strong>${ore(data.summary.incomingOre)}</strong></article><article><span>Utbetalningar</span><strong>${ore(data.summary.outgoingOre)}</strong></article><article><span>Netto</span><strong>${ore(data.summary.netOre)}</strong></article><article><span>Betalningar</span><strong>${data.summary.count}</strong></article></section>`}
function table(){if(!data)return'<div class="report-empty">Laddar…</div>';return `<section class="report-panel"><div class="report-head"><div><span class="eyebrow">${esc(data.period.label)}</span><h2>In- och utbetalningar</h2><p>${esc(data.period.from)} – ${esc(data.period.to)}</p></div></div><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Datum</th><th>Typ</th><th>Motpart</th><th>Faktura</th><th>Status</th><th>Referens</th><th>Belopp</th></tr></thead><tbody>${data.rows.map(r=>`<tr><td>${esc(r.paymentDate)}</td><td>${r.direction==='in'?'Inbetalning':'Utbetalning'}</td><td>${esc(r.counterparty||'—')}</td><td>${esc(r.invoiceNumber||'—')}</td><td>${esc(r.status||'—')}</td><td>${esc(r.reference||'—')}</td><td class="money">${r.direction==='out'?'-':''}${ore(r.amountOre)}</td></tr>`).join('')||'<tr><td colspan="7" class="report-empty">Inga betalningar i vald period.</td></tr>'}</tbody></table></div></section>`}
function render(){app.innerHTML=`<div class="reports-shell">${sidebar()}<section class="reports-main"><header class="topbar"><div><h1>Betalningar</h1><p>Inbetalningar · utbetalningar · periodfilter</p></div><div class="user-chip"><b>${esc(session?.user?.displayName||'Demoanvändare')}</b></div></header><main class="content">${isDemo?'<div class="demo-banner"><b>GitHub Pages-demo.</b> Betalningarna är fiktiva.</div>':''}${message?`<div class="notice">${esc(message)}</div>`:''}${toolbar()}${summary()}${table()}</main></section></div>`;globalThis.RollandsNavigation?.mount?.()}
async function loadData(){data=isDemo?demo():await api(`/reports/payments-overview?mode=${encodeURIComponent(mode)}&date=${encodeURIComponent(anchor)}&direction=${encodeURIComponent(direction)}&status=${encodeURIComponent(status)}&query=${encodeURIComponent(query)}&account=${encodeURIComponent(account)}&sort=${encodeURIComponent(sort)}&order=${encodeURIComponent(order)}`);render()}
function syncFields(){
  const value=name=>document.querySelector(`[data-field="${name}"]`)?.value??'';
  mode=value('mode')||mode;anchor=value('anchor')||anchor;direction=value('direction');status=value('status');query=value('query');account=value('account');sort=value('sort')||'date';order=value('order')||'asc';
}
document.addEventListener('change',e=>{if(e.target.dataset.field)syncFields()});
document.addEventListener('click',e=>{if(e.target.closest('[data-action="reload"]')){syncFields();loadData().catch(err=>{message=err.message;render()})}});
async function load(){if(isDemo){session={user:{displayName:'Demo Ekonomi'}};return loadData()}const s=await api('/session');if(!s.authenticated){location.href='./index.html';return}session=s;await loadData()}
load().catch(err=>{app.innerHTML=`<main class="boot"><strong>Betalningsöversikten kunde inte laddas</strong><span>${esc(err.message)}</span></main>`});
