const app=document.getElementById('payroll-app');
const isDemo=new URLSearchParams(location.search).get('demo')==='1';
const isSupabase=location.hostname==='ludwigberglund-coder.github.io'&&!isDemo;
const csrfToken=sessionStorage.getItem('rollands-csrf')||'';
let session=null,runs=[],message='',supabaseCtx=null;
async function supabaseContext(){supabaseCtx=supabaseCtx?.authenticated?supabaseCtx:await window.LTSupabaseUat.context();if(!supabaseCtx?.authenticated||!supabaseCtx.company){location.href='./index.html';throw new Error('Ingen aktiv Supabase-session.')}return supabaseCtx}
function mapPayrollRun(r,batch){return{id:r.id,companyId:r.company_id,period:r.period,payDate:r.pay_date,sourceName:r.source_name,grossSalaryOre:Number(r.gross_salary_ore||0),withheldTaxOre:Number(r.withheld_tax_ore||0),employerContributionsOre:Number(r.employer_contributions_ore||0),netPayOre:Number(r.net_pay_ore||0),vacationLiabilityChangeOre:Number(r.vacation_liability_change_ore||0),lines:r.lines_json||[],journalSha256:r.journal_sha256,status:r.status,importedBy:r.imported_by,importedAt:r.imported_at,postedBy:r.posted_by,postedAt:r.posted_at,accountingEntryId:r.accounting_entry_id,accountingBatchId:r.accounting_batch_id||'',accountingBatchNumber:batch?.batch_number||null,accountingBatchStatus:batch?.status||''}}
async function loadSupabasePayroll(){const ctx=await supabaseContext(),filter='company_id=eq.'+encodeURIComponent(ctx.company.id),[rows,batchRows]=await Promise.all([window.LTSupabase.from('payroll_runs',ctx.accessToken).select('*',filter+'&order=period.desc,imported_at.desc'),window.LTSupabase.from('financial_batches',ctx.accessToken).select('*',filter)]),batches=new Map((batchRows||[]).map(b=>[String(b.id),b]));runs=(rows||[]).map(r=>mapPayrollRun(r,batches.get(String(r.accounting_batch_id))));session={user:ctx.user,company:ctx.company}}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ore(v){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(v||0)/100)}
function parseOre(v){const raw=String(v??'').trim().replace(/\s/g,'').replace(',','.');if(!/^-?\d+(?:\.\d{1,2})?$/.test(raw))throw new Error('Belopp måste anges med högst två decimaler.');const sign=raw.startsWith('-')?-1:1;const [whole,dec='']=raw.replace('-','').split('.');const value=sign*(Number(whole)*100+Number((dec+'00').slice(0,2)));if(!Number.isSafeInteger(value))throw new Error('Beloppet är för stort.');return value}
function url(path){return `${path}${isDemo?'?demo=1':''}`}
async function api(path,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.method&&options.method!=='GET'&&csrfToken?{'X-CSRF-Token':csrfToken}:{})};const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',...options,headers,body:options.body?JSON.stringify(options.body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Begäran misslyckades.');return data}
const demoRun={id:'payroll-demo-2026-09',period:'2026-09',payDate:'2026-09-25',sourceName:'Extern lön september',grossSalaryOre:3000000,withheldTaxOre:900000,employerContributionsOre:942600,netPayOre:2100000,vacationLiabilityChangeOre:240000,status:'validated',journalSha256:'demo',lines:[{account:'7010',text:'Bruttolön',debitOre:3000000,creditOre:0},{account:'7510',text:'Arbetsgivaravgifter',debitOre:942600,creditOre:0},{account:'2920',text:'Semesterlöneskuld förändring',debitOre:240000,creditOre:0},{account:'2710',text:'Personalskatt',debitOre:0,creditOre:900000},{account:'2731',text:'Arbetsgivaravgifter skuld',debitOre:0,creditOre:942600},{account:'2910',text:'Upplupna löner',debitOre:0,creditOre:2100000},{account:'2920',text:'Semesterlöneskuld',debitOre:0,creditOre:240000}]};
function sidebar(){return `<aside class="sidebar payroll-nav"><div class="logo"><strong>${esc(isDemo?'Rollands':session?.company?.name||'Företaget')}</strong><small>LT STUDIO</small></div><div class="company-pill">${esc(session?.company?.name||(isDemo?'Rollands Frukt o Grönt AB':'Företaget'))}<br>${isDemo?'Demoföretag':'Skyddad företagsmiljö'}</div><div class="side-group"><span>Arbetsyta</span><a class="side-link" href="${url('./dashboard.html')}">Översikt</a></div><div class="side-group"><span>Ekonomi</span><a class="side-link" href="${url('./payables.html')}">Leverantörsfakturor</a><a class="side-link" href="${url('./inventory.html')}">Lager</a><a class="side-link" href="${url('./reports.html')}">Rapporter</a><a class="side-link active" href="${url('./payroll.html')}">Lön</a><a class="side-link" href="${url('./automation.html')}">Automationskö</a></div><div class="sidebar-footer">Endast aggregerad lönejournal visas här. Inga individuppgifter i publik demo.</div></aside>`}
function status(v,batchId=''){return batchId?'Väntar bunt':v==='posted'?'Bokförd':v==='validated'?'Validerad':'Avvisad'}
function summary(){const latest=runs[0];return `<section class="payroll-summary"><article><span>Senaste period</span><strong>${esc(latest?.period||'—')}</strong></article><article><span>Bruttolön</span><strong>${ore(latest?.grossSalaryOre)}</strong></article><article><span>Arbetsgivaravgifter</span><strong>${ore(latest?.employerContributionsOre)}</strong></article><article><span>Status</span><strong>${esc(latest?status(latest.status,latest.accountingBatchId):'—')}</strong></article></section>`}
function runList(){return `<section class="payroll-panel"><div class="payroll-head"><div><span class="eyebrow">Lönekörningar</span><h2>Aggregerade lönejournaler</h2></div></div><div style="overflow:auto"><table class="payroll-table"><thead><tr><th>Period</th><th>Källa</th><th>Utbetalningsdatum</th><th>Bruttolön</th><th>Nettolön</th><th>Status</th><th></th></tr></thead><tbody>${runs.map(r=>`<tr><td><b>${esc(r.period)}</b></td><td>${esc(r.sourceName)}</td><td>${esc(r.payDate)}</td><td class="money">${ore(r.grossSalaryOre)}</td><td class="money">${ore(r.netPayOre)}</td><td><span class="payroll-status ${esc(r.status)}">${esc(status(r.status,r.accountingBatchId))}</span></td><td>${r.status==='validated'&&r.accountingBatchId?`<span>Väntar bunt #${esc(String(r.accountingBatchNumber||'').padStart(5,'0'))}</span>`:r.status==='validated'?`<button class="button small" data-action="post" data-id="${esc(r.id)}">Skapa bunt</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Inga lönejournaler importerade.</td></tr>'}</tbody></table></div></section>`}
function lines(run){return `<section class="payroll-panel"><div class="payroll-head"><div><span class="eyebrow">Kontering</span><h3>${esc(run?.period||'Ingen journal')}</h3></div></div>${run?`<div style="overflow:auto"><table class="payroll-table"><thead><tr><th>Konto</th><th>Text</th><th>Debet</th><th>Kredit</th></tr></thead><tbody>${run.lines.map(l=>`<tr><td><b>${esc(l.account)}</b></td><td>${esc(l.text)}</td><td class="money">${l.debitOre?ore(l.debitOre):'—'}</td><td class="money">${l.creditOre?ore(l.creditOre):'—'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty">Ingen journal vald.</p>'}<div class="notice payroll-note"><b>Integritet:</b> journalen går efter validering via Buntar. Huvudboken påverkas först när bunten godkänns. En låst bokföringsperiod stoppar bokföringen. Den publika demon innehåller inga anställdas namn, personnummer eller individuella löner.</div></section>`}
function importPanel(){return `<section class="payroll-panel"><div class="payroll-head"><div><span class="eyebrow">Import</span><h3>Ny aggregerad lönejournal</h3></div></div><form class="payroll-form" id="payroll-import"><div class="payroll-grid"><label>Period<input type="month" name="period" value="2026-09" required></label><label>Utbetalningsdatum<input type="date" name="payDate" value="2026-09-25" required></label><label>Källa<input name="sourceName" value="Extern lön september" required></label><label>Bruttolön<input name="gross" value="30000,00" inputmode="decimal" required></label><label>Preliminär skatt<input name="tax" value="9000,00" inputmode="decimal" required></label><label>Arbetsgivaravgifter<input name="employer" value="9426,00" inputmode="decimal" required></label><label>Nettolön<input name="net" value="21000,00" inputmode="decimal" required></label><label>Semesterlöneskuld förändring<input name="vacation" value="2400,00" inputmode="decimal" required></label></div><div class="notice"><b>Demoformat:</b> konteringsraderna nedan skapas av importmallen. Senare kan en löneleverantör lämna samma struktur via integration.</div><div class="payroll-actions"><button class="button" type="submit">Importera & validera</button></div></form></section>`}
function render(){const latest=runs[0];app.innerHTML=`<div class="payroll-shell">${sidebar()}<section class="payroll-main"><header class="topbar"><div><h1>Lön</h1><p>Import · kontroll · lönejournal · bokföring</p></div><div class="user-chip"><b>${esc(session?.user?.displayName||'Demo Lön')}</b></div></header><main class="content">${isDemo?'<div class="demo-banner"><b>GitHub Pages-demo.</b> Endast fiktiva, aggregerade lönebelopp visas.</div>':''}${message?`<div class="notice">${esc(message)}</div>`:''}${summary()}${runList()}${lines(latest)}${importPanel()}</main></section></div>`}
function buildInput(form){const d=new FormData(form);const gross=parseOre(d.get('gross')),tax=parseOre(d.get('tax')),employer=parseOre(d.get('employer')),net=parseOre(d.get('net')),vacation=parseOre(d.get('vacation'));return{period:String(d.get('period')),payDate:String(d.get('payDate')),sourceName:String(d.get('sourceName')),grossSalaryOre:gross,withheldTaxOre:tax,employerContributionsOre:employer,netPayOre:net,vacationLiabilityChangeOre:vacation,lines:[{account:'7010',text:'Bruttolön',debitOre:gross,creditOre:0},{account:'7510',text:'Arbetsgivaravgifter',debitOre:employer,creditOre:0},{account:'2920',text:'Semesterlöneskuld förändring',debitOre:vacation,creditOre:0},{account:'2710',text:'Personalskatt',debitOre:0,creditOre:tax},{account:'2731',text:'Arbetsgivaravgifter skuld',debitOre:0,creditOre:employer},{account:'2910',text:'Upplupna löner',debitOre:0,creditOre:net},{account:'2920',text:'Semesterlöneskuld',debitOre:0,creditOre:vacation},{account:'7090',text:'Lönedifferens kontroll',debitOre:0,creditOre:Math.max(0,gross-tax-net)}].filter(l=>l.debitOre||l.creditOre)}}
async function load(){if(isDemo){session={user:{displayName:'Demo Lön'},company:{name:'Rollands Frukt o Grönt AB'}};runs=[structuredClone(demoRun)];render();return}if(isSupabase){await loadSupabasePayroll();render();return}const s=await api('/session');if(!s.authenticated){location.href='./index.html';return}session=s;runs=(await api('/payroll/runs')).runs||[];render()}
document.addEventListener('submit',async e=>{if(e.target.id!=='payroll-import')return;e.preventDefault();try{const input=buildInput(e.target);if(isDemo){const next={...input,id:`payroll-demo-${Date.now()}`,status:'validated',journalSha256:'demo',lines:input.lines};runs.unshift(next);message='Lönejournalen importerades och validerades i demon.'}else if(isSupabase){const ctx=await supabaseContext(),result=(await window.LTSupabase.rpc('import_payroll_run',{p_company_id:ctx.company.id,p_period:input.period,p_pay_date:input.payDate,p_source_name:input.sourceName,p_gross_salary_ore:input.grossSalaryOre,p_withheld_tax_ore:input.withheldTaxOre,p_employer_contributions_ore:input.employerContributionsOre,p_net_pay_ore:input.netPayOre,p_vacation_liability_change_ore:input.vacationLiabilityChangeOre,p_lines:input.lines},ctx.accessToken))?.[0];if(!result)throw new Error('Lönejournalen kunde inte importeras i Supabase.');await loadSupabasePayroll();message=result.duplicate?'Samma lönejournal fanns redan och återanvändes.':'Lönejournalen importerades och validerades i Supabase.'}else{const data=await api('/payroll/runs',{method:'POST',body:input});runs.unshift(data.run);message='Lönejournalen importerades och validerades.'}render()}catch(err){message=err.message;render()}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action="post"]');if(!b)return;try{if(isDemo){const run=runs.find(r=>r.id===b.dataset.id);if(run)run.status='posted';message='Lönejournalen bokfördes i demon i serie L.'}else if(isSupabase){const ctx=await supabaseContext(),result=(await window.LTSupabase.rpc('post_payroll_run',{p_company_id:ctx.company.id,p_payroll_run_id:b.dataset.id},ctx.accessToken))?.[0];if(!result)throw new Error('Lönejournalen kunde inte bokföras i Supabase.');await loadSupabasePayroll();const run=runs.find(row=>row.id===b.dataset.id);message=run?.accountingBatchId?`Lönejournalen väntar i bunt #${String(run.accountingBatchNumber||'').padStart(5,'0')}. Huvudboken påverkas först när bunten godkänns.`:(result.duplicate?'Lönejournalen var redan bokförd. ':'Lönejournalen bokfördes. ')+'Verifikation '+result.journal_number+'.'}else{await api(`/payroll/runs/${encodeURIComponent(b.dataset.id)}/post`,{method:'POST',body:{}});runs=(await api('/payroll/runs')).runs||[];message='Lönejournalen bokfördes.'}render()}catch(err){message=err.message;render()}});
load().catch(err=>{app.innerHTML=`<main class="boot"><strong>Lön kunde inte laddas</strong><span>${esc(err.message)}</span></main>`});
