const app=document.getElementById('reports-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const Demo=globalThis.RollandsDemoScenario;
let session=null,reportType='trial',fromDate='2026-09-01',toDate='2026-09-30',period='2026-09',report=null,message='';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ore(v){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(v||0)/100)}
function url(path){return `${path}${isDemo?'?demo=1':''}`}
async function api(path){const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',headers:{Accept:'application/json'}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Begäran misslyckades.');return data}
function sidebar(){return `<aside class="sidebar"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">${esc(session?.company?.name||'Rollands Frukt o Grönt AB')}</div></aside>`}
function sharedEntries(){return Demo?.section('accountingEntries')||[]}
function demoTrial(){const map=new Map();for(const entry of sharedEntries()){for(const line of entry.lines||[]){if(!map.has(line.account))map.set(line.account,{account:line.account,openingOre:0,debitOre:0,creditOre:0,closingOre:0});const row=map.get(line.account),delta=Number(line.debitOre||0)-Number(line.creditOre||0);if(entry.postingDate<fromDate)row.openingOre+=delta;else if(entry.postingDate<=toDate){row.debitOre+=Number(line.debitOre||0);row.creditOre+=Number(line.creditOre||0)}}}const rows=[...map.values()].map(r=>({...r,closingOre:r.openingOre+r.debitOre-r.creditOre})).filter(r=>r.openingOre||r.debitOre||r.creditOre).sort((a,b)=>a.account.localeCompare(b.account)),totals={debitOre:rows.reduce((s,r)=>s+r.debitOre,0),creditOre:rows.reduce((s,r)=>s+r.creditOre,0)};return{rows,totals}}
function demoLedger(){const rows=[];for(const entry of sharedEntries().filter(e=>e.postingDate>=fromDate&&e.postingDate<=toDate).sort((a,b)=>a.postingDate.localeCompare(b.postingDate)||String(a.number).localeCompare(String(b.number))))for(const line of entry.lines||[])rows.push({postingDate:entry.postingDate,number:entry.number,account:line.account,description:entry.description,lineText:line.text,debitOre:line.debitOre,creditOre:line.creditOre});return{rows}}
function demoPl(){const map=new Map();for(const entry of sharedEntries().filter(e=>e.postingDate>=fromDate&&e.postingDate<=toDate))for(const line of entry.lines||[])if(/^[3-8]/.test(line.account)){const current=map.get(line.account)||0;map.set(line.account,current+Number(line.creditOre||0)-Number(line.debitOre||0))}const rows=[...map.entries()].map(([account,amountOre])=>({account,amountOre})).sort((a,b)=>a.account.localeCompare(b.account));return{rows,resultOre:rows.reduce((s,r)=>s+r.amountOre,0)}}
function demoVat(){const state=Demo.state(),start=`${period}-01`,end=`${period}-31`;let output=0,input=0;for(const entry of state.accountingEntries||[]){if(entry.postingDate<start||entry.postingDate>end)continue;for(const line of entry.lines||[]){if(/^26[123][0-9]$/.test(line.account))output+=Number(line.creditOre||0)-Number(line.debitOre||0);if(line.account==='2641')input+=Number(line.debitOre||0)-Number(line.creditOre||0)}}const customers=(state.customerInvoices||[]).filter(i=>i.invoiceDate?.startsWith(period)),suppliers=(state.supplierInvoices||[]).filter(i=>i.invoiceDate?.startsWith(period));return{outputVatOre:output,inputVatOre:input,netVatOre:output-input,customerInvoiceCount:customers.length,supplierInvoiceCount:suppliers.length,customerGrossOre:customers.reduce((s,i)=>s+Number(i.totalOre||0),0),supplierGrossOre:suppliers.reduce((s,i)=>s+Number(i.totalOre||0),0),declarationReady:false,warning:'Avstämningen räknas från de gemensamma demo-verifikationerna. Innan en verklig momsdeklaration lämnas måste momskoder och bokföring verifieras mot företagets skarpa data.'}}
function demoReport(){if(reportType==='trial')return demoTrial();if(reportType==='ledger')return demoLedger();if(reportType==='pl')return demoPl();return demoVat()}
async function loadReport(){if(isDemo){if(!Demo)throw new Error('Det gemensamma demoscenariot kunde inte laddas.');report=demoReport();render();return}if(reportType==='trial')report=await api(`/reports/trial-balance?from=${fromDate}&to=${toDate}`);else if(reportType==='ledger')report=await api(`/reports/general-ledger?from=${fromDate}&to=${toDate}`);else if(reportType==='pl')report=await api(`/reports/profit-loss?from=${fromDate}&to=${toDate}`);else report=await api(`/reports/vat-control?period=${period}`);render()}
function toolbar(){return `<section class="report-toolbar"><label>Från<input type="date" data-field="from" value="${esc(fromDate)}" ${reportType==='vat'?'disabled':''}></label><label>Till<input type="date" data-field="to" value="${esc(toDate)}" ${reportType==='vat'?'disabled':''}></label><label>Momsperiod<input type="month" data-field="period" value="${esc(period)}" ${reportType!=='vat'?'disabled':''}></label><button class="button" data-action="reload">Uppdatera</button><div class="report-tabs"><button class="report-tab ${reportType==='trial'?'active':''}" data-report="trial">Balanslista</button><button class="report-tab ${reportType==='ledger'?'active':''}" data-report="ledger">Huvudbok</button><button class="report-tab ${reportType==='pl'?'active':''}" data-report="pl">Resultat</button><button class="report-tab ${reportType==='vat'?'active':''}" data-report="vat">Momsavstämning</button></div></section>`}
function summary(){if(!report)return'';if(reportType==='trial')return `<section class="report-summary"><article><span>Debet perioden</span><strong>${ore(report.totals?.debitOre)}</strong></article><article><span>Kredit perioden</span><strong>${ore(report.totals?.creditOre)}</strong></article><article><span>Antal konton</span><strong>${report.rows?.length||0}</strong></article><article><span>Kontroll</span><strong>${report.totals?.debitOre===report.totals?.creditOre?'Balanserar':'Avvikelse'}</strong></article></section>`;if(reportType==='pl')return `<section class="report-summary"><article><span>Periodens resultat</span><strong>${ore(report.resultOre)}</strong></article><article><span>Resultatkonton</span><strong>${report.rows?.length||0}</strong></article></section>`;if(reportType==='vat')return `<section class="report-summary"><article><span>Utgående moms</span><strong>${ore(report.outputVatOre)}</strong></article><article><span>Ingående moms</span><strong>${ore(report.inputVatOre)}</strong></article><article><span>Netto moms</span><strong>${ore(report.netVatOre)}</strong></article><article><span>Status</span><strong>Avstämning</strong></article></section>`;return `<section class="report-summary"><article><span>Rader</span><strong>${report.rows?.length||0}</strong></article><article><span>Period</span><strong>${esc(fromDate)} – ${esc(toDate)}</strong></article></section>`}
function content(){if(!report)return'<div class="report-empty">Laddar rapport…</div>';if(reportType==='trial')return `<section class="report-panel"><div class="report-head"><div><span class="eyebrow">Bokföring</span><h2>Balanslista</h2></div></div><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Konto</th><th>Ingående</th><th>Debet</th><th>Kredit</th><th>Utgående</th></tr></thead><tbody>${report.rows.map(r=>`<tr><td class="account">${esc(r.account)}</td><td class="money">${ore(r.openingOre)}</td><td class="money">${ore(r.debitOre)}</td><td class="money">${ore(r.creditOre)}</td><td class="money">${ore(r.closingOre)}</td></tr>`).join('')}</tbody></table></div></section>`;if(reportType==='ledger')return `<section class="report-panel"><div class="report-head"><div><span class="eyebrow">Bokföring</span><h2>Huvudbok</h2></div></div><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Datum</th><th>Ver.nr</th><th>Konto</th><th>Beskrivning</th><th>Debet</th><th>Kredit</th></tr></thead><tbody>${report.rows.map(r=>`<tr><td>${esc(r.postingDate)}</td><td>${esc(r.number)}</td><td class="account">${esc(r.account)}</td><td>${esc(r.description)}<br><small>${esc(r.lineText||'')}</small></td><td class="money">${r.debitOre?ore(r.debitOre):'—'}</td><td class="money">${r.creditOre?ore(r.creditOre):'—'}</td></tr>`).join('')||'<tr><td colspan="6" class="report-empty">Inga verifikationer i perioden.</td></tr>'}</tbody></table></div></section>`;if(reportType==='pl')return `<section class="report-panel"><div class="report-head"><div><span class="eyebrow">Resultat</span><h2>Resultatrapport</h2></div><strong>${ore(report.resultOre)}</strong></div><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Konto</th><th>Periodbelopp</th></tr></thead><tbody>${report.rows.map(r=>`<tr><td class="account">${esc(r.account)}</td><td class="money">${ore(r.amountOre)}</td></tr>`).join('')}</tbody></table></div></section>`;return `<section class="vat-panel"><div class="report-head"><div><span class="eyebrow">${esc(period)}</span><h2>Momsavstämning</h2></div><strong>${ore(report.netVatOre)}</strong></div><div class="vat-grid"><article><span>Utgående moms</span><strong>${ore(report.outputVatOre)}</strong><small>${report.customerInvoiceCount} kundfakturor</small></article><article><span>Ingående moms</span><strong>${ore(report.inputVatOre)}</strong><small>${report.supplierInvoiceCount} leverantörsfakturor</small></article><article><span>Netto</span><strong>${ore(report.netVatOre)}</strong></article></div><div class="notice warning vat-warning"><b>Kontrollunderlag – inte färdig momsdeklaration.</b> ${esc(report.warning||'')}</div></section>`}
function render(){app.innerHTML=`<div class="reports-shell">${sidebar()}<section class="reports-main"><header class="topbar"><div><h1>Rapporter</h1><p>Bokföring · huvudbok · resultat · moms</p></div><div class="user-chip"><b>${esc(session?.user?.displayName||'Demoanvändare')}</b></div></header><main class="content">${isDemo?'<div class="demo-banner"><b>Gemensamt UAT-scenario.</b> Demo-rapporterna räknas från samma bokföringsposter som Bokföring visar.</div>':''}${message?`<div class="notice">${esc(message)}</div>`:''}${toolbar()}${summary()}${content()}</main></section></div>`}
document.addEventListener('change',e=>{if(e.target.dataset.field==='from')fromDate=e.target.value;if(e.target.dataset.field==='to')toDate=e.target.value;if(e.target.dataset.field==='period')period=e.target.value});document.addEventListener('click',e=>{const tab=e.target.closest('[data-report]');if(tab){reportType=tab.dataset.report;report=null;loadReport().catch(err=>{message=err.message;render()});return}if(e.target.closest('[data-action="reload"]')){report=null;loadReport().catch(err=>{message=err.message;render()})}});
async function load(){if(isDemo){session={user:{displayName:'Demo Ekonomi'},company:{name:'Rollands Frukt o Grönt AB'}};return loadReport()}const s=await api('/session');if(!s.authenticated){location.href='./index.html';return}session=s;await loadReport()}
load().catch(err=>{app.innerHTML=`<main class="boot"><strong>Rapporter kunde inte laddas</strong><span>${esc(err.message)}</span></main>`});
