const app=document.getElementById('supplier-ledger-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
let session=null,suppliers=[],invoices=[],query='',statusFilter='all',selectedSupplierId='all';
const Demo=globalThis.RollandsDemoScenario;

function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ore(v){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(v||0)/100)}
function today(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function url(path){return `${path}${isDemo?'?demo=1':''}`}
async function api(path){const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',headers:{Accept:'application/json'}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Begäran misslyckades.');return data}
function normalized(v){return String(v||'').toLocaleLowerCase('sv-SE').replace(/\s+/g,' ').trim()}
function invoiceOpen(invoice){return !['paid','rejected'].includes(invoice.status)}
function invoiceOverdue(invoice){return invoiceOpen(invoice)&&invoice.dueDate<today()}
function statusLabel(v){return ({registered:'Registrerad','coding-review':'Kontering granskas',coded:'Väntar attest',approved:'Attesterad','payment-prepared':'Betalning förberedd',paid:'Betald',rejected:'Avvisad'})[v]||v}
function supplierFor(invoice){return suppliers.find(s=>s.id===invoice.supplierId)||{id:invoice.supplierId,name:invoice.supplierName||'Okänd leverantör',supplierNumber:invoice.supplierNumber||'',orgNumber:''}}
function matches(invoice){const supplier=supplierFor(invoice),needle=normalized(query);if(selectedSupplierId!=='all'&&supplier.id!==selectedSupplierId)return false;if(statusFilter==='open'&&!invoiceOpen(invoice))return false;if(statusFilter==='overdue'&&!invoiceOverdue(invoice))return false;if(statusFilter==='paid'&&invoice.status!=='paid')return false;if(!needle)return true;return [supplier.name,supplier.supplierNumber,supplier.orgNumber,invoice.supplierInvoiceNumber,invoice.status].some(v=>normalized(v).includes(needle))}
function supplierSummary(supplier){const rows=invoices.filter(i=>i.supplierId===supplier.id),open=rows.filter(invoiceOpen),overdue=open.filter(invoiceOverdue);return{count:rows.length,openCount:open.length,openOre:open.reduce((sum,i)=>sum+Number(i.totalOre||0),0),overdueOre:overdue.reduce((sum,i)=>sum+Number(i.totalOre||0),0),paidOre:rows.filter(i=>i.status==='paid').reduce((sum,i)=>sum+Number(i.totalOre||0),0)}}
function totals(){const rows=invoices.filter(matches);return{count:rows.length,openOre:rows.filter(invoiceOpen).reduce((s,i)=>s+Number(i.totalOre||0),0),overdueOre:rows.filter(invoiceOverdue).reduce((s,i)=>s+Number(i.totalOre||0),0),paidOre:rows.filter(i=>i.status==='paid').reduce((s,i)=>s+Number(i.totalOre||0),0)}}
function sidebar(){return `<aside class="sidebar"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">${esc(session?.company?.name||'Rollands Frukt o Grönt AB')}</div></aside>`}
function supplierCards(){const list=suppliers.filter(s=>{const needle=normalized(query);if(!needle)return true;return [s.name,s.supplierNumber,s.orgNumber].some(v=>normalized(v).includes(needle))||invoices.some(i=>i.supplierId===s.id&&normalized(i.supplierInvoiceNumber).includes(needle))});return `<div class="supplier-ledger-list"><button class="supplier-ledger-card ${selectedSupplierId==='all'?'active':''}" data-supplier="all"><span><b>Alla leverantörer</b><small>Samlad leverantörsreskontra</small></span><strong>${invoices.length}</strong></button>${list.map(s=>{const x=supplierSummary(s);return `<button class="supplier-ledger-card ${selectedSupplierId===s.id?'active':''}" data-supplier="${esc(s.id)}"><span><b>${esc(s.name)}</b><small>${esc(s.supplierNumber)} · Org.nr ${esc(s.orgNumber||'saknas')}</small></span><span class="supplier-card-money"><b>${ore(x.openOre)}</b><small>${x.openCount} öppna · ${x.count} totalt</small></span></button>`}).join('')}</div>`}
function invoiceRows(){const rows=invoices.filter(matches).sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate)));return rows.map(i=>{const s=supplierFor(i);return `<tr><td><b>${esc(s.name)}</b><small>${esc(s.supplierNumber)} · ${esc(s.orgNumber||'Org.nr saknas')}</small></td><td><b>${esc(i.supplierInvoiceNumber)}</b><small>${esc(i.invoiceDate)}</small></td><td>${esc(i.dueDate)}${invoiceOverdue(i)?'<small class="ledger-overdue">Förfallen</small>':''}</td><td><span class="ledger-status ${esc(i.status)}">${esc(statusLabel(i.status))}</span></td><td class="money">${ore(i.totalOre)}</td><td>${i.hasDocument?'<span class="doc-dot">PDF</span>':'—'}</td><td><a class="button ghost small" href="${url(`./payables.html#${encodeURIComponent(i.id)}`)}">Öppna faktura</a></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Inga leverantörsfakturor matchar sökningen.</td></tr>'}
function render(){const t=totals();app.innerHTML=`<div class="portal">${sidebar()}<section class="main"><header class="topbar"><div><h1>Leverantörsreskontra</h1><p>Leverantörer · fakturor · öppna saldon · förfallna poster</p></div><div class="user-chip"><b>${esc(session?.user?.displayName||'Demoanvändare')}</b></div></header><main class="content supplier-ledger-content">${isDemo?'<div class="demo-banner"><b>GitHub Pages-demo.</b> Alla leverantörer och fakturor är fiktiva.</div>':''}<section class="ledger-hero"><div><span class="eyebrow">Leverantörsreskontra</span><h2>Hitta en leverantör eller faktura direkt</h2><p>Sök på leverantörsnamn, leverantörsnummer, organisationsnummer eller fakturanummer. Välj en leverantör till vänster för att se dess reskontra.</p></div><div class="ledger-search-wrap"><input id="ledger-search" type="search" value="${esc(query)}" placeholder="Sök t.ex. Kustens, 559100-1209 eller KE-2088" aria-label="Sök i leverantörsreskontran"></div></section><section class="ledger-metrics"><article><span>Öppet saldo</span><strong>${ore(t.openOre)}</strong></article><article><span>Förfallet</span><strong>${ore(t.overdueOre)}</strong></article><article><span>Betalt</span><strong>${ore(t.paidOre)}</strong></article><article><span>Fakturor i urvalet</span><strong>${t.count}</strong></article></section><section class="ledger-layout"><aside class="panel ledger-suppliers"><div class="ledger-panel-head"><div><span class="eyebrow">Leverantörer</span><h3>Reskontra per leverantör</h3></div></div>${supplierCards()}</aside><section class="panel ledger-invoices"><div class="ledger-toolbar"><div class="ledger-tabs">${[['all','Alla'],['open','Öppna'],['overdue','Förfallna'],['paid','Betalda']].map(([id,label])=>`<button data-status="${id}" class="${statusFilter===id?'active':''}">${label}</button>`).join('')}</div><span>${selectedSupplierId==='all'?'Alla leverantörer':esc(suppliers.find(s=>s.id===selectedSupplierId)?.name||'')}</span></div><div class="ledger-table-wrap"><table class="ledger-table"><thead><tr><th>Leverantör</th><th>Faktura</th><th>Förfallodatum</th><th>Status</th><th class="money">Belopp</th><th>Underlag</th><th></th></tr></thead><tbody>${invoiceRows()}</tbody></table></div></section></section></main></section></div>`}
async function load(){if(isDemo){if(!Demo)throw new Error('Det gemensamma demoscenariot kunde inte laddas.');session={user:{displayName:'Demoanvändare'},company:{name:'Rollands Frukt o Grönt AB'}};const state=Demo.state();suppliers=structuredClone(state.suppliers||[]);invoices=structuredClone(state.supplierInvoices||[]);render();return}const state=await api('/session');if(!state.authenticated){location.href='./index.html';return}session=state;[suppliers,invoices]=await Promise.all([api('/payables/suppliers').then(x=>x.suppliers||[]),api('/payables/invoices').then(x=>x.invoices||[])]);render()}
document.addEventListener('input',e=>{if(e.target.id==='ledger-search'){query=e.target.value;render();const input=document.getElementById('ledger-search');input?.focus();input?.setSelectionRange(query.length,query.length)}});
document.addEventListener('click',e=>{const supplier=e.target.closest('[data-supplier]');if(supplier){selectedSupplierId=supplier.dataset.supplier;render();return}const status=e.target.closest('[data-status]');if(status){statusFilter=status.dataset.status;render()}});
load().catch(error=>{app.innerHTML=`<main class="boot"><strong>Leverantörsreskontran kunde inte laddas</strong><span>${esc(error.message)}</span></main>`});
