const app=document.getElementById('suppliers-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const csrfToken=sessionStorage.getItem('rollands-csrf')||'';
const Demo=globalThis.RollandsDemoScenario;
let session=null,suppliers=[],selected=null,history=[],message='';
let profileRequestId='',paymentRequestId='',profileInFlight=false,paymentInFlight=false;
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function newRequestId(prefix){return `${prefix}-${crypto.randomUUID()}`}
async function api(path,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.method&&options.method!=='GET'&&csrfToken?{'X-CSRF-Token':csrfToken}:{})};const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',...options,headers,body:options.body?JSON.stringify(options.body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Begäran misslyckades.');return data}
function url(path){return `${path}${isDemo?'?demo=1':''}`}
function sidebar(){return `<aside class="sidebar supplier-nav"><div class="logo"><strong>${esc(isDemo?'Rollands':session?.company?.name||'Företaget')}</strong><small>LT STUDIO</small></div><div class="company-pill">${esc(session?.company?.name||(isDemo?'Rollands Frukt o Grönt AB':'Företaget'))}<br>${isDemo?'Demoföretag':'Personlig session'}</div><div class="side-group"><span>Arbetsyta</span><a class="side-link" href="${url('./dashboard.html')}">Översikt</a></div><div class="side-group"><span>Ekonomi</span><a class="side-link" href="${url('./payables.html')}">Leverantörsfakturor</a><a class="side-link active" href="${url('./suppliers.html')}">Leverantörer</a><a class="side-link" href="${url('./automation.html')}">Automationskö</a></div><div class="sidebar-footer">Betalningsuppgifter sparas direkt och registreras i historiken.</div></aside>`}
function supplierList(){return `<section class="supplier-list panel"><div class="panel-head"><div><span class="eyebrow">Register</span><h2>Leverantörer</h2></div><strong>${suppliers.length}</strong></div><div class="supplier-search"><input id="supplier-search" placeholder="Sök leverantör"></div><div id="supplier-rows">${suppliers.map(s=>`<button class="supplier-row ${selected?.id===s.id?'selected':''}" data-supplier-id="${esc(s.id)}"><span><b>${esc(s.name)}</b><small>${esc(s.supplierNumber)} · ${esc(s.orgNumber||'Org.nr saknas')}</small></span><span>${esc(s.bankgiro||s.plusgiro||'Betalningsuppgift saknas')}</span></button>`).join('')}</div></section>`}
function detail(){if(!selected)return'<section class="panel supplier-detail"><p class="empty">Välj en leverantör.</p></section>';return `<section class="panel supplier-detail"><div class="panel-head"><div><span class="eyebrow">Leverantör</span><h2>${esc(selected.name)}</h2></div><span>${esc(selected.supplierNumber)}</span></div><div class="detail-grid"><form data-form="profile"><label>Namn<input name="name" value="${esc(selected.name)}" required></label><label>Organisationsnummer<input name="orgNumber" value="${esc(selected.orgNumber||'')}"></label><label>E-post<input name="email" type="email" value="${esc(selected.email||'')}"></label><label>Standardkonto<input name="defaultCostAccount" maxlength="4" value="${esc(selected.defaultCostAccount||'')}"></label><button class="button" type="submit">Spara leverantörsuppgifter</button></form><form data-form="payment"><div class="critical-box"><strong>Betalningsuppgifter</strong><p>Ändringar sparas direkt och registreras i ändringshistoriken.</p></div><label>Bankgiro<input name="bankgiro" value="${esc(selected.bankgiro||'')}"></label><label>Plusgiro<input name="plusgiro" value="${esc(selected.plusgiro||'')}"></label><button class="button" type="submit">Spara betalningsuppgifter</button></form></div><div class="history"><h3>Ändringshistorik</h3>${history.length?history.map(h=>`<article><b>${esc(h.changeType==='payment-details'?'Betalningsuppgifter':'Leverantörsuppgifter')}</b><span>${esc(new Date(h.changedAt).toLocaleString('sv-SE'))}</span><small>Ändrad av ${esc(h.changedBy)}</small></article>`).join(''):'<p class="empty">Ingen ändringshistorik ännu.</p>'}</div></section>`}
function render(){app.innerHTML=`<div class="supplier-shell">${sidebar()}<section class="supplier-main"><header class="topbar"><div><h1>Leverantörsregister</h1><p>Masterdata · betalningsuppgifter · historik</p></div><div class="user-chip"><b>${esc(session?.user?.displayName||'Demoanvändare')}</b></div></header><main class="content">${isDemo?'<div class="demo-banner"><b>Gemensamt UAT-scenario.</b> Samma leverantörer används av Leverantörsfakturor och Automationskö.</div>':''}${message?`<div class="notice">${esc(message)}</div>`:''}<div class="supplier-layout">${supplierList()}${detail()}</div></main></section></div>`}
function syncDemo(){if(!Demo)return;const state=Demo.state();suppliers=structuredClone(state.suppliers);if(selected)selected=suppliers.find(s=>s.id===selected.id)||suppliers[0]||null;history=selected?structuredClone(state.supplierHistory[selected.id]||[]):[]}
async function loadHistory(){if(!selected){history=[];return}if(isDemo){history=structuredClone(Demo.state().supplierHistory[selected.id]||[]);return}history=((await api(`/suppliers/${encodeURIComponent(selected.id)}/history`)).history||[])}
async function load(){if(isDemo){if(!Demo)throw new Error('Det gemensamma demoscenariot kunde inte laddas.');session={user:{displayName:'Demoanvändare'}};syncDemo();selected=suppliers[0]||null;await loadHistory();render();return}const s=await api('/session');if(!s.authenticated){location.href='./index.html';return}session=s;suppliers=(await api('/suppliers')).suppliers||[];selected=suppliers[0]||null;await loadHistory();render()}
async function saveProfile(form){
  if(profileInFlight)return;profileInFlight=true;
  try{
    const payload=Object.fromEntries(new FormData(form));
    if(isDemo){const id=selected.id;Demo.patch(state=>{const supplier=state.suppliers.find(s=>s.id===id);const before={name:supplier.name,orgNumber:supplier.orgNumber,email:supplier.email,defaultCostAccount:supplier.defaultCostAccount};Object.assign(supplier,payload);(state.supplierHistory[id]??=[]).unshift({id:`profile-${Date.now()}`,changeType:'profile',changedBy:'demo-accountant',changedAt:new Date().toISOString(),before,after:payload})});syncDemo();await loadHistory();message='Leverantörsuppgifterna sparades i det gemensamma demoscenariot.';return}
    profileRequestId=profileRequestId||newRequestId('supplier-profile');
    await api(`/suppliers/${encodeURIComponent(selected.id)}/profile`,{method:'PUT',body:{...payload,requestId:profileRequestId}});
    profileRequestId='';message='Leverantörsuppgifterna sparades.';suppliers=(await api('/suppliers')).suppliers||[];selected=suppliers.find(s=>s.id===selected.id)||null;await loadHistory();
  }finally{profileInFlight=false}
}
async function requestPayment(form){
  if(paymentInFlight)return;paymentInFlight=true;
  try{
    const payload=Object.fromEntries(new FormData(form));
    if(isDemo){const id=selected.id;Demo.patch(state=>{const supplier=state.suppliers.find(s=>s.id===id);const before={bankgiro:supplier.bankgiro||'',plusgiro:supplier.plusgiro||''};supplier.bankgiro=payload.bankgiro||'';supplier.plusgiro=payload.plusgiro||'';(state.supplierHistory[id]??=[]).unshift({id:`payment-${Date.now()}`,changeType:'payment-details',changedBy:'demo-accountant',changedAt:new Date().toISOString(),before,after:{bankgiro:supplier.bankgiro,plusgiro:supplier.plusgiro}})});syncDemo();await loadHistory();message='Betalningsuppgifterna sparades i det gemensamma demoscenariot.';return}
    paymentRequestId=paymentRequestId||newRequestId('supplier-payment');
    await api(`/suppliers/${encodeURIComponent(selected.id)}/payment-details`,{method:'POST',body:{...payload,requestId:paymentRequestId}});
    paymentRequestId='';message='Betalningsuppgifterna har sparats.';suppliers=(await api('/suppliers')).suppliers||[];selected=suppliers.find(s=>s.id===selected.id)||null;await loadHistory();
  }finally{paymentInFlight=false}
}
document.addEventListener('click',async e=>{const row=e.target.closest('[data-supplier-id]');if(!row)return;selected=suppliers.find(s=>s.id===row.dataset.supplierId)||null;await loadHistory();render()});
document.addEventListener('input',e=>{const form=e.target.closest('form[data-form]');if(!form)return;if(form.dataset.form==='profile'&&!profileInFlight)profileRequestId='';if(form.dataset.form==='payment'&&!paymentInFlight)paymentRequestId=''});
document.addEventListener('submit',async e=>{const form=e.target.closest('form[data-form]');if(!form)return;e.preventDefault();try{if(form.dataset.form==='profile')await saveProfile(form);else await requestPayment(form);render()}catch(error){message=error.message;const existing=app.querySelector('.notice');if(existing)existing.textContent=message;else app.querySelector('.content')?.insertAdjacentHTML('afterbegin',`<div class="notice">${esc(message)}</div>`)}});
document.addEventListener('input',e=>{if(e.target.id!=='supplier-search')return;const q=e.target.value.toLowerCase();document.querySelectorAll('.supplier-row').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(q))});
load().catch(error=>{app.innerHTML=`<main class="boot"><strong>Leverantörsregistret kunde inte laddas</strong><span>${esc(error.message)}</span></main>`});
