const app=document.getElementById('suppliers-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const csrfToken=sessionStorage.getItem('rollands-csrf')||'';
const Demo=globalThis.RollandsDemoScenario;
let session=null,suppliers=[],selected=null,history=[],message='',creating=false,searchQuery='',searchOpen=false,searchActiveIndex=-1,toast=null;
let toastTimer=null,profileRequestId='',paymentRequestId='',profileInFlight=false,paymentInFlight=false;
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function newRequestId(prefix){return `${prefix}-${crypto.randomUUID()}`}
async function api(path,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.method&&options.method!=='GET'&&csrfToken?{'X-CSRF-Token':csrfToken}:{})};const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',...options,headers,body:options.body?JSON.stringify(options.body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Begäran misslyckades.');return data}
function url(path){return `${path}${isDemo?'?demo=1':''}`}
function sidebar(){return `<aside class="sidebar supplier-nav"><div class="logo"><strong>${esc(isDemo?'Rollands':session?.company?.name||'Företaget')}</strong><small>LT STUDIO</small></div><div class="company-pill">${esc(session?.company?.name||(isDemo?'Rollands Frukt o Grönt AB':'Företaget'))}<br>${isDemo?'Demoföretag':'Personlig session'}</div><div class="side-group"><span>Arbetsyta</span><a class="side-link" href="${url('./dashboard.html')}">Översikt</a></div><div class="side-group"><span>Ekonomi</span><a class="side-link" href="${url('./payables.html')}">Leverantörsfakturor</a><a class="side-link active" href="${url('./suppliers.html')}">Leverantörer</a><a class="side-link" href="${url('./automation.html')}">Automationskö</a></div><div class="sidebar-footer">Betalningsuppgifter sparas direkt och registreras i historiken.</div></aside>`}
function nextSupplierNumber(){const max=suppliers.reduce((n,s)=>Math.max(n,Number(String(s.supplierNumber||'').replace(/\D/g,''))||0),0);return 'L-'+String(Math.max(1,max+1)).padStart(4,'0')}
function normalizeSearch(value){return String(value||'').trim().toLocaleLowerCase('sv-SE')}
function supplierMatchesPrefix(supplier,query){const q=normalizeSearch(query);if(!q)return true;return [supplier.name,supplier.supplierNumber,supplier.orgNumber].some(value=>normalizeSearch(value).startsWith(q))}
function supplierSuggestions(){return searchQuery?suppliers.filter(s=>supplierMatchesPrefix(s,searchQuery)).slice(0,8):[]}
function supplierSuggestionHtml(){const rows=supplierSuggestions();if(!rows.length)return '<div class="supplier-search-empty">Inga leverantörer börjar på det du har skrivit.</div>';return rows.map((s,index)=>`<button type="button" class="supplier-search-option ${index===searchActiveIndex?'active':''}" role="option" aria-selected="${index===searchActiveIndex?'true':'false'}" data-supplier-suggestion="${esc(s.id)}"><span><b>${esc(s.name)}</b><small>${esc(s.supplierNumber)}${s.orgNumber?' · '+esc(s.orgNumber):''}</small></span><span>${esc(s.bankgiro||s.plusgiro||'')}</span></button>`).join('')}
function updateSearchUi(){const field=document.getElementById('supplier-search'),box=document.getElementById('supplier-search-results');if(!field||!box)return;const open=Boolean(searchOpen&&searchQuery);field.setAttribute('aria-expanded',open?'true':'false');box.hidden=!open;if(open)box.innerHTML=supplierSuggestionHtml();document.querySelectorAll('.supplier-row').forEach(row=>{const supplier=suppliers.find(s=>s.id===row.dataset.supplierId);row.hidden=Boolean(searchQuery&&!supplierMatchesPrefix(supplier,searchQuery))})}
function queueToast(text){toast={text:String(text||'Sparad')};clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toast=null;render()},2400)}
function toastHtml(){return toast?`<div class="supplier-toast" role="status" aria-live="polite"><span class="supplier-toast-check">✓</span><span><b>Sparad</b><small>${esc(toast.text)}</small></span></div>`:''}
function createSupplierForm(){return `<section class="sales-panel supplier-detail"><div class="panel-head"><div><span class="eyebrow">Ny leverantör</span><h2>Lägg till leverantör</h2></div><button type="button" class="button ghost small" data-cancel-new-supplier>Avbryt</button></div><form data-form="create" class="detail-grid supplier-create-form"><label>Leverantörsnummer<input name="supplierNumber" value="${esc(nextSupplierNumber())}" required maxlength="40"></label><label>Namn<input name="name" required maxlength="160"></label><label>Organisationsnummer<input name="orgNumber" maxlength="40"></label><label>E-post<input name="email" type="email" maxlength="254"></label><label>Standardkonto<input name="defaultCostAccount" inputmode="numeric" maxlength="4" placeholder="4010"></label><label>Bankgiro<input name="bankgiro" maxlength="40"></label><label>Plusgiro<input name="plusgiro" maxlength="40"></label><div class="critical-box"><strong>Betalningsuppgifter</strong><p>Bankgiro och plusgiro sparas tillsammans med leverantören och kan därefter ändras i leverantörens detaljvy.</p></div><div class="modal-actions"><button class="button" type="submit">Skapa leverantör</button><button class="button ghost" type="button" data-cancel-new-supplier>Avbryt</button></div></form></section>`;}
function supplierList(){return `<section class="sales-panel supplier-list"><div class="panel-head"><div><span class="eyebrow">Register</span><h2>Leverantörer</h2><p>Sök på namn, leverantörsnummer eller organisationsnummer.</p></div><div class="supplier-count"><strong>${suppliers.length}</strong><small>leverantörer</small></div></div><div class="supplier-search-wrap"><label class="supplier-search-label" for="supplier-search">Sök leverantör</label><div class="supplier-search-control"><span class="supplier-search-icon" aria-hidden="true">⌕</span><input id="supplier-search" type="search" role="combobox" aria-autocomplete="list" aria-controls="supplier-search-results" aria-expanded="false" autocomplete="off" placeholder="Börja skriva namn eller nummer…" value="${esc(searchQuery)}"><span class="supplier-search-pulse" aria-hidden="true"></span></div><div id="supplier-search-results" class="supplier-search-results" role="listbox" ${searchOpen&&searchQuery?'':'hidden'}>${searchOpen&&searchQuery?supplierSuggestionHtml():''}</div></div><div id="supplier-rows" class="supplier-rows">${suppliers.map(s=>`<button class="supplier-row ${selected?.id===s.id?'selected':''}" data-supplier-id="${esc(s.id)}"><span><b>${esc(s.name)}</b><small>${esc(s.supplierNumber)} · ${esc(s.orgNumber||'Org.nr saknas')}</small></span><span>${esc(s.bankgiro||s.plusgiro||'Betalningsuppgift saknas')}</span></button>`).join('')}</div></section>`}
function detail(){if(creating)return createSupplierForm();if(!selected)return'<section class="sales-panel supplier-detail"><p class="empty">Välj en leverantör eller skapa en ny.</p></section>';return `<section class="sales-panel supplier-detail"><div class="panel-head"><div><span class="eyebrow">Leverantör</span><h2>${esc(selected.name)}</h2></div><span>${esc(selected.supplierNumber)}</span></div><div class="detail-grid"><form data-form="profile"><label>Namn<input name="name" value="${esc(selected.name)}" required></label><label>Organisationsnummer<input name="orgNumber" value="${esc(selected.orgNumber||'')}"></label><label>E-post<input name="email" type="email" value="${esc(selected.email||'')}"></label><label>Standardkonto<input name="defaultCostAccount" maxlength="4" value="${esc(selected.defaultCostAccount||'')}"></label><button class="button" type="submit">Spara leverantörsuppgifter</button></form><form data-form="payment"><div class="critical-box"><strong>Betalningsuppgifter</strong><p>Ändringar sparas direkt och registreras i ändringshistoriken.</p></div><label>Bankgiro<input name="bankgiro" value="${esc(selected.bankgiro||'')}"></label><label>Plusgiro<input name="plusgiro" value="${esc(selected.plusgiro||'')}"></label><button class="button" type="submit">Spara betalningsuppgifter</button></form></div><div class="history"><h3>Ändringshistorik</h3>${history.length?history.map(h=>`<article><b>${esc(h.changeType==='payment-details'?'Betalningsuppgifter':'Leverantörsuppgifter')}</b><span>${esc(new Date(h.changedAt).toLocaleString('sv-SE'))}</span><small>Ändrad av ${esc(h.changedBy)}</small></article>`).join(''):'<p class="empty">Ingen ändringshistorik ännu.</p>'}</div></section>`}
function render(){app.innerHTML=`<div class="portal"><aside class="sidebar"></aside><section class="main"><header class="topbar"><div><h1>Leverantörer</h1><p>Register & verksamhet / Leverantörsregister</p></div></header><main class="content sales-content">${isDemo?'<div class="demo-banner"><b>Gemensamt UAT-scenario.</b> Samma leverantörer används av Leverantörsfakturor och Automationskö.</div>':''}${message?`<div class="notice" role="alert">${esc(message)}</div>`:''}<div class="sales-head supplier-page-head"><div><h2>Leverantörsregister & betalningsuppgifter</h2><p>Hantera leverantörer, betalningsuppgifter och ändringshistorik på samma sätt som i kundregistret.</p></div><div class="sales-actions"><a class="button ghost" href="${url('./payables.html')}">Leverantörsfakturor</a><button type="button" class="button" data-new-supplier>+ Ny leverantör</button></div></div><div class="supplier-layout">${supplierList()}${detail()}</div></main></section></div>${toastHtml()}`;updateSearchUi()}
function syncDemo(){if(!Demo)return;const state=Demo.state();suppliers=structuredClone(state.suppliers);if(selected)selected=suppliers.find(s=>s.id===selected.id)||suppliers[0]||null;history=selected?structuredClone(state.supplierHistory[selected.id]||[]):[]}
async function loadHistory(){if(!selected){history=[];return}if(isDemo){history=structuredClone(Demo.state().supplierHistory[selected.id]||[]);return}history=((await api(`/suppliers/${encodeURIComponent(selected.id)}/history`)).history||[])}
async function load(){if(isDemo){if(!Demo)throw new Error('Det gemensamma demoscenariot kunde inte laddas.');session={user:{displayName:'Demoanvändare'}};syncDemo();selected=suppliers[0]||null;await loadHistory();render();return}const s=await api('/session');if(!s.authenticated){location.href='./index.html';return}session=s;suppliers=(await api('/suppliers')).suppliers||[];selected=suppliers[0]||null;await loadHistory();render()}
async function createSupplier(form){
  const payload=Object.fromEntries(new FormData(form));
  if(!String(payload.name||'').trim())throw new Error('Ange leverantörens namn.');
  if(!String(payload.supplierNumber||'').trim())throw new Error('Ange leverantörsnummer.');
  if(isDemo){
    const supplier={id:crypto.randomUUID(),supplierNumber:String(payload.supplierNumber).trim(),name:String(payload.name).trim(),orgNumber:String(payload.orgNumber||'').trim(),email:String(payload.email||'').trim(),defaultCostAccount:String(payload.defaultCostAccount||'').trim(),bankgiro:String(payload.bankgiro||'').trim(),plusgiro:String(payload.plusgiro||'').trim()};
    Demo.patch(state=>{state.suppliers=[...(state.suppliers||[]),supplier];state.supplierHistory??={};state.supplierHistory[supplier.id]=[]});
    syncDemo();selected=suppliers.find(s=>s.id===supplier.id)||null;creating=false;message='';queueToast('Leverantören har skapats.');await loadHistory();return;
  }
  const result=await api('/payables/suppliers',{method:'POST',body:payload});
  suppliers=(await api('/suppliers')).suppliers||[];
  selected=suppliers.find(s=>s.id===result.supplier?.id)||result.supplier||null;
  creating=false;message='';queueToast(result.duplicate?'Leverantören fanns redan med samma uppgifter.':'Leverantören har skapats.');await loadHistory();
}
async function saveProfile(form){
  if(profileInFlight)return;profileInFlight=true;
  try{
    const payload=Object.fromEntries(new FormData(form));
    if(isDemo){const id=selected.id;Demo.patch(state=>{const supplier=state.suppliers.find(s=>s.id===id);const before={name:supplier.name,orgNumber:supplier.orgNumber,email:supplier.email,defaultCostAccount:supplier.defaultCostAccount};Object.assign(supplier,payload);(state.supplierHistory[id]??=[]).unshift({id:`profile-${Date.now()}`,changeType:'profile',changedBy:'demo-accountant',changedAt:new Date().toISOString(),before,after:payload})});syncDemo();await loadHistory();message='';queueToast('Leverantörsuppgifterna är sparade.');return}
    profileRequestId=profileRequestId||newRequestId('supplier-profile');
    await api(`/suppliers/${encodeURIComponent(selected.id)}/profile`,{method:'PUT',body:{...payload,requestId:profileRequestId}});
    profileRequestId='';message='';queueToast('Leverantörsuppgifterna är sparade.');suppliers=(await api('/suppliers')).suppliers||[];selected=suppliers.find(s=>s.id===selected.id)||null;await loadHistory();
  }finally{profileInFlight=false}
}
async function requestPayment(form){
  if(paymentInFlight)return;paymentInFlight=true;
  try{
    const payload=Object.fromEntries(new FormData(form));
    if(isDemo){const id=selected.id;Demo.patch(state=>{const supplier=state.suppliers.find(s=>s.id===id);const before={bankgiro:supplier.bankgiro||'',plusgiro:supplier.plusgiro||''};supplier.bankgiro=payload.bankgiro||'';supplier.plusgiro=payload.plusgiro||'';(state.supplierHistory[id]??=[]).unshift({id:`payment-${Date.now()}`,changeType:'payment-details',changedBy:'demo-accountant',changedAt:new Date().toISOString(),before,after:{bankgiro:supplier.bankgiro,plusgiro:supplier.plusgiro}})});syncDemo();await loadHistory();message='';queueToast('Betalningsuppgifterna har sparats.');return}
    paymentRequestId=paymentRequestId||newRequestId('supplier-payment');
    await api(`/suppliers/${encodeURIComponent(selected.id)}/payment-details`,{method:'POST',body:{...payload,requestId:paymentRequestId}});
    paymentRequestId='';message='';queueToast('Betalningsuppgifterna har sparats.');suppliers=(await api('/suppliers')).suppliers||[];selected=suppliers.find(s=>s.id===selected.id)||null;await loadHistory();
  }finally{paymentInFlight=false}
}
document.addEventListener('click',async e=>{if(e.target.closest('[data-new-supplier]')){creating=true;selected=null;history=[];message='';searchOpen=false;render();return}if(e.target.closest('[data-cancel-new-supplier]')){creating=false;selected=suppliers[0]||null;await loadHistory();render();return}const suggestion=e.target.closest('[data-supplier-suggestion]');if(suggestion){creating=false;selected=suppliers.find(s=>s.id===suggestion.dataset.supplierSuggestion)||null;searchQuery='';searchOpen=false;searchActiveIndex=-1;await loadHistory();render();return}if(!e.target.closest('.supplier-search-wrap')){searchOpen=false;updateSearchUi()}const row=e.target.closest('[data-supplier-id]');if(!row)return;creating=false;selected=suppliers.find(s=>s.id===row.dataset.supplierId)||null;searchQuery='';searchOpen=false;await loadHistory();render()});
document.addEventListener('input',e=>{const form=e.target.closest('form[data-form]');if(!form)return;if(form.dataset.form==='profile'&&!profileInFlight)profileRequestId='';if(form.dataset.form==='payment'&&!paymentInFlight)paymentRequestId=''});
document.addEventListener('submit',async e=>{const form=e.target.closest('form[data-form]');if(!form)return;e.preventDefault();try{if(form.dataset.form==='create')await createSupplier(form);else if(form.dataset.form==='profile')await saveProfile(form);else await requestPayment(form);render()}catch(error){message=error.message;const existing=app.querySelector('.notice');if(existing)existing.textContent=message;else app.querySelector('.content')?.insertAdjacentHTML('afterbegin',`<div class="notice">${esc(message)}</div>`)}});
document.addEventListener('input',e=>{if(e.target.id!=='supplier-search')return;searchQuery=e.target.value;searchOpen=Boolean(normalizeSearch(searchQuery));searchActiveIndex=-1;updateSearchUi()});
document.addEventListener('focusin',e=>{if(e.target.id!=='supplier-search')return;if(normalizeSearch(e.target.value)){searchOpen=true;updateSearchUi()}});
document.addEventListener('keydown',async e=>{if(e.target.id!=='supplier-search')return;const rows=supplierSuggestions();if(e.key==='Escape'){searchOpen=false;searchActiveIndex=-1;updateSearchUi();return}if(!rows.length)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();searchOpen=true;const step=e.key==='ArrowDown'?1:-1;searchActiveIndex=(searchActiveIndex+step+rows.length)%rows.length;updateSearchUi();return}if(e.key==='Enter'&&searchOpen){e.preventDefault();const choice=rows[Math.max(0,searchActiveIndex)];if(!choice)return;creating=false;selected=choice;searchQuery='';searchOpen=false;searchActiveIndex=-1;await loadHistory();render()}});
load().catch(error=>{app.innerHTML=`<main class="boot"><strong>Leverantörsregistret kunde inte laddas</strong><span>${esc(error.message)}</span></main>`});
