const app=document.getElementById('uat-app');
const Demo=globalThis.RollandsDemoScenario;
const isDemo=location.hostname==='ludwigberglund-coder.github.io'||new URLSearchParams(location.search).has('demo');
const KEY='rollands-uat-checklist-v1';
const q=isDemo?'?demo=1':'';
const steps=[
 {id:'navigation-v2',title:'Gemensam meny – byt sida och fäll ut rubriker',text:'Öppna Ekonomi och Systemadministration. Byt mellan flera moduler, öppna och stäng formulär och prova en smal skärm. Samma menyval ska finnas kvar. Rubrikerna fäller ihop och ut sina länkar. Äldre referensverktyg är tydligt märkta och har separat demodata.',href:`./dashboard.html${q}`},
 {id:'customers',title:'Kunder – skapa eller kontrollera en företagskund',text:'Öppna Kunder. Lägg in en fiktiv kund med fakturaadress, kontaktuppgifter och eventuellt VAT-nummer. Kunden ska kunna väljas i fakturaverktyget. Ändring i kundregistret ska inte skriva om en redan bokförd fakturas ursprungsuppgifter.',href:`./customers.html${q}`},
 {id:'invoice-v2',title:'Kundfaktura – fullständigt underlag och egna intäktskonton',text:'Skapa en faktura med två rader. Välj olika intäktskonton, exempelvis 3051 och ett eget 3099 som ni lagt till i Kontoplan & intäktskonton. Fyll i parter, adresser, datum, referenser, villkor och fiktiva betalningsuppgifter. Prova frakt, expeditionsavgift och blandad moms. Granska utan att bokföra; bokför sedan och kontrollera att valda konton används i verifikationen, inte ett hårdkodat 3010.',href:`./invoices.html${q}`},
 {id:'invoice-pdf-v2',title:'PDF – kundfaktura och hela det interna underlaget',text:'Öppna Visa / skriv ut på fakturan. Hämta faktura (PDF) och kontrollera fälten från mallen, momsuppdelningen, avgifterna, totalsumman och betalningsuppgifterna. Öppna utskriftsvyn: bara PDF-filen, inte adminmenyn, ska skrivas ut. Hämta hela underlaget (PDF): den ska också ha valda konton, bokföringsspår och interna anteckningar. Prova en längre faktura som kräver flera sidor.',href:`./invoices.html${q}`},
 {id:'receivables',title:'Kundreskontra – kontrollera den gemensamma kundfordran',text:'Den faktura ni nyss bokförde ska synas här. Kontrollera även Nordic Office Göteborg AB, faktura 310002, med 3 925,00 kr kvar att betala; den används i bankmatchningens fiktiva testscenario.',href:`./receivables.html${q}`},
 {id:'bank',title:'Bank – matcha den befintliga demoinbetalningen',text:'Hitta Nordic Office Göteborg AB, referens 310002 och 3 925,00 kr. Om status är Ej matchad: välj Analysera matchning. Ett förslag ska skapas för rätt faktura. CAMT/BAM-filimport ingår inte i denna testomgång.',href:`./bank.html${q}`},
 {id:'automation-bank',title:'Automationskö – granska kopplingen till kundfaktura',text:'Förslaget ska ange rätt kundfaktura och visa Debet 1930 Företagskonto / bank och Kredit 1510 Kundfordringar. Inget ska bokföras bara för att ett förslag visas eller granskas.',href:`./automation.html${q}`},
 {id:'automation-supplier',title:'Automationskö – granska leverantörskontering',text:'Kontrollera förslaget för Kustens Emballage AB, faktura KE-2088, 589,00 kr. Kostnadskonto, ingående moms och leverantörsskuld ska framgå i klartext.',href:`./automation.html${q}`},
 {id:'payables',title:'Leverantörsfakturor – följ attest och betalning',text:'Kontrollera leverantör, fakturanummer, belopp, moms, kontering och status. Följ BKS-771 genom skuldbokföring, betalningsförberedelse, separat frisläppning och fiktiv bankbekräftelse. Samma faktura och verifikation ska gå att följa efteråt.',href:`./payables.html${q}`},
 {id:'suppliers',title:'Leverantörsregister – kontrollera betalningsuppgifter',text:'Kustens Emballage AB ska finnas som L-120. Ändrade betalningsuppgifter ska gå till separat godkännande och inte börja användas omedelbart.',href:`./suppliers.html${q}`},
 {id:'documents',title:'Dokument – kontrollera affärskoppling',text:'Leverantörsfaktura GF-8821 ska ha en dokumentkoppling till rätt affärshändelse. Demots exempelkontrollsumma är inte ett bevis för att en verklig originalfil är arkiverad.',href:`./documents.html${q}`},
 {id:'accounting',title:'Bokföring – kontrollera konton och spårbarhet',text:'Öppna den nyss bokförda kundfakturans verifikation. Kontrollera de intäktskonton ni faktiskt valde, separata momskonton, debet och kredit. Summorna ska balansera. Kontrollera även periodlås och att rättelser görs med nya motverifikationer.',href:`./accounting.html${q}`},
 {id:'cms',title:'Webbplats & innehåll – utkast och förhandsvisning',text:'Ändra en ofarlig demotext, spara utkast och förhandsvisa. Juridiskt namn och organisationsnummer ska inte kunna ändras i CMS.',href:`./website.html${q}`},
 {id:'overall',title:'Helhetsbedömning',text:'Bedöm om ni alltid hittar samma verktyg via de gemensamma rubrikerna och om fakturan innehåller allt ni behöver. Kontrollera även lager, lön och rapporter. Notera konkreta fel eller önskemål; en grön testmarkering är er bedömning, inte ett produktionsgodkännande.',href:`./dashboard.html${q}`}
];
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function loadState(){try{return JSON.parse(localStorage.getItem(KEY)||'{}');}catch{return {};}}
function saveState(value){localStorage.setItem(KEY,JSON.stringify(value));}
function statusLabel(v){return ({ok:'Godkänd',issue:'Fel / behöver rättas',change:'Önskad ändring',untested:'Ej testad'})[v]||'Ej testad';}
function render(){
 const state=loadState(),done=steps.filter(s=>state[s.id]?.status==='ok').length;
 app.innerHTML=`<div class="uat-shell"><aside class="sidebar"></aside><section class="uat-main"><header class="topbar"><div><h1>Testa systemet</h1><p>Manuell testguide · scenario ${esc(Demo?.VERSION||'saknas')}</p></div><button class="button ghost" data-action="reset-demo">Återställ demoscenario</button></header><main class="content"><div class="demo-banner"><b>Gå igenom arbetsflödena i ordning.</b> Markeringar och anteckningar sparas i er egen webbläsare. Använd enbart fiktiva uppgifter. Inget skickas till en bank eller kund.</div><section class="uat-summary"><article><span>Godkända steg</span><strong>${done}/${steps.length}</strong></article><article><span>Scenario-datum</span><strong>${esc(Demo?.AS_OF_DATE||'—')}</strong></article><article><span>Datakälla</span><strong>Demodata</strong></article></section><section class="uat-list">${steps.map((step,index)=>{const row=state[step.id]||{status:'untested',note:''};return `<article class="uat-step ${esc(row.status||'untested')}"><div class="uat-step-head"><div><span class="step-status">${esc(statusLabel(row.status))}</span><h2>${index+1}. ${esc(step.title)}</h2></div><a class="button" href="${esc(step.href)}">Öppna modul</a></div><p>${esc(step.text)}</p><div class="uat-controls"><select data-status="${esc(step.id)}" aria-label="Teststatus: ${esc(step.title)}"><option value="untested" ${row.status==='untested'||!row.status?'selected':''}>Ej testad</option><option value="ok" ${row.status==='ok'?'selected':''}>Godkänd</option><option value="issue" ${row.status==='issue'?'selected':''}>Fel / behöver rättas</option><option value="change" ${row.status==='change'?'selected':''}>Önskad ändring</option></select><textarea data-note="${esc(step.id)}" rows="2" aria-label="Anteckning: ${esc(step.title)}" placeholder="Skriv vad ni såg eller vad ni vill ändra…">${esc(row.note||'')}</textarea></div></article>`;}).join('')}</section></main></section></div>`;
}
document.addEventListener('change',event=>{const id=event.target.dataset.status;if(!id)return;const state=loadState();state[id]={...(state[id]||{}),status:event.target.value,note:document.querySelector(`[data-note="${CSS.escape(id)}"]`)?.value||''};saveState(state);render();});
document.addEventListener('input',event=>{const id=event.target.dataset.note;if(!id)return;const state=loadState();state[id]={...(state[id]||{status:'untested'}),note:event.target.value};saveState(state);});
document.addEventListener('click',event=>{if(!event.target.closest('[data-action="reset-demo"]'))return;if(!confirm('Återställa hela demoscenariot och UAT-markeringarna?'))return;Demo?.reset();localStorage.removeItem(KEY);render();});
if(!isDemo)app.innerHTML='<main class="boot"><strong>Testguiden är avsedd för demon</strong><span>Öppna sidan med ?demo=1 för att använda fiktiva data.</span></main>';
else if(!Demo)app.innerHTML='<main class="boot"><strong>Demoscenario saknas</strong><span>Demodatan kunde inte laddas.</span></main>';
else render();
