const app=document.getElementById('uat-app');
const Demo=globalThis.RollandsDemoScenario;
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const KEY='rollands-uat-checklist-v1';
const q=isDemo?'?demo=1':'';
const steps=[
  {id:'receivables',title:'1. Kundreskontra – kontrollera kundfaktura 310002',text:'Öppna kundreskontran och kontrollera att Nordic Office Göteborg AB har faktura 310002 med 3 925,00 kr kvar att betala. Denna restpost används senare i bankmatchningen.',href:`./index.html${q}`},
  {id:'bank',title:'2. Bank – matcha inbetalningen 3 925,00 kr',text:'Öppna Bank & avstämning. Hitta Nordic Office Göteborg AB, referens 310002 och 3 925,00 kr. Om status är Ej matchad: klicka Analysera matchning. Systemet ska föreslå faktura/avi 310002.',href:`./bank.html${q}`},
  {id:'automation-bank',title:'3. Automationskö – granska omföring till faktura/avi',text:'Öppna Automationskön. Förslaget ska tydligt säga att en inbetalning ska kopplas till kundfaktura/avi 310002 och visa Debet 1930 Företagskonto / bank och Kredit 1510 Kundfordringar. Prova att öppna kontorullistan. Inget ska bokföras bara för att förslaget godkänns.',href:`./automation.html${q}`},
  {id:'automation-supplier',title:'4. Automationskö – granska leverantörskontering',text:'Kontrollera förslaget för Kustens Emballage AB, faktura KE-2088, 589,00 kr. Det ska visa föreslagen kontering i klartext: 5460 Förbrukningsmaterial, 2641 Ingående moms och 2440 Leverantörsskulder. Byt gärna kostnadskonto i rullistan och spara.',href:`./automation.html${q}`},
  {id:'payables',title:'5. Leverantörsfakturor – följ attest och betalning',text:'Öppna Leverantörsfakturor. Kontrollera att leverantör, fakturanummer, belopp, moms, kontering och status är begripliga. Testa särskilt BKS-771 som är klar för betalningssteget och KE-2088 som behöver kontering.',href:`./payables.html${q}`},
  {id:'suppliers',title:'6. Leverantörsregister – kontrollera masterdata och fyrögonprincip',text:'Öppna Leverantörer. Kustens Emballage AB ska finnas som L-120. Kontrollera att ändring av betalningsuppgifter ligger i separat godkännandekö och inte används direkt.',href:`./suppliers.html${q}`},
  {id:'documents',title:'7. Dokument – kontrollera koppling till affärshändelse',text:'Öppna Dokument. Leverantörsfaktura GF-8821 ska vara kopplad till leverantörsfakturan och visa kontrollsumma. Originalprincipen ska vara tydlig.',href:`./documents.html${q}`},
  {id:'accounting',title:'8. Bokföring – kontrollera spårbarhet',text:'Öppna Bokföring. Kontrollera att verifikationer visar konto, text, debet och kredit och att rättelse sker genom en ny motverifikation. Periodlås och upplåsningskö ska vara begripliga.',href:`./accounting.html${q}`},
  {id:'cms',title:'9. Webbplats & innehåll – prova utkast och förhandsvisning',text:'Öppna Webbplats & innehåll. Ändra en ofarlig demotext, spara utkast och förhandsvisa. Juridiskt namn och organisationsnummer ska inte kunna ändras i CMS.',href:`./website.html${q}`},
  {id:'overall',title:'10. Helhetsbedömning',text:'Gå tillbaka till Översikt och bedöm om navigation, språk och arbetsflöden känns som ett sammanhängande småföretagssystem. Markera detta steg först när ni har gått igenom de andra.',href:`./dashboard.html${q}`}
];
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function loadState(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}
function saveState(value){localStorage.setItem(KEY,JSON.stringify(value))}
function statusLabel(v){return ({ok:'Godkänd',issue:'Fel / behöver rättas',change:'Önskad ändring',untested:'Ej testad'})[v]||'Ej testad'}
function render(){const state=loadState();const done=steps.filter(s=>state[s.id]?.status==='ok').length;app.innerHTML=`<div class="uat-shell"><aside class="sidebar"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">Rollands Frukt o Grönt AB<br>UAT / demogranskning</div><div class="side-group"><span>Test</span><a class="side-link active" href="./uat.html${q}">Testa systemet</a><a class="side-link" href="./dashboard.html${q}">Översikt</a></div><div class="sidebar-footer">All data i denna testguide är fiktiv.</div></aside><section class="uat-main"><header class="topbar"><div><h1>Testa systemet</h1><p>Sammanhängande UAT-guide · scenario ${esc(Demo?.VERSION||'saknas')}</p></div><button class="button ghost" data-action="reset-demo">Återställ demoscenario</button></header><main class="content"><div class="demo-banner"><b>Syftet med denna sida:</b> ni ska kunna gå igenom systemet i ordning och markera vad som fungerar, vad som är fel och vad ni vill ändra. Inga markeringar påverkar riktig bokföring eller riktiga data.</div><section class="uat-summary"><article><span>Godkända steg</span><strong>${done}/${steps.length}</strong></article><article><span>Scenario-datum</span><strong>${esc(Demo?.AS_OF_DATE||'—')}</strong></article><article><span>Datakälla</span><strong>Gemensam demo</strong></article></section><section class="uat-list">${steps.map(step=>{const row=state[step.id]||{status:'untested',note:''};return `<article class="uat-step ${esc(row.status||'untested')}"><div class="uat-step-head"><div><span class="step-status">${esc(statusLabel(row.status))}</span><h2>${esc(step.title)}</h2></div><a class="button" href="${esc(step.href)}">Öppna modul</a></div><p>${esc(step.text)}</p><div class="uat-controls"><select data-status="${esc(step.id)}"><option value="untested" ${row.status==='untested'||!row.status?'selected':''}>Ej testad</option><option value="ok" ${row.status==='ok'?'selected':''}>Godkänd</option><option value="issue" ${row.status==='issue'?'selected':''}>Fel / behöver rättas</option><option value="change" ${row.status==='change'?'selected':''}>Önskad ändring</option></select><textarea data-note="${esc(step.id)}" rows="2" placeholder="Skriv vad ni såg eller vad ni vill ändra…">${esc(row.note||'')}</textarea></div></article>`}).join('')}</section></main></section></div>`}
document.addEventListener('change',event=>{const id=event.target.dataset.status;if(!id)return;const state=loadState();state[id]={...(state[id]||{}),status:event.target.value,note:document.querySelector(`[data-note="${CSS.escape(id)}"]`)?.value||''};saveState(state);render()});
document.addEventListener('input',event=>{const id=event.target.dataset.note;if(!id)return;const state=loadState();state[id]={...(state[id]||{status:'untested'}),note:event.target.value};saveState(state)});
document.addEventListener('click',event=>{if(!event.target.closest('[data-action="reset-demo"]'))return;if(!confirm('Återställa hela demoscenariot och UAT-markeringarna?'))return;Demo?.reset();localStorage.removeItem(KEY);render()});
if(!isDemo){app.innerHTML='<main class="boot"><strong>UAT-guiden är avsedd för demon</strong><span>Öppna sidan med ?demo=1 för att använda det fiktiva testsceariot.</span></main>'}else if(!Demo){app.innerHTML='<main class="boot"><strong>Demoscenario saknas</strong><span>Den gemensamma demodatan kunde inte laddas.</span></main>'}else render();
