-- Supabase Performance Advisor cleanup, phase 2.
-- Migration filename generated by Supabase CLI 2.118.0.
-- Preserve authorization semantics while caching row-independent request checks.

create or replace function lt_security.request_has_aal2_personal_session()
returns boolean
language sql
stable
security invoker
set search_path=''
as $$
  select
    coalesce((select auth.jwt()->>'aal'),'aal1')='aal2'
    and (select lt_security.session_within_personal_limit())
$$;

revoke all on function lt_security.request_has_aal2_personal_session() from public, anon;
grant execute on function lt_security.request_has_aal2_personal_session() to authenticated;

-- 37 shared UAT guards and 10 specialized policies currently repeat the same
-- row-independent AAL2 + personal-session checks. Replace that pair with one
-- scalar init-plan helper while leaving every row-dependent predicate intact.
do $$
declare
  r record;
  v_using text;
  v_check text;
  v_using_new text;
  v_check_new text;
  v_changed integer := 0;
  v_remaining integer := 0;
  v_old_aal constant text :=
    'COALESCE(( SELECT (auth.jwt() ->> ''aal''::text)), ''aal1''::text) = ''aal2''::text';
  v_old_session constant text :=
    '( SELECT lt_security.session_within_personal_limit() AS session_within_personal_limit)';
  v_new_request_guard constant text :=
    '( SELECT lt_security.request_has_aal2_personal_session() AS request_has_aal2_personal_session)';
begin
  for r in
    select schemaname,tablename,policyname,qual,with_check
    from pg_policies
    where schemaname='public'
      and (
        coalesce(qual,'') like '%'||v_old_aal||'%'
        or coalesce(with_check,'') like '%'||v_old_aal||'%'
      )
      and (
        coalesce(qual,'') like '%'||v_old_session||'%'
        or coalesce(with_check,'') like '%'||v_old_session||'%'
      )
    order by tablename,policyname
  loop
    v_using := r.qual;
    v_check := r.with_check;
    v_using_new := v_using;
    v_check_new := v_check;

    if v_using_new is not null then
      v_using_new := replace(v_using_new,v_old_aal,v_new_request_guard);
      v_using_new := replace(v_using_new,v_old_session,'true');
    end if;
    if v_check_new is not null then
      v_check_new := replace(v_check_new,v_old_aal,v_new_request_guard);
      v_check_new := replace(v_check_new,v_old_session,'true');
    end if;

    if v_using_new is not distinct from v_using
       and v_check_new is not distinct from v_check then
      raise exception 'RLS_INITPLAN_PHASE2_POLICY_NOT_REWRITTEN_%.%',r.tablename,r.policyname;
    end if;

    execute format(
      'alter policy %I on %I.%I%s%s',
      r.policyname,
      r.schemaname,
      r.tablename,
      case when v_using_new is null then '' else format(' using (%s)',v_using_new) end,
      case when v_check_new is null then '' else format(' with check (%s)',v_check_new) end
    );
    v_changed := v_changed + 1;
  end loop;

  if v_changed <> 47 then
    raise exception 'RLS_INITPLAN_PHASE2_EXPECTED_47_POLICIES_CHANGED_GOT_%',v_changed;
  end if;

  select count(*) into v_remaining
  from pg_policies
  where schemaname='public'
    and (
      coalesce(qual,'') like '%'||v_old_aal||'%'
      or coalesce(with_check,'') like '%'||v_old_aal||'%'
      or coalesce(qual,'') like '%'||v_old_session||'%'
      or coalesce(with_check,'') like '%'||v_old_session||'%'
    );

  if v_remaining <> 0 then
    raise exception 'RLS_INITPLAN_PHASE2_EXPECTED_0_OLD_REQUEST_GUARDS_GOT_%',v_remaining;
  end if;
end;
$$;

-- The remaining Advisor finding is a direct auth.uid() call in the manual
-- customer-payment read policy. Preserve the membership predicate exactly and
-- cache the request user id once per statement.
alter policy customer_manual_payments_company_read
on public.customer_manual_payments
using (
  exists (
    select 1
    from public.company_memberships m
    where m.company_id=customer_manual_payments.company_id
      and m.auth_user_id=(select auth.uid())
  )
);
