'use strict';

const Accounting=require('./accounting-store.js');

function reportError(message,code='ACCOUNTING_REPORT_ERROR',statusCode=422){const e=new Error(message);e.code=code;e.statusCode=statusCode;return e}
function text(v){return String(v??'').trim()}
function validateRange(from='',to=''){const start=text(from),end=text(to);if(start&&!Accounting.validDate(start))throw reportError('Från-datumet är ogiltigt.','INVALID_REPORT_FROM');if(end&&!Accounting.validDate(end))throw reportError('Till-datumet är ogiltigt.','INVALID_REPORT_TO');if(start&&end&&start>end)throw reportError('Från-datum får inte ligga efter till-datum.','INVALID_REPORT_RANGE');return{from:start,to:end}}
function accountClass(account){const n=Number(account);if(n>=1000&&n<=1999)return'asset';if(n>=2000&&n<=2999)return'equity-liability';if(n>=3000&&n<=3999)return'revenue';if(n>=4000&&n<=8999)return'cost';return'other'}
function vatClass(account){const n=Number(account);if(n>=2610&&n<=2639)return'output-vat';if(n>=2640&&n<=2649)return'input-vat';if(n>=2650&&n<=2659)return'vat-settlement';return''}
function rows(db,companyId,{from='',to=''}={}){const range=validateRange(from,to);let where='e.company_id=?',params=[companyId];if(range.from){where+=' AND e.posting_date>=?';params.push(range.from)}if(range.to){where+=' AND e.posting_date<=?';params.push(range.to)}return db.prepare(`SELECT e.id AS entryId,e.fiscal_year AS fiscalYear,e.series,e.sequence,e.number,e.posting_date AS postingDate,e.description,e.source_type AS sourceType,e.source_id AS sourceId,l.line_number AS lineNumber,l.account,l.line_text AS text,l.debit_ore AS debitOre,l.credit_ore AS creditOre FROM accounting_entries e JOIN accounting_entry_lines l ON l.entry_id=e.id WHERE ${where} ORDER BY e.posting_date,e.series,e.sequence,l.line_number`).all(...params)}
function entries(db,companyId,{from='',to='',limit=500}={}){const range=validateRange(from,to);const safe=Math.max(1,Math.min(1000,Number(limit)||500));let where='e.company_id=?',params=[companyId];if(range.from){where+=' AND e.posting_date>=?';params.push(range.from)}if(range.to){where+=' AND e.posting_date<=?';params.push(range.to)}params.push(safe);const headers=db.prepare(`SELECT e.id,e.fiscal_year AS fiscalYear,e.series,e.sequence,e.number,e.posting_date AS postingDate,e.description,e.source_type AS sourceType,e.source_id AS sourceId,e.created_by AS createdBy,e.created_at AS createdAt FROM accounting_entries e WHERE ${where} ORDER BY e.posting_date DESC,e.series DESC,e.sequence DESC LIMIT ?`).all(...params);const stmt=db.prepare(`SELECT line_number AS lineNumber,account,line_text AS text,debit_ore AS debitOre,credit_ore AS creditOre FROM accounting_entry_lines WHERE entry_id=? ORDER BY line_number`);return headers.map(entry=>({...entry,lines:stmt.all(entry.id)}))}
function trialBalance(sourceRows){const map=new Map();for(const row of sourceRows||[]){const current=map.get(row.account)||{account:row.account,debitOre:0,creditOre:0,balanceOre:0};current.debitOre+=Number(row.debitOre||0);current.creditOre+=Number(row.creditOre||0);current.balanceOre=current.debitOre-current.creditOre;map.set(row.account,current)}return [...map.values()].sort((a,b)=>a.account.localeCompare(b.account))}
function incomeStatement(sourceRows){const accounts=trialBalance(sourceRows).filter(row=>['revenue','cost'].includes(accountClass(row.account))).map(row=>({...row,class:accountClass(row.account),reportAmountOre:accountClass(row.account)==='revenue'?row.creditOre-row.debitOre:row.debitOre-row.creditOre}));const revenueOre=accounts.filter(a=>a.class==='revenue').reduce((s,a)=>s+a.reportAmountOre,0);const costOre=accounts.filter(a=>a.class==='cost').reduce((s,a)=>s+a.reportAmountOre,0);return{accounts,revenueOre,costOre,resultOre:revenueOre-costOre}}
function balanceSheet(sourceRows){const accounts=trialBalance(sourceRows).filter(row=>['asset','equity-liability'].includes(accountClass(row.account))).map(row=>({...row,class:accountClass(row.account),reportAmountOre:accountClass(row.account)==='asset'?row.debitOre-row.creditOre:row.creditOre-row.debitOre}));const assetsOre=accounts.filter(a=>a.class==='asset').reduce((s,a)=>s+a.reportAmountOre,0);const equityLiabilitiesOre=accounts.filter(a=>a.class==='equity-liability').reduce((s,a)=>s+a.reportAmountOre,0);return{accounts,assetsOre,equityLiabilitiesOre,differenceOre:assetsOre-equityLiabilitiesOre}}
function vatSummary(sourceRows){const accounts=trialBalance(sourceRows).filter(row=>vatClass(row.account)).map(row=>({...row,vatClass:vatClass(row.account),netOre:row.debitOre-row.creditOre}));const outputVatOre=accounts.filter(a=>a.vatClass==='output-vat').reduce((s,a)=>s+(a.creditOre-a.debitOre),0);const inputVatOre=accounts.filter(a=>a.vatClass==='input-vat').reduce((s,a)=>s+(a.debitOre-a.creditOre),0);const settlementOre=accounts.filter(a=>a.vatClass==='vat-settlement').reduce((s,a)=>s+(a.creditOre-a.debitOre),0);return{accounts,outputVatOre,inputVatOre,settlementOre,netVatPayableOre:outputVatOre-inputVatOre}}
function periods(db,companyId){return db.prepare(`SELECT period,status,locked_by AS lockedBy,locked_at AS lockedAt FROM accounting_periods WHERE company_id=? ORDER BY period DESC`).all(companyId)}
function overview(db,companyId,range={}){const source=rows(db,companyId,range);return{range:validateRange(range.from,range.to),entryCount:new Set(source.map(r=>r.entryId)).size,lineCount:source.length,trialBalance:trialBalance(source),incomeStatement:incomeStatement(source),balanceSheet:balanceSheet(source),vatSummary:vatSummary(source)}}
module.exports=Object.freeze({validateRange,accountClass,vatClass,rows,entries,trialBalance,incomeStatement,balanceSheet,vatSummary,periods,overview});
