'use strict';

const fs=require('node:fs');
const path=require('node:path');
const Access=require('../../packages/access-control/authorization.js');
const Automation=require('../../packages/automation/proposals.js');
const CodingSuggestions=require('../../packages/automation/supplier-coding.js');
const Auth=require('./auth.js');
const Db=require('./database.js');
const Payables=require('./payables.js');
const PdfSecurity=require('./pdf-upload-security.js');
const SupplierAccounting=require('./supplier-accounting.js');
const Queues=require('./queues.js');
const Domain=require('../../packages/payables/supplier-invoices.js');
const {readJson,securityHeaders}=require('./app.js');

const DEFAULT_ACCESS=JSON.parse(fs.readFileSync(path.join(__dirname,'..','..','config','access-control.json'),'utf8'));
const SUPPORTED_SUPPLIER_VAT_TREATMENT='se-domestic-full-input-vat';
const PDF_LIMIT=10*1024*1024;
function routeError(message,code='PAYABLES_ROUTE_ERROR',statusCode=400){const e=new Error(message);e.code=code;e.statusCode=statusCode;return e}
function send(res,status,body,headers={}){if(res.writableEnded)return;res.writeHead(status,{...securityHeaders(),'Content-Type':'application/json; charset=utf-8',...headers});res.end(JSON.stringify(body))}
function readPdf(req,res){return new Promise((resolve,reject)=>{const type=String(req.headers['content-type']||'').split(';')[0].trim().toLowerCase();if(type!=='application/pdf'){send(res,415,{error:'PDF-uppladdning måste använda application/pdf.',code:'UNSUPPORTED_MEDIA_TYPE'});req.resume();return resolve(null)}const declared=Number(req.headers['content-length']||0);if(Number.isFinite(declared)&&declared>PDF_LIMIT){send(res,413,{error:'PDF-filen får vara högst 10 MB.',code:'DOCUMENT_TOO_LARGE'});req.resume();return resolve(null)}const chunks=[];let size=0;req.on('data',chunk=>{size+=chunk.length;if(size>PDF_LIMIT){if(!res.writableEnded)send(res,413,{error:'PDF-filen får vara högst 10 MB.',code:'DOCUMENT_TOO_LARGE'});chunks.length=0;req.destroy();return}chunks.push(chunk)});req.on('end',()=>{if(res.writableEnded)return resolve(null);resolve(Buffer.concat(chunks))});req.on('error',reject)})}
function documentName(req){const raw=String(req.headers['x-document-name']||'leverantorsfaktura.pdf');try{return decodeURIComponent(raw).replace(/[\r\n]/g,'').slice(0,180)||'leverantorsfaktura.pdf'}catch{return 'leverantorsfaktura.pdf'}}
// RFC 6266: ASCII fallback plus UTF-8 name, never raw user input in a header.
function pdfDisposition(name){
  const clean=String(name||'invoice.pdf').toWellFormed().replace(/[\x00-\x1f\x7f\\/]/g,'_').slice(0,180).toWellFormed();
  const encoded=encodeURIComponent(clean).replace(/['()*]/g,char=>'%'+char.charCodeAt(0).toString(16).toUpperCase());
  return `attachment; filename="invoice.pdf"; filename*=UTF-8''${encoded}`;
}
function createPayablesRouter(options){
  const db=options?.db;if(!db)throw new Error('Databas krävs.');Payables.initializePayables(db);SupplierAccounting.initializeSupplierAccounting(db);Queues.initializeQueues(db);
  const accessModel=Access.createModel(options.accessConfig||DEFAULT_ACCESS);
  function session(req){const token=Auth.parseCookies(req.headers.cookie).rollands_session;if(!token)return null;const s=Db.sessionByTokenHash(db,Auth.hashToken(token));if(!s||s.disabled)return null;s.actor={id:s.userId,name:s.displayName,companyId:s.companyId,authenticated:true,membershipActive:true,disabled:Boolean(s.disabled)};return s}
  function requireSession(req){const s=session(req);if(!s)throw routeError('Personlig inloggning krävs.','AUTH_REQUIRED',401);return s}
  function csrf(req,s){const supplied=String(req.headers['x-csrf-token']||'');if(!supplied||!Auth.safeEqualText(Auth.hashToken(supplied),s.csrfHash))throw routeError('Säkerhetskontrollen misslyckades.','CSRF_FAILED',403)}
  function permission(s,id){const d=Access.authorize(accessModel,s.actor,id);if(!d.allowed)throw routeError('Du saknar behörighet för åtgärden.','ACCESS_DENIED',403)}
  async function handle(req,res){
    let url;try{url=new URL(req.url,'http://localhost')}catch{return false}
    if(!url.pathname.startsWith('/api/v1/payables/'))return false;
    try{
      const s=requireSession(req);if(req.method!=='GET')csrf(req,s);
      if(url.pathname==='/api/v1/payables/suppliers'&&req.method==='GET'){permission(s,'supplier-invoice.view');return send(res,200,{suppliers:Payables.listSuppliers(db,s.companyId)}),true}
      if(url.pathname==='/api/v1/payables/suppliers'&&req.method==='POST'){permission(s,'supplier-invoice.register');const payload=await readJson(req,res);if(!payload)return true;const result=Db.transaction(db,()=>{const value=Payables.createSupplierIdempotent(db,{...payload,companyId:s.companyId});if(!value.duplicate)Db.appendAudit(db,{companyId:s.companyId,userId:s.userId,action:'SUPPLIER_CREATED',entityType:'supplier',entityId:value.supplier.id,details:{supplierNumber:value.supplier.supplierNumber,name:value.supplier.name}});return value});return send(res,result.duplicate?200:201,result),true}
      if(url.pathname==='/api/v1/payables/invoices'&&req.method==='GET'){permission(s,'supplier-invoice.view');return send(res,200,{invoices:Payables.listInvoices(db,s.companyId)}),true}
      if(url.pathname==='/api/v1/payables/invoices'&&req.method==='POST'){permission(s,'supplier-invoice.register');const payload=await readJson(req,res);if(!payload)return true;if(!Payables.supplierById(db,s.companyId,String(payload.supplierId||'')))throw routeError('Leverantören hittades inte.','SUPPLIER_NOT_FOUND',404);const vatTreatment=String(payload.vatTreatment||'').trim();if(vatTreatment!==SUPPORTED_SUPPLIER_VAT_TREATMENT)throw routeError('Den här versionen får endast registrera svenska leverantörsfakturor där hela den angivna momsen är avdragsgill. EU, import, omvänd betalningsskyldighet, momsfritt och begränsad avdragsrätt måste hanteras utanför det automatiska flödet tills uttryckligt stöd är verifierat.','UNSUPPORTED_SUPPLIER_VAT_TREATMENT',422);if(!Number.isSafeInteger(payload.vatOre)||payload.vatOre<=0)throw routeError('En svensk standardfaktura i detta flöde måste ha ett positivt momsbelopp. Fakturor utan debiterad moms kräver ett annat verifierat momsflöde.','UNSUPPORTED_SUPPLIER_VAT_TREATMENT',422);const result=Db.transaction(db,()=>{const value=Payables.createSupplierInvoiceIdempotent(db,{...payload,vatTreatment,companyId:s.companyId,registeredBy:s.userId});if(!value.duplicate)Db.appendAudit(db,{companyId:s.companyId,userId:s.userId,action:'SUPPLIER_INVOICE_REGISTERED',entityType:'supplier-invoice',entityId:value.invoice.id,details:{supplierId:value.invoice.supplierId,supplierInvoiceNumber:value.invoice.supplierInvoiceNumber,totalOre:value.invoice.totalOre,dueDate:value.invoice.dueDate,vatTreatment}});return value});return send(res,result.duplicate?200:201,{...result,vatTreatment}),true}
      if(req.method==='GET'&&url.pathname==='/api/v1/payables/payments'){permission(s,'payment.view');const date=String(url.searchParams.get('date')||'');const payments=Payables.listPayments(db,s.companyId,date);return send(res,200,{summary:date?Domain.paymentSummary(payments,date):null,payments}),true}
      const invoiceMatch=url.pathname.match(/^\/api\/v1\/payables\/invoices\/([^/]+)$/);
      if(invoiceMatch&&req.method==='GET'){permission(s,'supplier-invoice.view');const invoice=Payables.invoiceById(db,s.companyId,invoiceMatch[1]);if(!invoice)throw routeError('Fakturan hittades inte.','INVOICE_NOT_FOUND',404);return send(res,200,{invoice}),true}
      const pdfMatch=url.pathname.match(/^\/api\/v1\/payables\/invoices\/([^/]+)\/document$/);
      if(pdfMatch&&req.method==='PUT'){permission(s,'supplier-invoice.register');const bytes=await readPdf(req,res);if(!bytes)return true;const name=documentName(req);await PdfSecurity.assertSafePdfDeep(bytes,{fileName:name,maxBytes:PDF_LIMIT});const result=Db.transaction(db,()=>{const value=Payables.storeDocumentIdempotent(db,{companyId:s.companyId,invoiceId:pdfMatch[1],name,mime:'application/pdf',bytes});if(!value.duplicate)Db.appendAudit(db,{companyId:s.companyId,userId:s.userId,action:'SUPPLIER_INVOICE_DOCUMENT_STORED',entityType:'supplier-invoice',entityId:pdfMatch[1],details:{sha256:value.document.sha256,size:value.document.size}});return value});return send(res,result.duplicate?200:201,result),true}
      if(pdfMatch&&req.method==='GET'){permission(s,'supplier-invoice.view');const doc=Payables.document(db,s.companyId,pdfMatch[1]);res.writeHead(200,{...securityHeaders(),'Content-Type':'application/pdf','X-Frame-Options':'DENY','Content-Security-Policy':"sandbox; default-src 'none'; object-src 'none'; frame-ancestors 'none'; base-uri 'none'",'Content-Disposition':pdfDisposition(doc.name),'Content-Length':doc.bytes.length,'X-Document-SHA256':doc.sha256});res.end(doc.bytes);return true}
      const suggestionMatch=url.pathname.match(/^\/api\/v1\/payables\/invoices\/([^/]+)\/coding-suggestion$/);
      if(suggestionMatch&&req.method==='POST'){
        permission(s,'supplier-invoice.register');const invoice=Payables.invoiceById(db,s.companyId,suggestionMatch[1]);if(!invoice)throw routeError('Fakturan hittades inte.','INVOICE_NOT_FOUND',404);if(!['registered','coding-review','coded'].includes(invoice.status))throw routeError('Konteringsförslag kan inte skapas efter attest.','CODING_LOCKED',409);
        const supplier=Payables.supplierById(db,s.companyId,invoice.supplierId);const history=Payables.supplierHistory(db,s.companyId,invoice.supplierId,{excludeInvoiceId:invoice.id,limit:20});const suggestion=CodingSuggestions.suggestSupplierCoding(invoice,{supplier,history});
        const proposal=Automation.createProposal({companyId:s.companyId,type:'supplier-invoice-coding',sourceId:invoice.id,confidence:suggestion.confidence,deterministic:suggestion.deterministic,ambiguous:suggestion.ambiguous,reason:suggestion.reason,evidence:suggestion.evidence,suggestion:{invoiceId:invoice.id,lines:suggestion.coding},engine:{kind:'rules',name:'supplier-coding-history',version:'1'},createdBy:s.userId});
        const saved=Db.transaction(db,()=>{const stored=Queues.saveAutomationProposal(db,proposal,{idempotencyKey:`supplier-coding:${invoice.id}:${invoice.updatedAt}:v1`});if(!stored.duplicate)Db.appendAudit(db,{companyId:s.companyId,userId:s.userId,action:'SUPPLIER_CODING_SUGGESTED',entityType:'supplier-invoice',entityId:invoice.id,details:{proposalId:stored.proposal.id,confidence:stored.proposal.confidence,engine:stored.proposal.engine}});return stored});return send(res,200,{proposal:saved.proposal,coding:suggestion.coding,editable:true,duplicate:saved.duplicate}),true;
      }
      const codingMatch=url.pathname.match(/^\/api\/v1\/payables\/invoices\/([^/]+)\/coding$/);
      if(codingMatch&&req.method==='PUT'){permission(s,'supplier-invoice.register');const payload=await readJson(req,res);if(!payload)return true;const result=Db.transaction(db,()=>{const value=Payables.saveCodingIdempotent(db,{companyId:s.companyId,invoiceId:codingMatch[1],lines:payload.lines});if(!value.duplicate)Db.appendAudit(db,{companyId:s.companyId,userId:s.userId,action:'SUPPLIER_INVOICE_CODING_UPDATED',entityType:'supplier-invoice',entityId:value.invoice.id,details:{codingSha256:value.invoice.codingSha256}});return value});return send(res,200,result),true}
      const approveMatch=url.pathname.match(/^\/api\/v1\/payables\/invoices\/([^/]+)\/approve$/);
      if(approveMatch&&req.method==='POST'){permission(s,'supplier-invoice.approve');const payload=await readJson(req,res);if(!payload)return true;const invoice=Payables.invoiceById(db,s.companyId,approveMatch[1]);if(!invoice)throw routeError('Fakturan hittades inte.','INVOICE_NOT_FOUND',404);const workflow=Access.evaluateWorkflowAction(accessModel,s.actor,'supplier-invoice-approval',{registeredBy:invoice.registeredBy,approvedBy:s.userId});if(!workflow.allowed)throw routeError(workflow.reason,workflow.code,409);const result=Db.transaction(db,()=>{const value=Payables.approveIdempotent(db,{companyId:s.companyId,invoiceId:invoice.id,actorId:s.userId,expectedCodingSha256:payload.expectedCodingSha256,expectedDocumentSha256:payload.expectedDocumentSha256});if(!value.duplicate)Db.appendAudit(db,{companyId:s.companyId,userId:s.userId,action:'SUPPLIER_INVOICE_APPROVED',entityType:'supplier-invoice',entityId:value.invoice.id,details:{codingSha256:value.invoice.codingSha256,documentSha256:value.invoice.documentSha256}});return value});return send(res,200,result),true}
      const postMatch=url.pathname.match(/^\/api\/v1\/payables\/invoices\/([^/]+)\/post$/);
      if(postMatch&&req.method==='POST'){permission(s,'accounting.post');const invoice=Payables.invoiceById(db,s.companyId,postMatch[1]);if(!invoice)throw routeError('Fakturan hittades inte.','INVOICE_NOT_FOUND',404);if(invoice.vatTreatment!==SUPPORTED_SUPPLIER_VAT_TREATMENT)throw routeError('Leverantörsfakturans momsbehandling är inte verifierad för automatisk bokföring. Kontrollera underlaget och registrera via ett uttryckligt stött momsflöde.','SUPPLIER_VAT_TREATMENT_REQUIRED',409);const result=SupplierAccounting.postSupplierInvoice(db,{companyId:s.companyId,invoiceId:invoice.id,actorId:s.userId});return send(res,200,{...result,message:result.duplicate?`Leverantörsskulden var redan bokförd som ${result.entry.number}.`:`Leverantörsskulden är bokförd som ${result.entry.number}.`}),true}
      const dateCorrectionMatch=url.pathname.match(/^\/api\/v1\/payables\/invoices\/([^/]+)\/correct-dates$/);
      if(dateCorrectionMatch&&req.method==='POST'){permission(s,'accounting.post');const payload=await readJson(req,res);if(!payload)return true;const result=SupplierAccounting.correctSupplierInvoiceDates(db,{companyId:s.companyId,invoiceId:dateCorrectionMatch[1],requestId:payload.requestId,newInvoiceDate:payload.invoiceDate,newDueDate:payload.dueDate,reason:payload.reason,actorId:s.userId});return send(res,200,{...result,message:result.duplicate?'Fakturadatumets rättelse var redan registrerad.':'Fakturadatum och förfallodatum har rättats med bevarad bokföringshistorik.'}),true}
      const payMatch=url.pathname.match(/^\/api\/v1\/payables\/invoices\/([^/]+)\/prepare-payment$/);
      if(payMatch&&req.method==='POST'){permission(s,'payment.prepare');const payload=await readJson(req,res);if(!payload)return true;const invoice=Payables.invoiceById(db,s.companyId,payMatch[1]);if(!invoice)throw routeError('Fakturan hittades inte.','INVOICE_NOT_FOUND',404);const result=Db.transaction(db,()=>{const existing=Payables.paymentByInvoice(db,s.companyId,invoice.id);const value=Payables.preparePayment(db,{companyId:s.companyId,invoiceId:invoice.id,paymentDate:payload.paymentDate,amountOre:invoice.openAmountOre,account:payload.account||'1930',preparedBy:s.userId});const duplicate=Boolean(existing);if(!duplicate)Db.appendAudit(db,{companyId:s.companyId,userId:s.userId,action:'SUPPLIER_PAYMENT_PREPARED',entityType:'supplier-payment',entityId:value.id,details:{invoiceId:invoice.id,amountOre:value.amountOre,paymentDate:value.paymentDate}});return{payment:value,duplicate}});return send(res,result.duplicate?200:201,{...result,message:result.duplicate?'Betalningen var redan förberedd med samma uppgifter.':'Betalningen har förberetts.'}),true}
      send(res,404,{error:'Hittades inte.',code:'NOT_FOUND'});return true;
    }catch(error){const status=Number(error.statusCode||500);if(status>=500)console.error(error);send(res,status,{error:status>=500?'Ett internt serverfel uppstod.':String(error.message||'Begäran misslyckades.'),code:error.code||'INTERNAL_ERROR'});return true}
  }
  return Object.freeze({handle,accessModel});
}
module.exports=Object.freeze({createPayablesRouter});
